### ISSUE TITLE
Immutability and export

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida-core#1762]
The majority of the entity instances that are exported and imported are immutable. However, when an instance can change its values after storing it, problems can arise. The biggest problem is how we discover such changes and how we treat them.

For example, let a code C that exists with the same UUID at the databases of users U1 and U2.
U1 decides to update the code (prepend text) and use it for some calculations.
U2 uses the code without any change.
When exchanging data between U1 and U2, the import code will not update the code node because the UUID exists and it is already in the user's database. However, the code is not the same.

How should we address such issues (but also similar issues)?
Should we check the UUID of the immutable entities and the hashes of the rest?
How sealable entities can help us on the above problem?

This ticket is initially intended for discussion and to take decisions on this subject.

Idea below sealing:
- Before store you can change everything
- After store:
  - for Data, you cannot change anything anymore (this is enforced in aiida 1.0.0aX, not in 0.12.X)
  - the same should happen for Code, but not sure it if it is the case
  - for Calculations, you change only the updatable attrs
- After sealing (the concept exists only for Calculations), you can not change anything
A note: the logic of Sealing was fixed/improved in 1.0.0aX

**Comment by giovannipizzi** [comment]
Things to do (these can be moved to smaller issues once it's all clear):
- [ ] document the logic of sealing. Also, note that there are notable exceptions to what can be changed. E.g., label and description. The logic should be already in the code for caching/hashing. We should document this as well in the same section, and define the behaviour (e.g. overwrite the label, ignore the imported label, ...)
- [ ] make sure Code sealing works as for codes (connected to the issue of having Code be a subclass of Data #278)
- [ ] ensure we don't provide command line options to modify entities (e.g. `verdi computer update`, `verdi code update`; check also if there are API calls that would allow this). Note: if they exist, it's because this is useful/easy for the user. We shouldn't just disable those features, but replace with convenient commands to achieve the same goal but in the correct way (e.g. `verdi computer duplicate` instead of `verdi computer update`, etc.). Important to check also non-node entities where the Sealing concept does not exist (i.e. they should behave like data).
- [ ] have a flag to hash the nodes that are being imported and check if they changed (and in this case warn the user/give the option e.g. to keep the existing data, or replacing with imported one.
   - note that this should not happen unless the user messes up with its db (but might happen e.g. if there are data migrations and one is importing between different AiiDA versions...)
   - we should profile this option and check the performance bottleneck. If it's not too high, I would always put the check on hashing, and remove it optionally.

**Comment by giovannipizzi** [comment]
Closing as the various related PRs have been merged :-)
