### ISSUE TITLE
Put AiiDA in a seperate RabbitMQ virtual host

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida-core#2065]
Currently we use the default virtual host i.e. '/' and append a prefix to our queues/exchagnes to make sure it does not collide with other applications using the RMQ service (as it is 'global' to the computer).  Ideally we would use a seperate vhost and then we don't have to use the prefix on every queue and exchange (just the vhost name itself).

**Comment by sphuber** [comment]
This request is now one step closer thanks to #4341 which makes it possible to define the virtual host to use in the profile configuration. However, to use a specific virtual host, other than the `/` default, it has to be created first. Doing so is not obvious. There is an HTTP API that can be used to create vhosts, but I am not sure if one first has to enable it by installing the admin management plugin for RabbitMQ using `rabbitmq-plugins enable rabbitmq_management`. This would complicate the install procedure even more. If this is not necessary, we could have AiiDA's install operation attempt to create a virtual host and use that.

One final complication though is that certain computing centers provide a RabbitMQ instance and they are designated a vhost that should be used. In this case AiiDA cannot force the name to include the profile UUID. This may be ok, as long as it is made clear to the user that this virtual host should be reserved to be used only with this particular AiiDA profile.

**Comment by muhrin** [comment]
Thanks a lot Seb, great news.

Indeed creation of the vhost is certainly the awkward part here.  I would suggest the primary way of doing this be the CLI interface.  We could get AiiDA to spit out the command line string that can be used to create the appropriate vhost and if we want to take it to the next level we could even invoke the command ourselves (as we for now for creating the db).

I wouldn't necessarily force the UUID to be in the vhost name, I think having this as the default but allowing the user to choose whatever the want would be just fine.

Lastsly, I think it may be worth considering bundling all this up in a docker at some point.  This would make installing and configuring a standard setup of AiiDA a lot easier (not to mention the fact that I imagine installing RMQ without root is not trivial).  Maybe that's already how it's done for the AiiDA lab side of things, maybe @ltalirz knows more.

**Comment by greschd** [comment]
> not to mention the fact that I imagine installing RMQ without root is not trivial

Side question: is setting up docker without root much easier? I know of [rootless mode](https://docs.docker.com/engine/security/rootless/), but never tried it - do you have any experience with that? Anyway, I support creating a docker, but think it should still be possible to run "on the metal".

**Comment by sphuber** [comment]
The most important part for me is that we give flexibility to those who need it, but we keep it as automated and simple as possible for those who don't.

There are two use cases for using non-default virtual hosts.
1. The user of AiiDA wants to specify what virtual host to use.
2. AiiDA itself wants to use virtual hosts to separate profiles that use the same RabbitMQ instance

The first case is now supported so there is nothing left to do. The second case is what this issue is about. If we are going to implement this, it should really be fully automated. I don't think we can demand from a user to create a new virtual host every time they set up a new profile that is using the same RabbitMQ instance. Even if you say we try to simplify it by printing a command to run, that is not good enough. Automatic profile creation will be severely hampered and is in my opinion not really acceptable. So, as far as I see it, if we want to implement this, it is AiiDA that should be fully capable of creating the virtual hosts during profile setup. If this is not possible, I say we stay with the current model, which ultimately works just fine. Having separated virtual hosts would just be a "nicety" but wouldn't really change anything for users.

**Comment by ltalirz** [comment]
> Lastsly, I think it may be worth considering bundling all this up in a docker at some point. This would make installing and configuring a standard setup of AiiDA a lot easier (not to mention the fact that I imagine installing RMQ without root is not trivial). Maybe that's already how it's done for the AiiDA lab side of things, maybe @ltalirz knows more.

If you mean a container with aiida, rmq and postgres, that certainly exists: https://hub.docker.com/r/aiidateam/aiida-core (built on every commit to `develop`)


Otherwise I fully agree with the points made by @sphuber - while using virtual hosts to organize AiiDA profiles does seem like a good idea, it needs to be weighed against the downside of having to create/manage those virtual hosts.

I can imagine that this use case may come up in the context of multi-user platforms where we want to make sure keep information from different profiles isolated from each other, but I would point out that this is now already possible and platform administrators can be expected to know how to create virtual hosts (the only "downside" remaining would be the prefix in the queues, which is then useless, but that's not a big deal).

**Comment by greschd** [comment]
> the only "downside" remaining would be the prefix in the queues, which is then useless, but that's not a big deal

I'd consider that "defense in depth" from accidentally mixing RMQ queues - I think keeping the prefix regardless is a good idea.

**Comment by ltalirz** [comment]
I think that's a fair point. In that case, it looks to me like the issue should be closed  ;-)

**Comment by sphuber** [comment]
Done! :)
