### ISSUE TITLE
Export file size. Big exports.

### ISSUE THREAD

**Issue by broeder-j** [aiidateam/aiida-core#2399]
Related to #999 

We tried a 350 GB export, (160 K nodes). Export version 0.3, if this is better in newer versions, close this. I'm not so sure about the 350 GB, was an estimation from the file sizes sum of the calculations.
We had 800 GB disk space left. wasn't enough to do it. With the repo 'inode overhead' it is apparently to big.
(it failed when copying the files, before tar.) Backend was sqlalc, but since it was during file copy, it should not matter.

The data.json was 846 MB. So the file copy is not optimal

Suggestions:

1. Allow to provide a path for verdi export create where the temporary files can go...
which would allow to use some external storage, and not double the repo in the same place for big exports.

2. Export cleanup on failure, or a switch to export which will clean up if failed? (is everything in that temp folder?)

3. For me it seems not optimal that all the files are copied once into a separate folder then this is zipped together with a json for the nodes.
Could one avoid somehow copying the file physically? i.e use symlinks or something to collected them for the tar? The best solution would be a data stream of course, which could be directed everywhere.

4. When collecting the nodes in the beginning, estimate the export size and stop if there is not enough space. 

5. Allow for database only exports. (if repos become very large, they might be moved separately.)

**Comment by ltalirz** [comment]
1. Agreed.

2. If that is not yet the case, we should definitely do that.

3. Seems reasonable.

4. That is probably difficult with the current implementation of the file repository. Perhaps in a future implementation.

5. We should think about this.

@broeder-j You might be interested to contribute to upcoming discussions of the design on the new repositor and export file format. If that is the case, ping @ramirezfranciscof

**Comment by ltalirz** [comment]
> Allow to provide a path for verdi export create where the temporary files can go...

This is already possible, simply by setting the `TMPDIR` environment variable (see also the [tempfile docs](https://docs.python.org/3/library/tempfile.html) ).

> Export cleanup on failure, or a switch to export which will clean up if failed? (is everything in that temp folder?)

I assume this is the case - if not, please report.

> The best solution would be a data stream of course, which could be directed everywhere.

This will likely be the way it's done in the new archive format; see https://github.com/aiidateam/AEP/pull/21


This leaves the following two suggestions:


1. When collecting the nodes in the beginning, estimate the export size and stop if there is not enough space.

It is possible that we will not be doing this by default because it requires going first through all the DB content and then through all the files. 
For a memory-efficient approach we will need chunking, and we may want to iterate over batches of nodes instead of node DB and repository data separately.

However, one could implement this in a `--dry-run` approach that would simply collect data without writing it to disk and count how much space would be needed.

2. Allow for database only exports. (if repos become very large, they might be moved separately.)

Hopefully the disk aspect of the new archive format will be fast enough that this will no longer be desirable/necessary.

**Comment by chrisjsewell** [comment]
Heya, I'm going to mark this as being closed by #4534, and not there is also https://github.com/aiidateam/AEP/pull/21 which will improve this even further. But feel free to re-open if you still find issues

> Allow to provide a path for verdi export create where the temporary files can go
>  The best solution would be a data stream of course, which could be directed everywhere.

This is exactly what now happens.

All files are now written directly to the archive file (for zip and tar), i.e. before with a tar output the data was all written to a temporary folder first then compressed at the end, but now the tar file is created straight away and files are written into it. This means the memory used will only be the size of the final archive.

> Export cleanup on failure, or a switch to export which will clean up if failed? (is everything in that temp folder?)

Yep its all done in a temp folder so already gets cleaned

> When collecting the nodes in the beginning, estimate the export size and stop if there is not enough space.
> However, one could implement this in a --dry-run approach that would simply collect data without writing it to disk and count how much space would be needed.

with the export format there is now a "null" option, which basically does not write anything.
It does not estimate the export size, but that would be possible, especially since...

> Allow for database only exports.

with #4534 the `export` function now actually accepts a writer class, which you can essentially create yourself.

For example, you could subclass: `aiida/tools/importexport/archive/writers.py::WriterJsonTar` and remove the code in `write_node_repo_folder`. That is all that's needed to end up with an archive with database only content
