### ISSUE TITLE
Changing the default behaviour of the export set expansion rules

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida-core#2637]
In this issue we can discuss the default behaviour of the export rules.

These rules, based on a given set of nodes, they expand it to include nodes that are "expected" to be exported too.

The rules are described at issue #1102 as well as the default behaviour of these rules, and which of the they can be overridden.

Some ideas on how they can be changed are proposed at #2632 by @ltalirz 
https://github.com/aiidateam/aiida_core/pull/2632#issuecomment-475951114

**Comment by ltalirz** [comment]
Just to reiterate: the suggestion is to make what is currently achieved by the options `-RX` the default.

Furthermore, the current implementation of the `-C` option is very counterintuitive: while all other options turn the corresponding rules *on*,  `-C` turns the rule *off*
```
  -C, --create-reversed           Follow reverse CREATE links (recursively)
                                  when calculating the node set to export.
                                  [default: True]
```
The suggestion is to resolve this by having both `--create-reversed` and `--no-create-reversed` options (same for all other options).

**Comment by ltalirz** [comment]
Discussion April 17th 2019: 
 * the  `--create-reversed` and `--no-create-reversed` (same for other options) are already in 1.0
 * consider backporting them to 0.12

No conclusion reached yet concerning default behavior.

**Comment by ltalirz** [comment]
@CasperWA Do you know the current status of this issue?

I'm coming back to this because as of today's `develop`, it seems like the default settings for `verdi export` will export only the data provenance layer (only calculations and data), not the logical provenance (no workflows).
If people want to export the logical provenance, they currently need to add a number of options by hand.

I'm wondering whether this should be changed - shouldn't the default be to retain the logical provenance layer as well?
I would guess that most people want to retain this information when exporting.

**Comment by sphuber** [comment]
If I recall correctly, the reasoning for this is that if one really cares about the logical provenance, simply targeting the workflow node is the easiest as that will by default follow all the way down and include all the data provenance.

**Comment by ltalirz** [comment]
>  if one really cares about the logical provenance, simply targeting the workflow node is the easiest as that will by default follow all the way down and include all the data provenance.

In my view, exporting is about sharing the results of your calculations with provenance, i.e. the logic is intrinsically "bottom-up". 
This is the recipe I would recommend in the aiida-core docs for users who want to make an export for their publication:
  1. Make a list of the results you care about (Data nodes)
  2. Export those nodes

While you can try to do things top-down, this means you may export more than you need to, and even then you might lose logical provenance (e.g. if some inputs to the workchain you selected were also generated by a workchain, which will not be exported).

I would vote to keep logical provenance by default.

**Comment by giovannipizzi** [comment]
I think what we should do it to set to true by default the following of backwards CALL links (both for calc and work). This should be enough because if you have some data, by default you export also the CREATOR calculation, and if this was run by a workflow, having the backward-call turned on by default will also export the relevant workflows (i.e., the logical provenance).

I wouldn't instead put on by default the backwards-return, because after the creation a node could be returned by many independent workflows, and unless the users wants them (and then he/she could just target those WFs explicitly) those are not needed to show how the data was generated.
