### ISSUE TITLE
Merge `config.json` and `caching.yaml` configuration files

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#2701]
When merging the format has to be chosen, where `yaml` may be the best choice.
This would require the configuration migration framework to be rewritten however.

**Comment by ltalirz** [comment]
We discussed that we would look into this after the tutorial, together with moving the config.json to a config.yaml.

Note: when doing this, to check how to handle cases of `null` / empty strings, e.g. in "AIIDADB_PORT" / "AIIDADB_HOST".

**Comment by ltalirz** [comment]
One more suggestion to consider when moving the format:

Currently, the config.json has `user` field
```
user.email
user.first_name
user.institution
user.last_name
```
 which, however, does not refer to the user of a profile but just represents the default values to be used for `verdi setup/quicksetup`
We may want to call this field `suggestions` (or similar) instead; it may eventually be used to specify default values that have nothing to do with the user.

**Comment by ltalirz** [comment]
> We discussed that we would look into this after the tutorial, together with moving the config.json to a config.yaml.

As #4712 introduces a more complete interface to interacting with the configuration file (including the caching configuration), the choice of the format for the configuration file (json vs yaml) becomes less of an issue as users should not need to edit the file by hand.

@chrisjsewell decided to stick with json, partly because of the well-established validation functionality via JSON schemas.

I think this is a valid choice, and as such this issue can indeed be closed when #4712 is merged.
