### ISSUE TITLE
decide whether or not to provide wheels for aiida-core

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#2746]
We are currently providing a [python wheel for python2 but not for python3](https://pypi.org/project/aiida-core/1.0.0b2/#files).

As mentioned in https://github.com/DropD/reentry/issues/43, wheels actually prohibit automatic registration of entry points in reentry's cache, so we should decide whether we want to provide a wheel at all or not.

If we do want to provide a wheel, we should make sure to provide one for both python2 and python3.

**Comment by ltalirz** [comment]
mentioning @sphuber 

> We are currently providing a [python wheel for python2 but not for python3](https://pypi.org/project/aiida-core/1.0.0b2/#files).
> 
> As mentioned in [DropD/reentry#43](https://github.com/DropD/reentry/issues/43), wheels actually prohibit automatic registration of entry points in reentry's cache, so we should decide whether we want to provide a wheel at all or not.
> 
> If we do want to provide a wheel, we should make sure to provide one for both python2 and python3.

**Comment by ltalirz** [comment]
mentioning @sphuber and @giovannipizzi for discussion

**Comment by giovannipizzi** [comment]
Is the fact we have wheels only for py2 because we create the files in py2? would creating them in py3 fix the issue? 
Or maybe we should just change the instructions to run the following?
```
python setup.py sdist bdist_wheel --universal
```
This works for me in [seekpath](https://pypi.org/project/seekpath/#files).

For what concerns reentry not being rerun - does pip 19.0 change the situation? Maybe making pip 19 work changes this?

**Comment by ltalirz** [comment]
> Is the fact we have wheels only for py2 because we create the files in py2?

Yes.

> wouldd creating them in py3 fix the issue?

Creating them in both would.

> Or maybe we should just change the instructions to run the following?
> python setup.py sdist bdist_wheel --universal

That is even better - it's the recommended thing to do for python 2/3 compatible code.

> For what concerns reentry not being rerun - does pip 19.0 change the situation?

I believe not - wheels do not use setup.py period.
Just to be sure, I just downloaded the [wheel of aiida-core 0.12.3](https://pypi.org/project/aiida-core/0.12.3/#files) (this fetches reentry 1.2.2) and pip installed it
 * with pip 19.03: reentry map empty
 * with pip 9.0: reentry map empty

> Maybe making pip 19 work changes this?

Perhaps you missed #2741 - reentry now works with pip 19.

**Comment by ltalirz** [comment]
Back to the original question:
Since we can't really prevent plugin developers from providing wheels, I think the docs anyhow need to recommend doing `reentry scan`.

Given this, I would say it's fine to provide a universal wheel also for aiida-core.

**Comment by giovannipizzi** [comment]
hi, indeed I missed #2741, great!

Re wheels: I think we should do universal wheels, and accept this will not trigger re-entry scan. 

Also because according to these (long) discussion, having post install scripts in wheels is not possible by design and they don't want to support it:

https://github.com/pypa/packaging-problems/issues/64 (twisted seems to have the same issue as as, it would be good to see if they found a different workaround) 

https://discuss.python.org/t/pep-517-and-projects-that-cant-install-via-wheels/791

btw, is re-entry scan thread/multiprocess safe? I guess not because it's writing to files? If it is, we could find a few places where we could silently run it: of course not at every import as this defeats its purpose for speed when loading, but eg if we run it in all verdi run, shell and in the daemon, we probably cover 99% of the cases, i.e. we run it just before when a new plugin might be used. (maybe we need also to run it before specific commands, like what used or be verid calculation plugins).

However we should be careful to avoid unexpected behavior, like goinf through a path that does not trigger it and being confused as the plugin is not there, or running hundreds of parallel vedi run and getting the index of plugins wrong? 


Also, maybe it would be better to have a `verdi plugin rescan` calling `reentry scan`, as this is easier to remember, and suggest this in the docs?

**Comment by sphuber** [comment]
> Also, maybe it would be better to have a `verdi plugin rescan` calling `reentry scan`, as this is easier to remember, and suggest this in the docs?

I think this makes a lot of sense and especially giving `verdi plugin list` a info message pointing to that command saying that if something appears to be missing to run `verdi plugin scan`.

**Comment by ltalirz** [comment]
> Also because according to these (long) discussion, having post install scripts in wheels is not possible by design and they don't want to support it

Yes. We might want to keep an eye on the issue, though, and whether anything develops in [this](https://github.com/pypa/packaging-problems/issues/64#issuecomment-470088753) direction.
We could even add a post to the thread to explain our use case.

> it would be good to see if they found a different workaround

The [setup.py](https://github.com/twisted/twisted/blob/trunk/src/twisted/python/_setup.py) doesn't look to me like they have one...

> we could find a few places where we could silently run it: of course not at every import as this defeats its purpose for speed when loading, but eg if we run it in all verdi run, shell and in the daemon, we probably cover 99% of the cases

I'm not sure this is a good idea. In essence this is what we were supposed to have before and we always found cases where it did not happen.
I think it's better to tell people to do a `reentry scan` after installing a new plugin, also to alert them to the fact that this is how they can fix problems if the cache is deleted for some reason.

> maybe it would be better to have a verdi plugin rescan calling reentry scan, as this is easier to remember, and suggest this in the docs?

So, `verdi plugin scan` would do a `reentry scan -r aiida`?
I guess the downside is that we're introducing a new command and may cause a bit of confusion about the difference between `reentry scan` and `verdi plugin scan`.
I can see the logical upside of having it under `verdi plugin`, though.
Fine with me.

**Comment by ltalirz** [comment]
> On top of that, maybe we could also invoke verdi plugin scan ourselves after a verdi (quick)setup

Again, not so sure about introducing such side effects. It can lead to confusion (e.g. "I installed my plugin, did `verdi plugin list` and did not see my calculations listed. Later, for some reason, it started to be listed - don't know why").

**Comment by ltalirz** [comment]
I think the results of this discussion are:
 1. we should provide wheels for aiida-core (anyhow can't prevent plugin developers from providing wheels)
 1. as long as we are using `reentry`, we need to tell people to run the command to update cache
 1. calling `verdi plugin scan` might be easier to remember than calling `reentry scan`

I'll close this issue now - @giovannipizzi if you think we should add the `verdi plugin scan` to replace `reentry scan`, feel free to open another issue for this.

**Comment by giovannipizzi** [comment]
If we keep `reentry`, indeed a `very plugin scan` would be useful. Let's see first the decision in #3458
