### ISSUE TITLE
profiling the daemon

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#2859]
In aiida-core 0.12 we noticed that running a few 100 calculations of a particular workflow led to very high CPU usage, almost exclusively spent inside Postgres.

Could you please suggest a way to profile what is going on, i.e. to figure out which queries are causing this and where in the python code they are originating from?

Mentioning @sphuber and @giovannipizzi  for comment
@danieleongari and @kjappelbaum for notice

**Comment by sphuber** [comment]
Are these `WorkChains` launching `JobCalculations` that you are running? In that case, I would look at the way the workchains check for their sub processes to be finished. Since the engine in `0.12` is not event based, it uses polling and I have the suspicion that maybe the polling is happening too often.

**Comment by giovannipizzi** [comment]
You can also check the queries running in Postgres with the SQL query shown here:
http://chrismiles.info/systemsadmin/databases/articles/viewing-current-postgresql-queries/

**Comment by kjappelbaum** [comment]
I started looking a bit into what is happening in my case and will continue to do so in the next days. Here some preliminary notes about the profiling i ran on my DB:

* it is not an I/O issue (iowait is not high)  
* what at least in my case seems to be an issue is that a lot of temporary files are created. I just turned on the logging to see where they are created, but it suggests that one maybe could tune `working_mem`, at least for frequent queries
* some Commit queries seem to take suspiciously long (8 min) 
* didn't investigate it systematically so far but `SELECT sum(xact_commit+xact_rollback) FROM pg_stat_database;` suggests a transaction rate of 40 / s
* what I also noticed is that ` tval_idx_for_daemon`  needs vacuum in my case
![image (3)](https://user-images.githubusercontent.com/32935233/57557319-e747f300-7379-11e9-882d-d4f368d75f59.png)
* in the logs i found several `duplicate key value violates unique constraint "db_dbcalcstate_dbnode_id_45de92d4e5e6b644_uniq"` errors. But Leo mentioned that this might be something that is already fixed in 1.0

**Comment by sphuber** [comment]
The last one is *certainly* fixed in `1.0.0` since the `DbCalcState` does not exist anymore :wink: but this concerns `0.12.0 no? Because all of this is extremely diffferent in `1.0.0`

**Comment by ltalirz** [comment]
> but this concerns 0.12.0 no?

0.12.3, yes, and we should fix in 0.12.4 what we can. Still I'm not sure all of this is already fixed in 1.0, let's see.

**Comment by kjappelbaum** [comment]
Finally could restart my database. For me the frequent (every 50 s) temporary files which will slow down everything are due to celery queries in the message table
```
019-05-12 12:46:30.355 CEST [12836] aiida_qs_kevin@masterthesis_kevin LOG:  temporary file: path "base/pgsql_tmp/pgsql_tmp12836.0", size 85598208
2019-05-12 12:46:30.355 CEST [12836] aiida_qs_kevin@masterthesis_kevin STATEMENT:  EXPLAIN ANALYZE SELECT kombu_message.timestamp AS kombu_message_timestamp, kombu_message.id AS kombu_message_id, kombu_message.visible AS kombu_message_visible, kombu_message.payload AS kombu_message_payload, kombu_message.version AS kombu_message_version, kombu_message.queue_id AS kombu_message_queue_id
     FROM kombu_message
     WHERE kombu_message.queue_id = 1 AND kombu_message.visible != false ORDER BY kombu_message.timestamp, kombu_message.id
     LIMIT 1 FOR UPDATE
```

```EXPLAIN ANALYZE``on this shows that that is really creating temporary files:
```Sort Method: external merge  Disk: 83592kB```  the message table has 1833673 counts in my case ( [related to issue ##1253](https://github.com/aiidateam/aiida_core/issues/1253)

One workaround might be something like using a query like to set the `work_mem` high enough to avoid sorting with temporary files on the disk: 

```sql
SET work_mem = '256MB';
SELECT kombu_message.timestamp AS kombu_message_timestamp, kombu_message.id AS kombu_message_id, kombu_message.visible AS kombu_message_visible, kombu_message.payload AS kombu_message_payload, kombu_message.version AS kombu_message_version, kombu_message.queue_id AS kombu_message_queue_id
FROM kombu_message
WHERE kombu_message.queue_id = 1 AND kombu_message.visible != false ORDER BY kombu_message.timestamp, kombu_message.id
LIMIT 1 FOR UPDATE
RESET work_mem;
```

But still, I am not sure if it is good to hard code it to a high value. Options could be to 
1) Hard code it to a high value
2) Give users a switch to change the `work_mem` settings if they do not want their memory utilization to grow 
3) Reduce the size of the table to avoid that. I.e. just delete old messages with `DELETE FROM kombu_message WHERE timestamp < (NOW() - INTERVAL '1 DAYS');`

**Comment by giovannipizzi** [comment]
I agree the best is
1. make sure all calculations and workflows are completed
2. stop the daemon 
3. delete old kombu messages from the table
4. restart the daemon

This will not be a problem anymore in 1.0.

Moreover, also the content of the DbCalcState can be flushed and emptied completely **if all calculations have completed** since that table is used mainly to avoid that two workers try to change the state of a calculation at the same time (so do *not* do it if you still have running calculations).

**Comment by ltalirz** [comment]
@giovannipizzi I feel this deserves a fix rather than just a workaround in 0.12, since this severely impacts the ability to run high-throughput calculations.
How could this be done?

**Comment by giovannipizzi** [comment]
For the DbCalcState or for kombu? For the latter, it's not under our responsibility, it's used by celery. Maybe a message in the `verdi calculation list` if there more than XXX entries, with instructions?
With DbCalcState instead, one could think to have a (periodic?) clean up for all calculations that reached a "final" state (e.g. FINISHED or *FAILED), maybe say 1 day after this state is reached.

**Comment by kjappelbaum** [comment]
Another 'fix' for intermediate sized databases could be to increase globally `work_mem` (or at least recommend doing it). It is less work than deleting the tables (especially for people who haven't used SQL queries before) and increasing it to 200 Mb or so doesn't hurt on modern machines in most cases ... .

For kombu, I can also open an issue in celery.

**Comment by kjappelbaum** [comment]
Short progress report. On both mine and Daniele's machine we increased `work_mem` and saw a improvement (the CPU utilization is at times still high due to the polling, but at least we can do some work in parallel to running something in high-throughput on the same machine).

**Comment by danieleongari** [comment]
This definitively worked for me: previously I was experiencing full cpu load even when a few tens of calculations were still running (the ones that took longer, after submitting hundreds) but now, increasing the `work_mem`, the cpu load is acceptable considering the number of running calculations.

**Comment by ltalirz** [comment]
First of all, thanks a lot @kjappelbaum for looking into this and providing a fix for the `work_mem`.
I'll take care of adding this to the documentation.

Concerning the issue with the growing message table: Without knowing essentially anything about celery and kombu, my basic understanding is that calling `message.ack()` [should remove the message from the queue](http://docs.celeryproject.org/projects/kombu/en/stable/reference/kombu.message.html)

If the message table keeps growing, then this might be an indication that we are "leaking messages" (?)

@kjappelbaum Could you have a brief look inside the message table and post a few example of old messages lying around that should have been removed?



http://docs.celeryproject.org/projects/kombu/en/stable/reference/kombu.message.html

@sphuber So, can we https://kombu.readthedocs.io/en/latest/reference/kombu.html#queue

**Comment by ltalirz** [comment]
Anyhow, looking through the codebase I realize that this indeed refers only to 0.12 since `celery` has been replaced by `circus`. So perhaps the suggested fix with increasing `work_mem` is enough for the time being.

**Comment by sphuber** [comment]
The `kombu_tables` have been completely dropped yes, so this is not an issue for `v1.0.0`

**Comment by kjappelbaum** [comment]
I could not profile in more detail because I am again running something with the same database, but following observations: 
- temporary files are written when the `execmanager` tries to update calculation status
- message bodies from the table look like (somehow I code not correctly decode the base64 ...) `}q(UexpiresqNUutcqUargsq]qUchordqNU	callbacksqNUerrbacksqNUtasksetq	NUidq
U$a7586c80-2ea1-4ef5-834c-3f9237b52791qUretriesqKUtaskq
Utasks.tick_workqU	timelimitqNNUetaqNUkwargsq}qu.`

**Comment by ltalirz** [comment]
Ok, so it is still creating temporary files, even after you've increased the `work_mem` and purged the message table? 
Has the message table already grown to gigantic size again?

@sphuber Do you recognize these messages?
Can this be a hint to where we might be missing a `message.ack()` that leads to the leak?

**Comment by sphuber** [comment]
It has been a long time since I worked with the daemon of `0.12` so I'm not sure. But I do see `task_work` which probably is the ticker for the workflows. It is hooked up [here](https://github.com/aiidateam/aiida_core/blob/5592f81d2c6ec825b043abe107bafee152962236/aiida/daemon/tasks.py#L105). Try commenting that out and restart the daemon and see if you still see those messages. Just launch some job calculations to have some load. You can't do workchains though.

**Comment by kjappelbaum** [comment]
No, there is no longer an issue with temporary files in with increased `work_mem` . The only curious thing is that celery has an automatic cleanup `celery.backend_cleanup` if the beat is running. (https://celery.readthedocs.io/en/latest/userguide/configuration.html). I will check if for some reason this does not happen.

**Comment by sphuber** [comment]
Since we are no longer supporting `0.12.*` I am closing this
