### ISSUE TITLE
Setting attributes for unstored Dict nodes fails silently

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida-core#2883]
I'm confused by a behaviour of the `Dict` class. I want to update an unstored node `d = Dict()`, so I do the following:

`d.x = 1`
`d.dict.x = 1`

Neither of these commands raises an error, but the dictionary is still empty if I do `print(d.get_dict())`. I would expect them to either work or raise an error.

For context, the following gives an explicit error instead (which I'm also not sure why):

```d['x'] = 1   # TypeError: 'Dict' object does not support item assignment```

While the following actually works:

```d.update_dict({'x':1})```

**Comment by sphuber** [comment]
The reason you cannot set dictionary content through attributes is that there would be a potential clash in properties that are generic to the `Node` class. Example, let's say you want to set the key `label` to `test`. You can do it with `node.update_dict({'label': 'test'})`. Through the attribute setter, however, this would become `node.label = 'test'`. Now the problem is apparent. Does `label` need to be interpreted as an internal key of the `Dict` node, or the `label` property of the base `Node` class. Ultimately, setting and getting dictionary keys through attributes is not possible, because of this. The question is if we can rewrite the code to warn the user. Except I don't think we can, for the very same reason, we have to simply document this.

This is also the very reason for the existence of the `dict` property. It stands to reason that this should then also allow to set attributes, as long as the mutability rules are respected. The implementation of `__setattr__` you propose looks fine, because it calls `set_attribute` which contains all the mutability checks.

With respect to `__setitem__`. I don't see a reason why we shouldn't allow this. If we have it go properly through `set_attribute` also here mutability rules will be respected. In addition, `__getitem__` can be made a little more efficient by using `get_attribute` directly. This prevents loading the entire dictionary from the database and will give a small efficiency increase.

**Comment by ramirezfranciscof** [comment]
Just a self reminder for my own understanding: `get_attribute` refers to the backend database concept of attribute (which for a `dict` node it is just its dict content), not the python concept of the attribute of an object (setting "property-like" attributes in nodes such as the first of the examples here will only keep it in memory, it doesn't get stored in the database).
