### ISSUE TITLE
CodDbImporter throws warning about pybtex when importing CIF file

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida-core#2903]
Example:
```python
from aiida.tools.dbimporters.plugins.cod import CodDbImporter
importer = CodDbImporter()
structure_Al = importer.query(id='9008460')[0].get_aiida_structure()
```
Outputs:
```
/home/aiidatests/venvs/aiida_py3.6/lib/python3.6/site-packages/pymatgen/io/cif.py:44: UserWarning: Please install optional dependency pybtex if youwant to extract references from CIF files.
  warnings.warn("Please install optional dependency pybtex if you"
```

**Comment by ltalirz** [comment]
@giovannipizzi @CasperWA 
Are we going to "fix" this?
Should we simply fix this by installing pybtex as a dependency for the tutorial?

**Comment by ltalirz** [comment]
Perhaps this warning could be moved to a place that is only is called when someone explicitly requests extraction of references?

**Comment by giovannipizzi** [comment]
> Perhaps this warning could be moved to a place that is only is called when someone explicitly requests extraction of references?

I think so, but we should write to the pymatgen people for this.
For the tutorial/quantum mobile indeed we can add the dependency (even if we should check if this requires also to install LaTeX, and then I would say no if we don't have LaTeX already, since the dependency can be quite heavy). But I would say not for AiiDA in general - and yes, the best strategy is to avoid that this is printed by pymatgen if not needed.

**Comment by sphuber** [comment]
I have opened an [issue on pymatgen](https://github.com/materialsproject/pymatgen/issues/1507) to ask them to move the warning to a place where it is only emitted if the required functionality is requested, which we don't. There is not much we can or should do here

**Comment by ltalirz** [comment]
well, for the time being we could simply filter this warning in AiiDA

**Comment by sphuber** [comment]
They just addressed the issue. If we do add the filter, we should make sure to remove that code once we can depend on the newer version that fixes this (I don't think they do releases for py2 anymore, so that will be after we drop py2 as well). These kinds of "fixes" tend to stick around and clutter the source a lot
