### ISSUE TITLE
Rename `name` column of `Computer` to `label`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#2926]
This to be consistent with its function compared to all other ORM models, such as `Node` and `Group`

**Comment by CasperWA** [comment]
Note for import/export:
This will (obviously) change the import/export, since "name" of a `Computer` is (and was) exported.

**Comment by sphuber** [comment]
@ltalirz @giovannipizzi given that this would break user facing API, we also don't change this for `v1.0.0`? If so, just like with not merging `User.first_name` and `User.last_name`, what milestone *would* we plan this for?

**Comment by ltalirz** [comment]
strictly speaking 2.0

**Comment by giovannipizzi** [comment]
Note that however we are already changing the API e.g. for Users, where we are dropping a number of columns. So I still believe that in this case a discussion is in order... If we do the change, since we are already in the beta phase, we could already put in 'label' along with 'name', but keep both working with a deprecation warning and drop it in 1.1. If we agree, we just need to evaluate how much work this requires and if we manage to do it before 1.0 (it's possible that we don't...). If we want to try to discuss this before 1.0, I'd suggest to open another issue pointing to this (and to the first_name/last_name one?) and put it in the 1.0 project, that says clearly that we do it only if we have enough time (and we first need to solve the rest).

**Comment by sphuber** [comment]
@giovannipizzi what makes this even more problematic, is that applying these changes also need to change the export archive version. During the PRs we merged yesterday I *did* update the export schema, to make export/import work, but (as @CasperWA correctly pointed out) I did not up the archive version. Since it is in develop, people now can theoretically export archives which will have `v0.4` but with different content than those archives with the same version but created before the changes of the referenced PRs. 

I am about the create a PR to up the version. But again at that point, as soon as we introduce another change in the schema, we are strictly forced to up the archive version as well.

This being said, if we want to discuss whether these proposed changes should be done for v1.0, we should do it now rather than later. Otherwise we should maybe just decide to push it to `v2.0`.
