### ISSUE TITLE
Add support to write `CalcJob` input files that are not stored in the repository

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#2956]
This use case comes from the `aiida-vasp` plugin. The VASP code expects a single file named `POTCAR` with the contents of the required pseudo potentials concatenated for the various elements. The `VaspCalculation` plugin now simply creates this file in the `folder` sandbox, whose contents the engine will then copy to the working directory. However, these contents are also stored in the repository of the `CalcJobNode`. This leads to the content of the `PotcarData` nodes, which contain the pseudo potentials per element, to be copied over and over again. This is exactly why the `local_copy_list` mechanism was introduced, but since the target file is not a simple copy, but a concatenation of multiple input files, this cannot be used. The situation is made worse, because the content of the `PotcarData` nodes are proprietary and cannot be shared. The plugin already provides a mechanism to separate the actual content of the pseudo from the node representation, but all of this work is negated if their content is copied wholesale in the repository of the calculation job nodes that use them.

This is then the real problem here: neither the `local_copy_list` nor the `folder` can be used to have these files transferred to the working directory.

I see two potential solutions:
1. A richer syntax for `local_copy_list` to also instruct simple operations in addition to a literal copy of single files: e.g. concatenating of multiple files to a single
2. A second sandbox folder for files that need to be copied but *should not* be copied to the repository of the `CalcJobNode`.
3. A syntax of marking certain files or paths (with glob) in the `folder` that should not be stored.

Both of these further complicate the already rather complex `CalcJob.prepare_for_submission` interface, but it might be necessary.

**Edit:** added a third option proposed by @giovannipizzi

**Comment by espenfl** [comment]
Yes, this functionality would be highly welcome. In addition, we for instance write the `parameters`, `kpoints` and `structure` to respective input files as well. We would not need those as they are anyway defined as `inputs`. However, we still cannot use the present `local_copy_list` on those as these files are created from the `inputs`. To me it seems an additional directory would be cleaner and easier to explain to the user, than appending something to a list. The `local_copy_list` is still nice if one is for instance set to copy something from a folder, which is not defined as one of the standard ones as I think one defines paths explicitly.

**Comment by espenfl** [comment]
I certainly think we need a solution to this. This also gives problems on export, as the `POTCAR` file is exported in the `raw_input`, which is the content of `folder` as far as I know. This issue is thus linked to #3294 as well, which also needs some kind of solution. Do we have other options than the two above? To me, maybe option two makes most sense as then we would not have to open for extra functionality of `local_copy_list` etc. Thoughts?

**Comment by PhilippRue** [comment]
In the aiida-kkr plugin we have a similar situation where based on the inputs a concatenation of input files is done for a certain calculation. Thus, a general solution would be appreciated.

**Comment by espenfl** [comment]
During discussion we concluded that we will keep it as simple as possible for now. Based on this, we would like to suggest:

- Not to add a new directory (to not tighten the connection to folder filesystems).
- Flag files that we do not want to store in the repository by specifying a list of files (initial suggestion of function name `provance_exclude_list`) that attaches to the `CalcJobInfo`

When actually implementing this we should walk, instead of copy/move everything and then delete files (in case delete operation fails). We could possibly use a reflink copy to keep the speed of move, but we have to investigate if this functionality exists in Python. There is the `reflink` library.
