### ISSUE TITLE
Inefficient order of checks in `verdi import`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#2979]
`verdi import` currently *first* extracts the node data before checking the metadata. When trying to import a big archive with an old version, one first has to wait for the data to be extracted before getting the message that the version is incompatible. Only then does it go automatically to `verdi export migrate`, but there the same problem happens. Version compatibility happens *after* all the data is extracted. The `Archive` class provides useful context managers to read just a single file. This should be used in both these commands to first read the `metadata.json` and report any errors if it is incompatible before doing anything else.

**Comment by ltalirz** [comment]
Other issues/feature requests:
 * `verdi export inspect` has a way of looking inside the metadata and we should simply be reusing this for `verdi export migrate` (I just checked and it doesn't seem to be terribly fast either; perhaps the same mistake is made there)

 * For archives that already are at the latest version, `verdi export migrate` currently fails with:
```
$ verdi export migrate aiida_tutorial_2020_07_perovskites_v0.9.aiida out.aiida
Critical: Your export file is already at the version 0.9
```
   This is not the behavior you want e.g. when you try migrating files automatically - this should be considered a `Success`

 * I would like to see an `-i/--in-place` flag to migrate the archive in place

Since we're about to migrate a number of archives for Materials Cloud, I will have a brief look into this.

**Comment by ltalirz** [comment]
The issue seems to be here:

https://github.com/aiidateam/aiida-core/blob/9d918e0e410e09606294f16bff2018e8a02360e5/aiida/tools/importexport/common/archive.py#L213-L222

The `@ensure_unpacked` decorator extracts *the whole archive* although we would just like to read a single file.

> The Archive class provides useful context managers to read just a single file. 
@sphuber Could you please point me to this context manager?

**Comment by sphuber** [comment]
That phrase might be a bit misleading. It does allow you to retrieve the contents of a single file, but it still requires unpacking the whole thing. Currently, AiiDA archives can be either `.zip` or `.tar.gz` archives, and I am not sure if it is possible to even extract just a single file out of those. I think for `.zip` files it is, but not sure for tarballs.

**Comment by ltalirz** [comment]
> I am not sure if it is possible to even extract just a single file out of those.

It certainly is possible, both for .zip and for .tar.gz files.

Python syntax:
```python
tarfile.open('tarfile.tar').extract('file/to/extract', path='dest')
```
for zipfile see https://stackoverflow.com/a/17729939/1069467

So it seems that we should generalize the extraction code a bit to allow extracting single files and then let this functionality bubble up here...

**Comment by ltalirz** [comment]
Just to mention that
 * https://github.com/aiidateam/aiida-core/issues/4322 was opened for the error when trying to migrate up-to-date archives
 * https://github.com/aiidateam/aiida-core/issues/4233 was opened for the `--in-place` flag

I.e. we can keep discussions on this thread to speed issues in inspecting/loading archive files.

**Comment by ltalirz** [comment]
Thanks to #4510, the archive reader is now just reading (and caching) the files that are needed.

In particular, the version check will just read the metadata
https://github.com/aiidateam/aiida-core/blob/2f8e8454974f9b82d4d734e5e995bd51053e06da/aiida/tools/importexport/archive/readers.py#L123-L147

At the moment `verdi export inspect` defaults to a statistics overview that requires loading the `data.json` as well.
This is certainly useful but I propose to change the default to a mode that only requires reading the `metadata.json` (e.g. printing just the export version and the AiiDA version that was used to generate it.
