### ISSUE TITLE
per process_type caching configuration is not avalaible for CalcJobNode

### ISSUE THREAD

**Issue by zhubonan** [aiidateam/aiida-core#2990]
At the moment the default behaviour of caching for each node classes can be tuned in `cache_config.yml`. 

In 1.0.0 various types of `CalcJob` processes all store the same type of nodes `CalcJobNodes` in the database. The default caching configuration for `CalcJobNode` can be turned on or off but not for individual types of processes. 

I think this can be fixed by including the `process_type` of `CalcJobNode` when retrieving default the configurations.

**Comment by sphuber** [comment]
Instead of making the switch in the configuration file on the `process_type` the `CalcJobNode` will have, we should just update the configuration parser to accept `CalcJob` sub classes. The fact that it still switches on the node class is because the old calculation jobs used to be implemented as a sub class of a calculation instead of a process.

**Comment by zhubonan** [comment]
Yes, this would be ideal as it keeps the old behaviour. 
In fact, I initially tried to turn on the cache for my calculations (sub-class of `CalcJob`) this way but it did not work - it turned out to be the `CalcJobNode` class that needs to be enabled for caching of calculations to work.

**Comment by sphuber** [comment]
Exactly, but that is only because at the time that the caching was implemented calculation jobs were implemented as a sub class of a `Node`. When we address this issue however, we should simply adapt the logic of the caching mechanism. The user should simply define the calculation job class to cache and the implementation in `aiida-core` should then simply make sure that this is mapped to the correct nodes. The user should not have to think about this
