### ISSUE TITLE
pymatgen dependency

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida-core#3085]
Deprecation fixes for e.g. the `collections` was added in `pymatgen`: https://github.com/materialsproject/pymatgen/commit/da1982c903b19ab67dc89c25a7339f4d85aaf546

This is in since version `v2019.3.13`. I notice that the version that is locked in `aiida_core` is rather old. These fixes are useful when running `pytest` in particular. Can we consider to bump up the dependency? In fact, I believe at some point we should distance `aiida_core` from `pymatgen` in order to avoid these dependency issues in the future, but I am not sure what kind of internal routines that depend on this now.

**Comment by espenfl** [comment]
https://github.com/materialsproject/pymatgen/issues/1511

**Comment by shyuep** [comment]
I generally won't comment on other code bases, but I think "distancing" aiida core from pymatgen is a bad idea. It violates the general principle of not reinventing the wheel. You might as well ask that pymatgen and aiida distance themselves from numpy (which has much more deprecation issues), in which case you have to reimplement all of numpy functionality - arrays, matrices linear algebra in general... 

Of course, if you don't find pymatgen useful, by all means dump pymatgen as a dependency. What I would ask you not to do is to replicate some functionality and lock it in. I guarantee it will cause more problems than merely dealing with a few deprecation messages here and there.

**Comment by sphuber** [comment]
When running `pytest` you can ignore warnings with the `--disble-warnings` flag. That should fix it for you. Regarding the version of `pymatgen`, I think python 2 was deprecated since the `2019.01` version so we cannot use that. We could think of having a separate requirement for python 3 until we drop python2 support early 2020. But this will only solve "the problem" for py3.

Finally, I agree with shyuep, where possible we should not reinvent the wheel. `aiida-core` is a generic provenance and workflow engine and should not be implementing material science specific routines. Currently we use `pymatgen` mostly for the `StructureData` and `CifData` classes. These should and probably will eventually be moved to a separate plugin and with it their `pymatgen` dependency. But I think it will always remain useful for them to leverage `pymatgen` for this things it does well.

**Comment by espenfl** [comment]
Thanks for commenting on this. And I totally agree with you about reusage in general. I personally find pymatgen useful along with ASE and other Python packages. That is also why it is in AiiDA as a part of the atomic tools. I am not a core developer of AiiDA. Also, the word distancing was maybe not strictly what I meant. It was not meant in the context of creating borders and increasing maintenance, but more about continuous code review where the balance of flexibility, usability, portability and lightweightness are weighted.

**Comment by espenfl** [comment]
Yes, sure, please close it.
