### ISSUE TITLE
The hash of a CalcJob changes after storing

### ISSUE THREAD

**Issue by zhubonan** [aiidateam/aiida-core#3125]
on `1.0.0b4`, it seems that the hash of a `CalcJobNode` given by `get_hash()` is not the same as that stored in `extras` used for matching new nodes. I wonder if this is expected. The caching still works for new calculations nonetheless. Does this mean that the hash is changed after the node is stored?

This does mean if I rehash the database the matching will be broken. I am not sure what the cause is. The attributes of the `CalcJobNode` use for hashing, in my case, are:
```
import_sys_environment
output_filename
custom_scheduler_commands
input_filename
prepend_text
append_text
resources
seedname
use_kpoints
mpirun_extra_params
scheduler_stderr
parser_name
withmpi
environment_variables
scheduler_stdout
symlink_usage
parent_folder_name
```

Some of these are defined in the subclass of `CalcJob`. Another possible reason would be the repository which is used for computing the hash as well.
I also tried to find the code that stores the `CalcJobNode` and skip head if find matches but has not succeeded yet. 
BTW: I am using the django backend

**Comment by zhubonan** [comment]
I think I have located the problem. 

The repository of the `CalcJobNode` which is updated in the `pre_submit` method **after** the node is store and the initial hash is calculated. Hence, the content of the inputs files should be ignored. This is done by passing the `ignored_folder_content`. 
https://github.com/aiidateam/aiida_core/blob/406dbb4bfe597ac8c1d94553969ecf4427ba26bf/aiida/orm/nodes/process/calculation/calcjob.py#L107-L109
Now the inputs files are direct stored instead of in the `raw_input` folder. As a results these files are not ignored as they should be.
The reference to `raw_input` should also be removd in #3111.

**Comment by ltalirz** [comment]
@zhubonan Thanks for pointing this out!

> The fix would be to make the hashing ignore all contents in the repository for CalcJobNode.

@giovannipizzi @sphuber Do you agree with this?
Are there never any files in the repository of a CalcJobNode that should be considered part of the provenance?

**Comment by giovannipizzi** [comment]
I don't know - maybe it would be better, instead, to say that a ProcessNode gets a hash only when it's sealed and not on store?

**Comment by zhubonan** [comment]
This also make sense but will make the behaviour different between `Data` and `ProcessNode`. The former has the hash stored as soon as itself is stored.

This still requires the input files to be excluded from computing the hash, since a new, identical  `CalcJobNode` does not have the files there when it is stored (these files are generated by the runner of the process) but a hash is needed for matching.

**Comment by sphuber** [comment]
> I don't know - maybe it would be better, instead, to say that a ProcessNode gets a hash only when it's sealed and not on store?

This won't work I am afraid, because the hash of the unstored node, which will be used to see if the process should be taken from the cache or actually run, will be different, because at that point it does not have the files yet. The only possibility is to exclude indeed the files that are generated by the `presubmit` call. I don't think this is even such a bad idea, because in principle, if the calculation plugin is correctly designed, all the inputs it needs will be defined in the inputs and those are included in the hash. The content written in the repository are just a different representation of that same information. Of course the plugin could leak information into the calculation, but that breaks provenance in general, not just the caching mechanism. I think simply excluding the repository entirely for process nodes is the right thing to do.

**Comment by giovannipizzi** [comment]
Good point.
At the moment, it's ok to exclude the whole repository since it's anyway only generated data from the plugin inputs. 
I would still probably discuss if it makes sense to have a limitation (if it's not there yet) on caching only finished calculations? Or instead it's better to accept that if I ask for a calculation that is still running, it's still ok to reference it? 

If during caching we are duplicating inputs and outputs, probably caching an unfinished calculation is not a good idea. If we just want to get back the UUID of the calculation, it's ok to return also unsealed ones.

Maybe we should have a low-level logic that allows to get the UUID also of unsealed calcs, and have a second level that makes a copy of the cached calculation only if it's finished?

**Comment by sphuber** [comment]
> I would still probably discuss if it makes sense to have a limitation (if it's not there yet) on caching only finished calculations?

This is already enforced. The `ProcessNode` class overrides the `is_valid_cache` method and returns only true when it is finished ok, i.e. `process_state=Finished` and `exit_status=0`. The fact that it should be finished is absolutely required. Since the whole point of caching is to clone the outputs with out regenerating them, what is the point if there are not going to be any outputs yet? The fact that "failed" calculations cannot be cached is maybe a bit too strong. I can think of use cases where these may want to be cached anyway, let's say you do two calculations in a work chain where the first is expected to always fail.
