### ISSUE TITLE
REST API: add attribute filters for node endpoint default response

### ISSUE THREAD

**Issue by waychal** [aiidateam/aiida-core#3171]
Currently we have below endpoints:

- default endpoint (e.g. nodes) which returns all attributes: https://materialscloud.org/2dstructures/api/v2/calculations
- to get the attributes for specific node: https://materialscloud.org/2dstructures/api/v2/nodes/c873ee98/content/attributes 
- to add filter on attributes using alist and nalist for specific node: https://materialscloud.org/2dstructures/api/v2/nodes/c873ee98/content/attributes?alist=function_name 

In REST API, add attribute filter for default endpoint to request none, all or specific attributes for all nodes.

**Comment by asle85** [comment]
Fixed in PR #3429.

By default, attributes are not returned in /nodes endpoint. To get the list of all attributes specify attributes=true and to get selected attribute(s) list, use attributes=true and the attributes_filters filter.
The desired attributes have to be provided as a comma-separated list of values.
The attributes_filter filter is used in both /contents/attributes (instead of alist) and /nodes endpoints.

The same happens for extras.
