### ISSUE TITLE
Unable to `submit` work chain, while `run` works perfectly fine.

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-core#3189]
I have a work chain that is located in `/project/apps/surfaces/bulks/celloptwork.py` file.

The `/project` folder is in `$PYTHONPATH` and the `CellOptWorkChain` can be loaded in `verdi shell` or in Jupyter without any problems:
```
In [1]: from apps.surfaces.bulks.celloptwork import CellOptWorkChain

In [2]:
```

I can submit this work chain using `run` method, but when I use `submit` instead - the corresponding process gets stuck. 

The aiida logs show the following, which looks strange to me.
```
$ tail ~/.aiida/daemon/log/aiida-default.log

07/18/2019 02:50:37 PM <11845> kiwipy.rmq.tasks: [ERROR] The task excepted
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kiwipy/rmq/tasks.py", line 126, in _on_task
    result = yield result
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
ValueError: module 'apps.surfaces.bulks.celloptwork' from identifier 'apps.surfaces.bulks.celloptwork:CellOptWorkChain' could not be loaded
```

somehow AiiDA is not able to import the module.

@sphuber any ideas why?

**Comment by sphuber** [comment]
Did you restart the daemon after adding it to the path?

**Comment by yakutovicha** [comment]
Yes, just tried again just to be sure. Nothing has changed
For the info, I am using aiida-1.0.0b5

**Comment by sphuber** [comment]
Did you define the `PYTHONPATH` in an interactive terminal, or have you added it to the `.bashrc`?

**Comment by yakutovicha** [comment]
Added to `.bashrc`

**Comment by sphuber** [comment]
Does the `run` method work and can you import it if your current working directory is not in the `/project` path or any of its sub folders? i.e. go to `/home` or something and try to run it from there or open `verdi shell` and try to import it. Does that work?

**Comment by yakutovicha** [comment]
Just tried to import it in the `verdi shell` being at the `/home` folder. It worked.

```
In [1]: from apps.surfaces.bulks.celloptwork import CellOptWorkChain

In [2]: pwd
Out[2]: u'/home'
```

**Comment by yakutovicha** [comment]
Btw, is all in `dev-aiidalab`. Should I maybe give you the credentials and you try to have a look?

**Comment by sphuber** [comment]
I think I know the problem. Take the line from your bashrc where you add the path to the PYTHONPATH and add it to the activation script of your python virtualenv. Most likely `~/.virtualenvs/aiida/bin/activate` or something like that. Then restart the daemon and try again

**Comment by yakutovicha** [comment]
In aiidalab I don't use a virtual environment. I am already running inside a Docker container.

**Comment by sphuber** [comment]
I think I have figured out the problem here. We experienced similar problems with the virtual machine image @ltalirz used for the Xiamen tutorial. This also included AiiDA lab. Eventually tracked it down to the fact that the daemon workers themselves were excepting on launch. The Circus daemon would of course revive it straight away which would immediately die. Looking at `verdi daemon status` it _seemed_ like a daemon worker was always running, but in fact it was always a different process. You can look at the process id to see this. The problem is that the daemon runner itself was hitting an exception, which never made it to any logs. I opened #3333 for this.

The reason for the exception in this case is the `futures` dependency that was causing an import error. This dependency was added by `aiida-lab`. Removing this from the list and the installation solves the problem. Please give this a go and if confirmed we can close this issue.

**Comment by yakutovicha** [comment]
Thanks, @sphuber. Everything works now.
