### ISSUE TITLE
`load_profile` is not enough to load the profile

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#3201]
At least for Django backends. I think it's a bug.

Snippet to reproduce (make sure to have a default Django backend, or specify a Django profile with as a parameter to `load_profile`):
```python
from aiida import load_profile
load_profile()
from aiida.manage.backup.backup_django import Backup
```
This fails with 
```
ImproperlyConfigured: Requested setting DEFAULT_INDEX_TABLESPACE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```
while it works from the `verdi shell`.

I think the old `load_dbenv`, when called, was enough to make sure everything was loaded. Is this not anymore the case with `load_profile`? What does `verdi` does in addition to actually load fully the profile?

By the way, this seems to work instead:
```python
from aiida import load_profile
load_profile()
from aiida.manage.manager import get_manager
manager = get_manager()
manager.get_backend()
from aiida.manage.backup.backup_django import Backup
``` 
but I'm not sure if this the right thing to do (I have the feeling that the `get_backend()` should be put inside `load_profile`).

**Comment by sphuber** [comment]
The problem is that the concept of the "profile" and "backend" are now properly separated. That is to say, when the profile is loaded, does not mean that the backend itself is also loaded. This is necessary to make the backend load lazily and to be able to "unload" it and switch to another one. The backend is loaded automatically whenever any component that requires it is constructed. The problem here is that the `Backup` class is not properly going through this layer. Like other ORM components it should not be imported from a backend specific path, but the manager should be asked for an instance.
