### ISSUE TITLE
Process unreachable after stopping script 

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-core#3268]
The following happened while running the script `simple_sync_workflow.py` of section 6.3 of the latest [aiida tutorial](https://aiida-tutorials.readthedocs.io/en/latest/pages/2019_MARVEL_Psik_MaX/sections/workflows.html) in the virtual machine. I wanted to cancel the script mid-execution with ctrl+c but it only the terminal hang, and after restarting the machine the processes appeared as running but I wasn't able to `verdi process kill` them, getting the following error: `Error: Process<2648> is unreachable`. The way this was solved was by deleting the nodes, but not sure this is the intended behavior.

**Comment by sphuber** [comment]
If you `run` a process and then kill the interpreter, the actual process no longer exists. What you see in `verdi process list` is just the node that is used by the process to write its state to the database. Since the actual process task no longer exists commands like `kill` or `pause` can also no longer reach it, that is why you see the error. All of this is explained in more detail in [the documentation](https://aiida-core.readthedocs.io/en/latest/working/processes.html#manipulating-processes).

As an aside: interrupting the interpreter should have "killed" the processes. I have fixed a bug related to this in the recent months and maybe it was not included in the version of AiiDA core that you were running. I know that this still does not work for nested processes however, where only the parent gets properly marked as killed, but not the children. This is already described in #2711 so I am marking this as a duplicate and closing it. If you think the situation or cause was different feel free to reopen it and provide more info
