### ISSUE TITLE
Plugins not showing up in shell or with verdi command

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida-core#3298]
Noticed this when I was working on documentation and wanted to verify a few commands in `verdi shell`. First:

```
In [1]: vasp_calc = CalculationFactory(vasp.vasp)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-a324e9134eb1> in <module>()
----> 1 vasp_calc = CalculationFactory(vasp.vasp)

NameError: name 'vasp' is not defined

In [2]: 
```

Then:

```
(aiida) [efl@efl examples]$ pip list | grep aiida
aiida-core                    1.0.0b5              /home/efl/env/aiida/aiida_core
aiida-vasp                    0.2.4                /home/efl/env/aiida/aiida-vasp
(aiida) [efl@efl examples]$ 
```

And:

```
(aiida) [efl@efl examples]$ verdi plugin list
Info: Available entry point groups:
* aiida.calculations
* aiida.cmdline.data
* aiida.data
* aiida.node
* aiida.parsers
* aiida.schedulers
* aiida.tools.dbexporters
* aiida.tools.dbimporters
* aiida.transports
* aiida.workflows

Info: Pass one of the groups as an additional argument to show the registered plugins
(aiida) [efl@efl examples]$
```

But then notice:

```
(aiida) [efl@efl examples]$ verdi plugin list aiida.data
Registered entry points for aiida.data:
* array
* array.bands
* array.kpoints
* array.projection
* array.trajectory
* array.xy
* base
* bool
* cif
* code
* dict
* float
* folder
* int
* list
* numeric
* orbital
* remote
* singlefile
* str
* structure
* upf
* vasp.archive
* vasp.chargedensity
* vasp.potcar
* vasp.potcar_file
* vasp.wavefun

Info: Pass the entry point as an argument to display detailed information
(aiida) [efl@efl examples]$ 
```
Launching workchains etc. works fine.

**Comment by CasperWA** [comment]
Hi Espen. It seems to me that `vasp.vasp` is under `aiida.parsers` for this `aiida-vasp` version. However, you should have `vasp.paw` under `aiida.data`, which I cannot see.
Please try to run `reentry scan` and see if this fixes it.

**Comment by CasperWA** [comment]
Furthermore, you are trying to import using `CalculationFactory`, which will import from the `aiida.calculations` entry point. Also, the input parameter of `CalculationFactory` should be a string, i.e. `CalculationFactory('vasp.vasp')`.
I tried to do this, and it found the right entry point, however, it couldn't load properly due to an incorrect import of `DataFactory` in `aiida_vasp/calcs/vasp.py`. The correct import of factories are from `aiida.plugins`.

**Comment by espenfl** [comment]
Nope, already tried that, but forgot so mention that. Running `CalculationFactory(vasp.vasp)` works fine for our workchains in the same environment, so not quite sure what this is. The `vasp.vasp` under `aiida.parsers` is the VASP parser, so that should be there. You are probably looking at the `master`, `migration_beta` is the one.

**Comment by CasperWA** [comment]
> Nope, already tried that, but forgot to mention that. Running `CalculationFactory(vasp.vasp)` works fine for our workchains in the same environment, so not quite sure what this is. The `vasp.vasp` under `aiida.parsers` is the VASP parser, so that should be there. You are probably looking at the `master`, `migration_beta` is the one.

Yeah, when trying it out, I found that I was a bit too quick here :)
But check out my other comment.

**Comment by CasperWA** [comment]
It may be worth to mention I installed it all from GitHub, using the latest `develop` commits of `aiida-core` (which is now at `v1.0.0b6`).

**Comment by espenfl** [comment]
Okey, sorry for the noise. Started too early this morning with the `verdi shell` and did not look at the command again. Silly me forgot the string :)

However, why does not the plugin show up with `verdi plugin list`?

**Comment by CasperWA** [comment]
> Okey, sorry for the noise. Started too early this morning with the `verdi shell` and did not look at the command again. Silly me forgot the quotes :)

No worries :) Glad we figured it out - in the end.
 
> However, why does `verdi plugin list` not list the plugin?

Yeah, It may seem counter-intuitive, I agree. What it does show, however, is all the entry points where plugins may ... well... plug in. So supplying `verdi plugin list` with a specific entry point will show you all the plugins it knows under the specific plugin.
As it is now, AiiDA does not introduce new base entry points for plugins, since this would not make so much sense, I think. However, it may be helpful to add some sort of split in the printing, clearly stating what is entry points (that may be supplied to the command) and what is "packages" that have been installed for AiiDA, e.g., `aiida-vasp`.
Would this make more sense to you?

**Comment by CasperWA** [comment]
Just to understand, and perhaps optimize this part of the `verdi` usability:
How would you go about making it more intuitive?
Changing the output of `verdi plugin list` to a new command called `verdi plugin entry_list`? Or perhaps `verdi plugin entries`?
Or just printing it all, side by side, for `verdi plugin list`?

**Comment by espenfl** [comment]
Yes, I noticed now that it is listed under `aiida.calculations` and `aiida.workflows`. That is totally fine and I think we should not try to expand the list. Most important I think it is for the plugin developers to know how to approach this command, e.g. when debugging with a user if something does not work. I am closing this issue. Thanks @CasperWA for the swift response and sorry for the unnecessary noise regarding the `verdi shell` commands.
