### ISSUE TITLE
Documenting delete_node and export_node functionalities

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-core#3309]
Following the discussion of issue #1762 (related to issues #3262 and #3296 ) the documentation for both functionalities should probably be in the same place and the proposed location for now would be as a sub-section of the `concepts` section.

**Comment by ramirezfranciscof** [comment]
@CasperWA If you didn't start to do this, I could start and include it in my future PR for node deletion (not sure if anybody else could be also doing something related to this).

**Comment by CasperWA** [comment]
Please go ahead. You may find it useful to use the table I have created as a function documentation in PR #3262 (see [here](https://github.com/aiidateam/aiida-core/pull/3262/files#diff-a5f56ad49cfc4b8674309659a013bb3cR351)), since it uses the correct format for our rst documentation and is otherwise a copy of the table in #3295.

Concerning incorporating it in another PR, I would suggest to do separate PR's in order to avoid issues piling up in single PR. I mean, if one issue is easily solved in a PR, then trying to fix more issues in said PR, the original issue will not be fixed in the code until all issues have been collectively fixed, which can lead to blocking PRs, etc. (Note that I am somewhat a sinner in this respect myself).
However, if you have already started writing the documentation in the same branch, don't worry, simply make a single PR for it.
