### ISSUE TITLE
readthedocs build broken

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3371]
see https://github.com/aiidateam/aiida-core/pull/3314#issuecomment-537269013

**Comment by giovannipizzi** [comment]
@ltalirz FYI we're testing something out about this with @sphuber

**Comment by ltalirz** [comment]
Ok, let me know in case you get stuck.

My guess is it has to do with the autodoc part in the apidocs - we could even decide to somehow disable this.
Still, it would be better to find a workaround in the `conf.py` - after all we want other people to use this as well.

**Comment by sphuber** [comment]
Yes, that is the problem. Because using the sphinxext will require loading the ORM which requires loading the profile and backend, which was especially circumvented for RTD because it needs a database which we dont have. However, I am pretty sure I can get this working now without an actual database. I just have to load a dummy config and circumvent the schema check. I am trying to fix this now

**Comment by ltalirz** [comment]
Notifying @espenfl : I believe this the issue that you encountered as well.

In order to get it to work for aiida-vasp, you'll need to make a slight modification of the `conf.py` and use the latest develop branch of aiida-core on RTD (or wait for the 1.0 release).
