### ISSUE TITLE
Date times should be formatted according to ISO 8601

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-core#3399]
Using the dry-run feature, AiiDA creates a test-folder with format `submit_test/[date]-0000[x]`, where the `[date]` field is formatted as `yyyymmdd`. I suggest that this (and all other) date times in AiiDA are formatted according to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) as the [most universally accepted standard](https://xkcd.com/1179/) of formatting date times.

If agreed, we could use this issue to collect other instances where the date time format could be standardized.

**Comment by ltalirz** [comment]
transferred to aiida-core and gave you the necessary rights - use with care!

**Comment by giovannipizzi** [comment]
Is this still valid? I think from the wikipedia page that YYYYMMDD is a valid ISO date, no? Anyway, the naming of the folder is just for convenience, and to avoid overlaps of folders while making it easy to find new folders if you have many you didn't delete (but eventually those should always be deleted, I would consider these as "temp" folders).

I'm ok renaming to `YYYY-MM-DD-seq_number`, even if then the sequential number appended (needed to avoid writing in the same folder for two dry-runs at roughly the same time) might be misinterpreted. This should be a very easy fix. Otherwise I suggest to close this?

If instead there are other dates that we need to fix, happy to check them (but often, in human output (like verdi) we want to give back something easier to interpret, like "XXX ago").

**Comment by csadorf** [comment]
> Is this still valid? I think from the wikipedia page that YYYYMMDD is a valid ISO date, no? 

Yes, I think it is.

When I originally created the issue I intended this to be a bit broader effort to ensure that date formatting is consistent across the whole code base, but fine to close.
