### ISSUE TITLE
acces absolute path of a FolderData / use of outputs.retrieved

### ISSUE THREAD

**Issue by bosonie** [aiidateam/aiida-core#3416]
I was exploring the outputs.retrieved of a calculation. I remember that once there was a function get_abs_path or similar to access the location of the retrieved files in .aiida/repository/. This doesn't seem the case anymore. What should I do if, for instance, I want to physically access the aiida.out file of a calculation and I don't want to go to the remote_path? To be completely honest, the entire outputs.retrieved looks not very useful as it is. It has no attributes and it doesn't provide easy access to the retrieved files.

**Comment by sphuber** [comment]
We removed that function on purpose, because in the near future the repository might not necessarily be on the local filesystem, but for example on an Object Store. An absolute path does not make sense in that case. All node classes, so also the `FolderData` which is the type of the `retrieved` output, have an API to get the contents of their repository however:
Listing objects:
* `list_objects`
* `list_object_names`

Getting object
* `get_object`
* `get_object_content`

Putting objects:
* `put_object_from_filelike`
* `put_object_from_filepath`
* `put_object_from_tree`

So to take your example, if you want to get the content of the `aiida.out` file from the retrieved node, you can simply do:
```
node.outputs.retrieved.get_object_content('aiida.out')
```
Note that the object key support nesting, so if `aiida.out` would have been in a sub folder called `output` for example, one could have done:
```
node.outputs.retrieved.get_object_content('output/aiida.out')
```

**Comment by bosonie** [comment]
Super clear as usual, thanks a million Sebastian!
