### ISSUE TITLE
`Calcjob` input validation is incompatible with `expose_inputs`

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#3449]
As noted in aiidateam/aiida-quantumespresso#418, 9ebb8cc17e2871e196598ef5ee2d6db820a156d8 has introduced an issue if one wants to expose a subset of inputs for a `Calcjob`, within a `WorkChain.define`, since validation will fail if, for example, the `code` input is not present.

**Comment by sphuber** [comment]
See also #3431

**Comment by greschd** [comment]
IMO this should be resolved (or at least worked around) before 1.0 - it seems to break a significant amount of existing code that worked with ``1.0.0b6``.

Happy to contribute if we have a consensus on how to resolve this.

**Comment by sphuber** [comment]
I went down the rabbit hole last week and did not come up with a solution. The problem is that the validator that is now defined on the top level inputs namespace of `CalcJob` validates three things. The `computer`, `parser_name` and `resources`. Moving them to their respective ports is not possible (only for `parser_name`).
So I see three options:

* Update the validator signature to also receive the `spec` such that it can check if the relevant port is even in the spec.
* Revert the change and move the validation back to `CalcJobNode._validate`
* Suggest that workchains that expose only part of ports do `self.inputs['calcjob'].validator = None`

Option three would be the direction I would like to search the eventual solution, but this will take too much time, because it requires changes in `plumpy`. However, I am preparing the release of `1.0.0` now as we are releasing tomorrow. So that effectively leaves options 2 and 3 or is there an alternative I am missing?

**Comment by chrisjsewell** [comment]
Yeh, as we discussed in aiidateam/aiida-quantumespresso#418, option one would be my preference. But appreciate that it will take some time to achieve

**Comment by greschd** [comment]
I think option one  is where we want to eventually end up - but yeah, this needs some fleshing out. Maybe something to discuss at the coding week.

Would it make sense to perform option three automatically when exposing with include / exclude? Definitely a hack, but might be a sensible one.

**Comment by greschd** [comment]
@sphuber should we put a milestone to this?

**Comment by sphuber** [comment]
yes, we should fix this in `1.1.0` :)
