### ISSUE TITLE
Cannot export inline calculations after migration to 1.0.0

### ISSUE THREAD

**Issue by lekah** [aiidateam/aiida-core#3468]
After migrating an instance from AiiDA 0.10 to 1.0.0b6, I want to export a couple of nodes with their provenance. I get the error: Node(s) with PK(s): ... is/are not sealed.'
I see that the query that looks for unsealed nodes returns only nodes of type CalcFunctionNode, and all these calculations used to be InlineCalculations in v.0.10. I infer that no nodes can be exported after migration to v.1.0.0 if any InlineCalculation is in the provenance of a node, which could be a minor complication in the life of users...

**Comment by lekah** [comment]
For those experiencing the same issue, executing `[inl.seal() for inl, in QueryBuilder().append(CalcFunctionNode).iterall()]` in a verdi shell seals the nodes and removes this error in the next attempt to export.

**Comment by sphuber** [comment]
What version did you migrate your database to? I am a bit puzzled because you say you migrated with `1.0.0b6`, which should get you to version `1.0.40` of the schema (or SqlA) equivalent and that last migration contains a data migration for exactly this. The last statement in that query should find a process nodes that do not yet have the `sealed` attribute _and_ do not have an active `process_state` and seal them. Your legacy `InlineCalculation` nodes should have had their `node_type` migrated to `process.calculation.calcfunction.CalcFunctionNode.` before and should not have a `process_state`, so the migration should have added the sealed attribute. Can you paste the `select * from db_dbnode` results from let's say 10 off your calc functions nodes?

**Comment by lekah** [comment]
I am in code version 1.0.0b6, and schema version 1.0.40. Looking at migration 0.0.40, it is obvious why the sealed attribute is not set. The statement `attributes->>'process_state' NOT IN ('created', 'running', 'waiting');` returns true only if the key 'process_state' exists (and its value is not as specified). The attribute 'process_state' is only set for JobCalculations (migration 0038). Below I am pasting the attributes of one CalcFunctionNode:
`{"source_code": "@optional_inline\ndef niggli_reduce_inline(structure):\n    \n    p = structure.get_pymatgen_structure()\n    pred = p.get_reduced_structure(reduction_algo=u'niggli')\n    return {'reduced_structure':StructureData(pymatgen=pred)}\n", "function_name": "niggli_reduce_inline", "first_line_source_code": 44}`

**Comment by sphuber** [comment]
Good point `attributes->>'process_state' NOT IN ('created', 'running', 'waiting');` is clearly the problem. I will have to add another migration to solve these. Where there any other problems with the migration that you encountered?
