### ISSUE TITLE
Add max_num_cpus_per_machine and max_ram_per_machine_gb to Computers

### ISSUE THREAD

**Issue by zooks97** [aiidateam/aiida-core#3503]
See also #3406 

Currently when configuring a Computer, you set `default_mpiprocs_per_machine` which in practice is used as just that - the default number of MPI processes per machine/node. However, it is implicitly used to specify the number of CPUs/cores that the computer has per machine/node (the assumption is 1 MPI process per CPU/core). For the sake of clarity and flexibility, it could be good to add a property `max_cpus_per_machine` which defines the maximum number of CPUs/cores which should be used per machine/node.

This way, a user could set the parameters to e.g.:
`max_cpus_per_machine = 12`
`default_mpiprocs_per_machine = 6`
so that implicitly, they are specifying:
`default_cpus_per_mpiproc = 2`

Additionally, when working on automatic parallelization, I've found that knowing the maximum amount of RAM available per node/machine is necessary to appropriately parallelize RAM-dependent calculations. So, it would be nice to also have a property of Computers like `max_ram_per_machine_gb`.

**Comment by ltalirz** [comment]
https://github.com/aiidateam/aiida-core/pull/5260/files added a `default-memory-per-machine` property

```
  --default-memory-per-machine INTEGER
                                  The default amount of RAM (kB) that should
                                  be allocated per machine (node), if not
                                  otherwise specified.
```
which [ends up in](https://github.com/aiidateam/aiida-core/pull/5260/files#diff-315d89c8bb66243df6c56dc50087dce39728000b16c2a3d2ae07caddcf8db5b3R748) `job_tmpl.max_memory_kb`

I personally find this description somewhat confusing. It prompts the following questions in me: 
 * What does it mean for AiiDA to "allocate RAM"?
 * What does this number do in practice? Who makes use of it?

My current understanding of its practical utility is somewhat along the lines of
```
The total amount of usable RAM (kB) available per machine (node). Can be used by CalcJob plugins to determine memory parallelization strategy.
```
Perhaps @yakutovicha can comment whether that is accurate

**Comment by yakutovicha** [comment]
> The total amount of usable RAM (kB) available per machine (node).

@ltalirz I think the original description is more accurate. If the `default-memory-per-machine` is set for an aiida computer, it specifies the amount of memory per compute node to-be-used. It may, but doesn't have to be equal to the maximum amount of memory. If a user provides another value (at job submission time, for instance) - this other value will be used instead.

> * What does it mean for AiiDA to "allocate RAM"?

It refers to the amount of RAM that will be requested per node. Maybe requested is a better word then 👍.

> * What does this number do in practice? Who makes use of it?
> Can be used by CalcJob plugins to determine memory parallelization strategy.

Our use case is automated resource estimation. Knowing how much memory a typical job requires, we divide this memory by  `default-memory-per-machine` - this estimates how many nodes are needed (memory-wise). So the second sentence in your description is indeed our use case. I would only remove "by CalcJob plugins" since for us it is always a utility tool which is part of an AiiDAlab app (not plugin/workflow).

Maybe, a better alternative description would be:

```
The default amount of RAM (kB) should be requested per machine (node) - if not otherwise specified. It can be used to determine memory parallelization strategy.

```

**Comment by sphuber** [comment]
As it stands there are two use cases:

1. Define how much memory and cores a node of a particular `Computer` has available
2. Define how much memory and MPI processes should be allocated per node _by default_ when launching a `CalcJob`. (This would essentially provide defaults for the `metadata.options.max_memory_kb` and `metadata.options.resources.num_mpiprocs_per_machine`)

This could be implemented by adding the following attributes to a `Computer`:

* `memory_per_machine`: The available maximum memory per machine
* `cores_per_machine`: The available maximum number of cores (CPUs) per machine
* `default_max_memory_kb`: The default value for the `metadata.options.max_memory_kb` input
* `default_num_mpiprocs_per_machine`: The default value for the `metadata.options.resources.num_mpiprocs_per_machine` input.

There would be some questions regarding naming. Should the `default_` attributes maintain the direct parallel with the associated metadata option, or be named differently in favor of something more intuitive and perhaps closer related to the `memory_per_machine` and `cores_per_machine` attributes.

I am also wondering why the term `machine` was chosen at that time, over for example `node`. @giovannipizzi do you remember why `machine` was chosen? Is that term used in other communities/software/libraries?

**Comment by ltalirz** [comment]
`machine` is a historical artifact here (from `mpiprocs_per_machine`). 
I guess we don't want to change it at this point.

Moving to the memory specifications, do we really need two separate values at the Computer level here?

In my view it is enough to have one option `default_memory_per_machine` at the computer level; I would personally even drop the `default_` prefix and call it `memory_per_machine` - of course people are free to put a different number there than the actual memory available; it will just be the memory AiiDA considers to be available for this computer.
The value can then still be overridden at the CalcJob level. 

Here would be my proposition (which is functionally identical to Sasha's):

`memory_per_machine`: The memory (kB) AiiDA will request per machine, if supported by the scheduler plugin (default: unlimimted). Can be overridden at the CalcJob level via `metadata.options.max_memory_kb`.

**Comment by ltalirz** [comment]
After discussing with @sphuber , for the memory option it's not clear to us whether using `default_memory_per_machine` setting inside `metadata.options.max_memory_kb` is actually necessary.
It appears that the main use case for the memory-related option was just for defining parallelization strategies and piping it through to the CalcJob metadata may be unnecessary (although it probably doesn't do much harm either).

In summary, it appears to me that with the addition of the `default_memory_per_machine` Austin's issue is addressed in practice
- `default_mpiprocs_per_machine` can be used to signify the number of cores
- `default_memory_per_machine` can be used to signify the amount of memory

There is currently no way to say that a machine has X cores and should use Y MPI tasks by default, but does a setting like this really make sense at the computer level? 
It appears to me that parallelization strategies are so code-specific that you want to do those inside workflows rather than hack into the computer metadata.

I.e. from my perspective this issue can be closed.

, in which case it is anyhow the task of the workflow to define

**Comment by sphuber** [comment]
I guess the two existing `Computer` attributes can indeed be used for the use-case outlined in OP, however, they would be awkwardly named, and _if_ the actual default mpiprocs per machine to be allocated by AiiDA should be different from the actual number of cores on the node, this will stop working. I am not sure if there is an actual use case for this currently, but it is certainly envisageable. If there ever would be an AiiDA 3.0, I think this would then definitely be a candidate for a bit of a redesign and have either separate attributes or rename the current ones.

I will close this issue for now then as I don't think we will act on this unless we get a concrete request for a use-case that is currently not possible.
