### ISSUE TITLE
pytest follow-up

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3659]
This is a to-do list of things to complete, following the switch to pytest for testing

 - [x] Update documentation & wiki (`verdi devel tests` => `pytest`)
 - [x] Fix (py)test warnings (will touch lots of files)
 - [ ] Move test files out of aiida-core inside top-level `tests/` folder
 - [x] Decide whether we need to improve test discovery (see [comment](https://github.com/aiidateam/aiida-core/pull/3653#discussion_r357292341))

Then, over time, where it makes sense, we should start moving existing tests from the `AiiDATestCase` to pytest (e.g. where pytest fixtures are making things more effective)

**Comment by greschd** [comment]
I'll have a look at the test discovery part (i.e., fixing the backend variable when an external test profile is used).

**Comment by ltalirz** [comment]
With #3685 merged, only moving the tests out to a separate folder remains.
Since this will likely affect almost any PR and there are still many PRs open, I propose we set a date for this move and let people know.

@sphuber Would you agree? How about some date mid-January?

**Comment by greschd** [comment]
If we're only renaming files, git should be able to automatically merge in most cases (unless the file content is changed so much in the branch it doesn't recognize it as the same file) -- so that _should_ be pretty painless even for existing PRs.

Still probably makes sense to be cautious and announce it in some way.
