### ISSUE TITLE
Make RMQ prefetch count a profile option

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida-core#3677]
At the moment the number of worker slots, as defined by the RMQ prefetch count, is only configurable in the code at `aiida.manage.external.rmq._RMQ_TASK_PREFETCH_COUNT`.  This would be better placed as an advanced configuration option in the profile.

@giovannipizzi , @sphuber , @dev-zero, @greschd  Are we happy with using the name 'slots' such that our two tuning parameters would be num. slots and num. workers?

**Comment by sphuber** [comment]
I have always been very hesitant to make this option configurable because we do not really now how things behave when we make it to large, but if we put a big disclaimer in the documentation maybe it is ok.

Looking at the current configuration options we have in `aiida.manage.configuration.options` we already have `daemon.timeout`. Maybe we could add:

 * `daemon.default_workers`: default number of workers to start when calling `verdi daemon start`
 * `daemon.worker_process_slots`: number of concurrent process slots per daemon worker

I add the `_process_` infix because I am not sure that `worker_slots` is clear enough. If you guys think the shorter should be clear enough, that is also fine.

**Comment by giovannipizzi** [comment]
I think the names Sebastiaan suggests are good.

I also think, instead, that we should make this configurable exactly because we don't know the impact of the parameter.

**Comment by sphuber** [comment]
This is added to `v1.2.1` because implementing this functionality also allows to solve a critical bug.
