### ISSUE TITLE
Resources not set if default in calc spec

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida-core#3740]
Having say `spec.input('metadata.options.resources', valid_type=dict, default={'num_machines': 1, 'num_mpiprocs_per_machine': 1})` in a calculation, calling that from a workchain where `expose_inputs(..., exclude=['metadata'], ...)` is used yields:

```
  File "/home/espenfl/env/aiida/src/aiida-core/aiida/engine/processes/calcjobs/calcjob.py", line 80, in validate_calc_job
    resources['default_mpiprocs_per_machine'] = def_cpus_machine
TypeError: 'NoneType' object does not support item assignment
```

It seems the default is not set at this point. Note however that hiding the required `resources` might not be considered standard practice. Yet, such functionality might have its use.

**Comment by sphuber** [comment]
This is the expected behavior though. When you expose the ports of a class, you are creating a copy of those ports into the target namespace and it only includes those as determined by the exclude/include rules. That is to say that if you exclude the `metadata` port (which includes the `options.resources` port) then the default that was set on the calculation job class is not included so you will have to insert those inputs manually before launching the process.

**Comment by espenfl** [comment]
In this case the `options.resources` is spec'ed on the calc job. Should it not trigger the default settings, regardless of import/export rules? The calc job is called from a workchain, where `metadata` is excluded.

**Comment by greschd** [comment]
I agree that this is not expected behavior. 

Does the validation error happen when launching the _workchain_, or when the calculation is eventually submitted? In case it's the former, this could be a duplicate of https://github.com/aiidateam/aiida-core/issues/3449. The problem was that the workchain would (erroneously) inherit the validation from the calculation, which expects the resources to be there.

**Comment by sphuber** [comment]
Ah now I understand what you mean, apologies. Yes this may just be a problem that was recently fixed by PR #3702. Can you try to checkout the `develop` branch and run `pip install` to make sure you get the newer version of `plumpy` that is required for this fix.

**Comment by espenfl** [comment]
Yes, indeed. With 1.1.0 this is no longer an issue. Closing the issue. Thanks.

**Comment by sphuber** [comment]
Duplicate of #3449
