### ISSUE TITLE
Import / Export without empty directories

### ISSUE THREAD

**Issue by PhilippRue** [aiidateam/aiida-core#3764]
For some nodes AiiDA generates empty directories in the repository.
In my case I removed some of these to reduce the number of inodes I have. The database export and import now poses a problem since it runs into these (false positive) exception:
https://github.com/aiidateam/aiida-core/blob/12f96415e48a43fa43f6b2493101cb5e8b27108a/aiida/tools/importexport/dbexport/__init__.py#L500
and 
https://github.com/aiidateam/aiida-core/blob/12f96415e48a43fa43f6b2493101cb5e8b27108a/aiida/tools/importexport/dbimport/backends/django/__init__.py#L392

It would probably be good to not require empty directories to be included in import/export files.

**Comment by ltalirz** [comment]
@sphuber Let's discuss whether it perhaps makes sense to - until the repo migration - add a "lazy" node folder creation that only creates node folders when something should be put inside.

**Comment by CasperWA** [comment]
I agree - and it should be a fairly easy(TM) fix in the end. I can try and knock it out.

**Comment by ltalirz** [comment]
One comment by @sphuber : Since we are currently not tracking the content of folders, this change would mean that we are no longer able to detect whether the folder was (e.g. accidentally) deleted.

I.e. we should weigh whether the reduction in inodes is worth giving up this consistency check (which is of course quite basic - e.g. missing files are anyhow not detected).

Perhaps @giovannipizzi  can comment

**Comment by ltalirz** [comment]
This will be addressed by https://github.com/aiidateam/AEP/pull/21

**Comment by chrisjsewell** [comment]
Heya, I've marked this a being closed by: #3445.
This is because with this new repository system there will actually no longer be a folder system on disk; files are stored in a compressed format (indexed by hash), with the node's database entry containing a virtual mapping of the actual file/folder structure.

> Let's discuss whether it perhaps makes sense to - until the repo migration - add a "lazy" node folder creation that only creates node folders when something should be put inside.

I very much doubt anyone's going to have time to do this now, it'll just be wasted effort
