### ISSUE TITLE
"!" does not operate as described for verdi  commands

### ISSUE THREAD

**Issue by DanielMarchand** [aiidateam/aiida-core#3770]
`!` is supposed to 'ignore the default and set no value'. Yet this does not seem to be the case. This can be readily tested. E.g. when duplicating a code:

```
$ verdi code duplicate pw-local
Info: enter "?" for help
Info: enter "!" to ignore the default and set no value
Label [pw-local]: FOO
**Description [pw on local ]: !**
Default calculation input plugin [quantumespresso.pw]:
Installed on target computer? [True]:
Computer [daniel]:
Remote absolute path [/home/daniel/Install/q-e_2019.12.10/pw.x]:
Success: Code<1506> FOO@daniel created
```
However,
```
$ verdi code show FOO
--------------------  ----------------------------------------
PK                    1506
UUID                  508d63f9-457b-448f-845b-0d9fcb5a2d14
Label                 FOO
**Description           pw on local**
Default plugin        quantumespresso.pw
Type                  remote
Remote machine        daniel
Remote absolute path  /home/daniel/Install/q-e_2019.12.10/pw.x
Prepend text          No prepend text
Append text           No append text
--------------------  ----------------------------------------
```

**Comment by ltalirz** [comment]
thanks @DanielMarchand for the report; I'll look into fixing this as part of #3894

**Comment by ltalirz** [comment]
So, it turns out you stumbled upon a special case, since `verdi code duplicate` actually did this:

 * create a copy of the original code in memory
 * use the values you provide to update that copy
 * store the copy

Before #3894, there would have been no way to determine inside `code_duplicate` whether an option was simply not provided.
Now, it will actually send the input through the usual validation, which for a string-type argument like `description` should return an empty string.

**Comment by DanielMarchand** [comment]
Great, thanks for taking a look!
