### ISSUE TITLE
Expanding `metadata.options.resources` into explicit ports

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3809]
As we learned during the hackathon, when overriding default values of existing ports in the `spec` of a `CalcJob` or `WorkChain`, it is best practice *not* to redefine the port

```python
spec.input('metadata.options.parser_name', valid_type=six.string_types, default='diff')
```
but better to reuse the existing port like so
```python
spec.inputs['metadata']['options']['parser_name'].default = 'diff'
```
since this reuses e.g. the validators already defined on the port.

However, while trying to migrate the aiida-diff demo plugin to this approach I noticed that there are cases, where AiiDA expects a certain structure in input ports without pre-defining them.

E.g. take the case of the `metadata.options`. The code
```python
spec.inputs['metadata']['options']['resources']['num_machines'].default = 1
```
[raises a `TypeError: 'InputPort' object is not subscriptable`](https://github.com/aiidateam/aiida-plugin-cutter/pull/68/checks?check_run_id=469771309#step:6:101) because the input ports are pre-defined only up to the `resources` level  (see [docs](https://aiida.readthedocs.io/projects/aiida-core/en/latest/working/calculations.html#options)).

This does not seem very intuitive to me, and I am wondering whether we should perhaps extend the pre-defined input ports further down inside the `resources`?

Mentioning @sphuber and @giovannipizzi  for comment

**Comment by sphuber** [comment]
I changed the title because the functionality works, it is just that historically `resources` has been a single dictionary and we never expanded it into individual ports. I think if we can expand them, it would probably be a good idea. Why not. Just have to see what currently _can_ and _should_ be passed and make a list here, so it is then easy to implement

**Comment by sphuber** [comment]
Coming back to this, I don't think this will be trivial. The reason is that the schema of `metadata.options.resources` is determined by the scheduler plugin that will be used, which is only known on runtime. So there is now way that the spec can explicitly define the subports. Therefore I am closing this for now
