### ISSUE TITLE
Click version 7.1 breaks test and verdi-autodocs pre-commit hook

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-core#3838]
The click[ version 7.1](https://pypi.org/project/click/7.1/) (released a few hours ago) breaks test and verdi-autodocs pre-commit hook.

As an immediate measure, I recommend to pin the Click version to 7.0 (#3837 ).

**Comment by sphuber** [comment]
Do you remember what the problem was exactly? I tried to unpin and `verdi-autodocs` ran just fine with the new version of `click`. It just has some other setting regarding to the help string formatting, so it changed some of the generated auto docs.

**Comment by greschd** [comment]
Might be unrelated, but click version `7.1` had broken its error messages (they went to `stdout` instead of `stderr`). The fixed `7.1.1` was released just a few hours after, but not before the issue mentioned above.

If I remember correctly I _did_ try to run the tests again with `7.1.1` and it was still broken, but I didn't test that thoroughly.

**Comment by sphuber** [comment]
The problem is due to [this PR of click](https://github.com/pallets/click/pull/1470). They wrapped the editor command in `shlex_quote`. Since in our unit testing we pass arguments to the editor command to make it non-interactive, this is now interpreted as a single executable by bash which it then fails to find. We might have to find another way to simulate the interactivity of these tests without abusing the `os.environ['EDITOR']` variable.
