### ISSUE TITLE
Allow to pass a folder in `local_copy_list`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#3869]
Currently the `local_copy_list` only supports the copying of individual files from the repository of any data node. However, sometimes one might want to copy over the entire contents of a node's repository, or at least of a sub directory, to the remote working directory. Implementation should be relatively simple: just check whether the second element of any entry in `local_copy_list` corresponds to a directory instead of a file. If it is a directory copy its contents recursively.

**Comment by giovannipizzi** [comment]
Question: is it needed? Instead of generalising the interface, maybe we just provide a helper function to convert a function in a list of its content (e.g. internally using os.walk), in a format ready to be used by local_copy_list?
Also, as a note for the implementation, we need to be careful that this does not depend on the fact that currently the repository is on an actual folder, as this will go away soon.

**Comment by sphuber** [comment]
If you agree this is a useful use-case and it will require us to implement some logic, why make the interface more complicated for the user. Imagine I have some `FolderData` whose entire contents I want to copy over. Consider the interface:
```
single = SingleFileData()
folder = FolderData()
local_copy_list = []
local_copy_list.append((single.uuid, single.filename, 'pseudo.upf'))
local_copy_list.append((folder.uuid, None, './target'))
```
versus
```
from aiida.engine.calcjob import get_folder_local_copy_list
single = SingleFileData()
folder = FolderData()
local_copy_list = []
local_copy_list.append((single.uuid, single.filename, 'pseudo.upf'))
local_copy_list.append(get_folder_local_copy_list(node, None, './target))
```
I think the consistency in syntax for defining the copy of single files as well as (nested) directories is a lot clearer than having to import some utility function from somewhere.
