### ISSUE TITLE
node hash includes computer uuid. why?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3878]
While playing around with mock codes, I ran into a couple of issues related to node hashing:

### the hash of any `Node` currently includes `self.computer.uuid` (if they have an associated computer).
https://github.com/aiidateam/aiida-core/blob/358b9167cfc64ad6bcff0b13837c3295aded0d2c/aiida/orm/nodes/node.py#L1140

I have two questions here:
 1. Hashes are meant to look at the *content* of nodes. UUIDs should never be part of the hash, correct? I guess we need to introduce a hash for computers.
 2. Why was the computer hash introduced to the hash in the first place? I imagine it was introduced for `Code`s (?), where a hash of the computer *should* be part of the hash of the code.
   For CalcJob nodes, however, (which also have a `Node.computer`), this information actually does not need to be included in the hash, since this is already taken care of by the hash of the code in the inputs.
   Can we move the computer hash to the `Node` subclasses for which it is intended?

### the readability of the output provided by `Node._get_objects_to_hash` currently varies a lot:

```
['1.1.1', 
 {'version': {'core': '1.1.1', 'plugin': '1.1.1'}, 
  'withmpi': False, 
  'resources': {'num_machines': 1, 'tot_num_mpiprocs': 1, 'num_mpiprocs_per_machine': 1}, 
  'append_text': '', 
  'parser_name': 'zeopp.network', 
  'prepend_text': '', 
  'scheduler_stderr': '_scheduler-stderr.txt', 
  'scheduler_stdout': '_scheduler-stdout.txt', 
  'mpirun_extra_params': [], 
  'environment_variables': {}, 
  'import_sys_environment': True, 
  'custom_scheduler_commands': ''
 },
'57473b64-d400-4cb3-b99b-4735c0cd5a36', 
 {'code': '4cbbb85106e3352e04b4aaf1a4896e962cd1b17f857728a1ba801f6aabc1d394',
   'parameters': '5cdad2c1da524984832893d7436e695f3326f9d51db679aef4c845227a3b620c', 
   'structure': '364e7867f49e1bf6279b4c94832c965051a1cf8022ff4860df9e158a45165667'
 }
]
```
While some items are nicely documented using dictionaries, others (the version + the computer uuid) are just dumped in "bare", making it difficult to understand where they came from.

Could we agree to move to a practise where all items in this list are wrapped in dictionaries that provide some context?

mentioning @greschd and @sphuber for comment

**Comment by greschd** [comment]
To be honest I don't remember why the `Computer` was hashed by `uuid` instead of content. It might have been a hack that "works most of the time", but it could also be because the `Computer` has some (more than the usual `Node`) mutable attributes. 
It could be ok to hash by content instead, but that needs to be looked into carefully. Also, one should check what happens on export / import.

As for using the Computer uuid in the `Node`, as far as I can tell any `Node` can have a `computer` set - at least `RemoteData` uses it as well.

None of the objects in `_get_objects_to_hash` are actually documented: Some of them are "understandable" simply because they are dictionaries _themselves_. The reason for this is that `_get_objects_to_hash` wasn't really intended to be inspected. We should certainly improve the "explainability" of differences in hashes - we can probably do that without changing the hashes themselves, though.

As a side note: changing hashes is actually a bit problematic, because there is no good way of migrating the hashes to a new format. The main culprit there is the `__version__`, which is taken from the current source. That means an old `Node` will get a hash corresponding to a new version when it gets rehashed. To fix that, we would need to store the version of AiiDA / the plugin that a node was created with in the DB.

**Comment by greschd** [comment]
Should we maybe open a separate issue for the "explainability" topic? I think it's somewhat independent from the computer hashing question.

**Comment by sphuber** [comment]
> To fix that, we would need to store the version of AiiDA / the plugin that a node was created with in the DB.

This is already done since `aiida-core==1.0.0` at least for `ProcessNodes`. At the time we decided not to add this yet for `Data` nodes, if I remember correctly.

**Comment by greschd** [comment]
> This is already done since `aiida-core==1.0.0` at least for `ProcessNodes`. At the time we decided not to add this yet for `Data` nodes, if I remember correctly.

Ok, it would be good to propagate that to be included (instead of the current source `__version__`) in the hash, then.

**Comment by greschd** [comment]
For `Data` nodes it's true that the version is not really important - they're uniquely determined by their content, anyway. Maybe hashing should also not include the version in that case.

**Comment by ltalirz** [comment]
> Should we maybe open a separate issue for the "explainability" topic? I think it's somewhat independent from the computer hashing question.

Sure, you can also tack it on to this one https://github.com/aiidateam/aiida-core/issues/2549

**Comment by greschd** [comment]
Since the core + plugin version are now stored in `attributes` (for `ProcessNode`), I think it makes sense to just remove the `__version__` from the `_get_objects_to_hash`.

For `Data` nodes I think adding the `__version__` is indeed not required, because if the plugin or core changes in any meaningful way, their attributes will also be different.

Tagging also @giovannipizzi for comments - since I originally discussed adding the `__version__` with him.

**Comment by sphuber** [comment]
Just came across this. I wasn't involved in the original selection of objects to add to the hash calculation, but having the `computer` makes sense, since any node can have one defined, for example `RemoteData` as @greschd pointed out. So it is not just `Code`. And even in some cases, the `computer` is not always implicit in the `Code` input. `PortableCodes` don't define a computer but this has to be defined in the `metadata.computer` input on the `CalcJob` itself, since the computer can be selected at run-time. I think it makes sense to keep it then. 

If we want to remove the `__version__` from the list returned by `_get_objects_to_hash`, we could do that, but it would require a migration to reset all existing hashes. I just merged such a migration to `main` (the first migration since v2.0) which is scheduled to be released soon, after a bug was fixed in the hash algorithm for `CalcJobNodes`. If we want to change more in the `_get_objects_to_hash`, now would be the time, because then we only annoy users once with having to recompute the hashes.

Another important note, the version dictionary of core + plugin is implemented by the `ProcessNode`. This means that `Data` nodes do not get it (nor does the `Node` base class, but that is anyway not storable). But as @greschd argued above, they might not really it. Although wouldn't the same 

My conclusions:
* Leave the `computer` in `_get_objects_to_hash` (required by multiple node types)
* Remove top-level `__version__` attribute
* Add the version info dictionary to `Data` nodes?
* Change return type of `_get_objects_to_hash` from `list` to `dict` using keys for each value (Note this wouldn't require a migration necessarily as the `_get_hash` method could simply pass `.values()` to `make_hash` thus not changing the hash.

**Comment by ltalirz** [comment]
That looks good to me

> Add the version info dictionary to Data nodes?

Since this would be a change in caching behavior, and I don't remember hearing any complaints so far, I would suggest to skip this change.

> Change return type of _get_objects_to_hash from list to dict using keys for each value (Note this wouldn't require a migration necessarily as the _get_hash method could simply pass .values() to make_hash thus not changing the hash.

Yes, that sounds like a good solution
