### ISSUE TITLE
Lsf scheduler wrong with `num_machines`

### ISSUE THREAD

**Issue by xjf729** [aiidateam/aiida-core#3887]
aiida-core version: 1.1.1

1. When I set `metadata.options.resources` without `num_machines`, it raises "aiida.common.exceptions.InputValidationError: the `resources` input has to at least include `num_machines`."
2. When I set  `metadata.options.resources` with `num_machines: None`, it raises "aiida.common.exceptions.InputValidationError: the input `resources.num_machines` shoud be an integer."
3. When I set `metadata.options.resources` with `num_machines: 1`, it raises "aiida.common.exceptions.ConfigurationError: num_machines cannot be set for LSF scheduler"

btw, when I use aiida-core v1.0.1 and set `metadata.options.resources` without `num_machines`, aiida can work properly.

**Comment by giovannipizzi** [comment]
Thanks for the report! 
Are you using Quantum ESPRESSO or another plugin?
@sphuber is this maybe related to aiidateam/aiida-quantumespresso#485, or to some other recent change?
Indeed, while for most schedulers that we use, `num_machines` is required, there is a class of schedulers that don't allow to specify the number of machines, but only the total number of MPI processors and a "partition name". For these, we use the [ParEnvJobResource](https://aiida.readthedocs.io/projects/aiida-core/en/latest/scheduler/index.html#parenvjobresource-sge-like)

So we should check if we changed the validation upstream somewhere, and possibly evaluate if we want to revert aiidateam/aiida-quantumespresso#485

**Comment by sphuber** [comment]
This should have nothing to do with `aiida-quantumespresso` but rather probably the fact that we moved validation of `metadata.options.resources` directly on the spec: https://github.com/aiidateam/aiida-core/blob/99742f284556bfea62a3c6df28a0a0b7da4832f0/aiida/engine/processes/calcjobs/calcjob.py#L87

I thought this was required for all calculation jobs. It will be difficult to make this validation scheduler dependent, because for that one would need to get the scheduler type, which can only be retrieved from the `computer` either directly from the `metadata` input or through the `code` input.

Another option would be to simply ignore the `num_machines` in the LSF scheduler, but I don't know how that scheduler works and what adverse effects it could have. Also this then forces people to always add `num_machines` in the options, even though it will be discarded.

However, come to think of it, simply ignoring it might have another benefit. Since the value _is_ required for most other schedulers, and it is forgotten so often, causing the calculation to fail, that is exactly the reason I have made it a default for all `CalcJob` implementations in `aiida-quantumespresso` in the PR you linked. If we choose not to ignore the `num_machines` for LSF schedulers, people will have to remember to explicitly remove the input.

**Comment by xjf729** [comment]
Thanks for your answer @giovannipizzi 
Actually, I'm using CP2K plugin, and it's version is `aiida_cp2k develop branch (1.0.0)`.

**Comment by zhubonan** [comment]
@sphuber I ran into the same error with SGE scheduler - it also does not require `num_machines`. In fact, this field is not picked up by the scheduler plugin at all. So I have to set `'num_machines': 1` for all my calculations for it to proceed.

I do think it is a good idea to validate the resources at the process input level, but perhaps the validation can be made more general? For example, we can just check if the `resources` is empty.

**Comment by giovannipizzi** [comment]
@zhubonan just to be sure, is now `num_machines` just ignored, or instead before it had a default of 1 and could be skipped? In the latter case maybe it's better to be explicit? In the former, I would prefer instead to avoid that parameters are passed but then ignored and maybe a different number of machines are used.

**Comment by zhubonan** [comment]
@giovannipizzi The `num_machines` is now validated by the `CalcJob`, see the following lines.

https://github.com/aiidateam/aiida-core/blob/e8e7e46a02d6777d0c92e6090a8061f1f26e3cf2/aiida/engine/processes/calcjobs/calcjob.py#L81-L92

Previously (1.0.X) it was not validated, which results in excepted `CalcJob` if the scheduler needs it but it is not defined. #3742 added the validation to the `CalcJob` level, but it only makes sense for certain schedulers (Slurm and PBS).

There is no default for `num_machines`, and I have to specify a value to just get past the validation, and this value is ignored downstream. For SGE scheduler there is no way for the user to set the actual number of nodes that will be allocated, only the total amount of processes can be defined. 

I think the solution is to let `validate_resources` less restrictive, for example, just check if the `resources` is defined or not.

**Comment by giovannipizzi** [comment]
Thanks for the clarification!
I think then that we shouldn't have `num_machines` required and then ignored, as this will be misleading when looking at the CalcJob metadata.

**Comment by sphuber** [comment]
I think the best solution is to implement `Scheduler.validate_resources` which the plugins can then implement. This will require also a bit of extra code on the `JobResource` classes itself to provide a validation mechanism. Or we can always just construct them and catch the exception if invalid. This way in the `CalcJob` inputs validator, we can simply call the validator of the `Scheduler` passing the relevant inputs (maybe there is something more than just the resources) and catch any validation errors.

**Comment by giovannipizzi** [comment]
Ok! I think I would put the validation itself into the [JobResource](https://github.com/aiidateam/aiida-core/blob/98e21dac650fc1e7e79cb69eeebfadaf90c21c24/aiida/schedulers/datastructures.py#L45) as you mention.

Then, the correct JobResource class can be obtained from the Scheduler (sub)class using the [`job_resource_class` class method](https://github.com/aiidateam/aiida-core/blob/98e21dac650fc1e7e79cb69eeebfadaf90c21c24/aiida/schedulers/scheduler.py#L98).

(Of course it's then straightforward, if we want to, to add a `Scheduler.validate_resources` wrapper that just calls `cls.job_resource_class.validate(job_resource_data)` or something like this (e.g., better: `cls.job_resource_class(**job_resource_data).validate()` making the validate of the JobResource class a proper method (not a class method).

We can start with something simple, and then improve on the validation later if needed (BTW, this means that we don't have to touch any of the plugins, but we just fix the two JobResource subclasses).

**Comment by sphuber** [comment]
Is there any reason to make the validation indirect through a `validate` instance method call? Since you have to construct the instance first, and it is a simple data structure essentially, why not have the validation done already in the constructor (which already what happens now)?

I could see the benefit of having a validation class method, such that you can validate inputs without being forced to construct an instance. Actually this may be something we want to think about, because with the design you propose now, the resources validation would essentially call the validation of the scheduler, which now will be forced to instantiate the `JobResource` just to validate it, but then will discard the instance. Don't think this will be a problematic performance hit, but maybe it may be nice to think of an API where instantiation is not strictly necessary.

**Comment by giovannipizzi** [comment]
@sphuber I see your point, and I agree. It's ok if the validation is done in the `__init__`, and a `validate` function in the process could just try to instantiate it to check if the provided options are valid.
