### ISSUE TITLE
A "Create AiiDA test profile setup/environment" GitHub Action

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-core#3898]
This would be GREAT for various AiiDA-related repositories that want to use GitHub Actions CI for testing their package.

Personally, I could see myself using this in the OPTIMADE-related AiiDA packages (both server and client). It may be quite useful for minor AiiDA lab app tests as well, and perhaps even some AiiDA plugins?

**What should it do**: Set up an AiiDA profile, preferably including PostgreSQL and RabbitMQ services, but less may be able to do it.

**Why**: Creating Nodes (for testing AiiDA interactions) demands the loading of a profile. Storing a Node demands even more than this, i.e., a PostgreSQL service to back it up.

**Result**: Easy setup of AiiDA test environment for CI testing using GitHub Actions (i.e., should also make the local GitHub Actions CI workflows look sleeker).

**Comment by CasperWA** [comment]
This could be based on the new AiiDA Docker images ...

**Comment by agoscinski** [comment]
I am not sure in which way this would be useful for any user group. There is an aiida [cookie cutter recipe](https://github.com/aiidateam/aiida-plugin-cutter) which people can use for new plugins that includes a GitHub workflow setting up aiida. Having in addition to that a GitHub Action seems like maintenance overhead.

**Comment by CasperWA** [comment]
For me, the user base is mainly platforms or technologies that implement AiiDA as an integral or integrated part of it. For example, 
 a platform, where AiiDA is one of or the main workflow manager/executor or it becomes integrated into a more high-level data interoperability framework. For the AiiDA development team, this refers to various EU-funded projects and similar, where this is the case.
It will indeed be extra overhead and maintenance, and as such should be a minimum implementation that relies on existing work and technologies - like the docker stack (for AiiDAlab). The easiest option here would be a small bash script that will become the entrypoint for a base docker stack image that will end up running `verdi shell` something, something, or similar.

**Comment by sphuber** [comment]
Note that an action may no longer be necessary. We have done a lot of work for the upcoming release to support profiles that use SQLite (instead of PSQL) and require no RMQ (of course daemon related functionality is then not available. The new pytest fixtures provide the `aiida_profile` fixture that is automatically loaded and provides a test profile with SQLite and no broker. This means that plugins only have to install `aiida-core` and then add the following to their `conftest.py`
```python
pytest_plugins = 'aiida.tools.pytest_fixtures'
```
And then they can start storing nodes etc. No services are required to be installed. The upside over an action is that this even works locally, thus making local development a breeze to get started with.

Of course, if the plugin requires daemon functionality and so RMQ is needed, some more work is needed. But GHA provides an easy way to provide this as a Docker service in the runner and the `aiida_profile` fixture can be easily configured to add the broker.

So I would close this for now. If this still poses too much hassle for whatever reason, please feel free to reopen with a concrete problem description.
