### ISSUE TITLE
group error message needs to contain instructions on what to do

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3919]
On the latest `develop` branch, I now get this error message
```
-/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/groups.py:61: UserWarning: no registered entry point for `Group` so its instances will not be storable.
  warnings.warn(message)  # pylint: disable=no-member
/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/groups.py:61: UserWarning: no registered entry point for `AutoGroup` so its instances will not be storable.
  warnings.warn(message)  # pylint: disable=no-member
/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/groups.py:61: UserWarning: no registered entry point for `ImportGroup` so its instances will not be storable.
  warnings.warn(message)  # pylint: disable=no-member
/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/groups.py:61: UserWarning: no registered entry point for `UpfFamily` so its instances will not be storable.
  warnings.warn(message)  # pylint: disable=no-member
```
and if I understand correctly, essentially all AiiDA users will get those when they upgrade.

In order to save us from tons of questions, we really need to put instructions into this warning on how to make it go away again.

**Comment by sphuber** [comment]
The problem here is that you just updated your branch but did not `pip install && reentry scan` it. This is standard procedure and is in the documentation for when you update your AiiDA version. The reason that I did not add this explanation in this warning message, is because this is not the only reason. Here it concerns entry points that ship with `aiida-core` so normally should not be a problem. However, this message is really intended for people who import an archive containing groups from some plugin package that they don't have installed. `aiida-core` cannot know from which package they come from so cannot say how to install them.

**Comment by ltalirz** [comment]
Ok, that's already much better... 

However, I would be willing to bet money that others will forget to `reentry scan` as well.

> However, this message is really intended for people who import an archive containing groups from some plugin package that they don't have installed. aiida-core cannot know from which package they come from so cannot say how to install them.

Right. We could still add something like "if you've recently upgraded aiida-core, you may want to try running `reentry scan`".

Also, maybe I didn't pay enough attention, but was there a message concerning this when doing the migration?
That might be another place to warn about this.

**Comment by chrisjsewell** [comment]
`reentry scan` no longer needed, so I guess we can close this 😄 

Perhaps though we should add the module path `namespace['__module__']` to the warning message?

**Comment by sphuber** [comment]
> `reentry scan` no longer needed, so I guess we can close this smile

Agreed

> Perhaps though we should add the module path `namespace['__module__']` to the warning message?

Don't think it is necessary
