### ISSUE TITLE
Docs step of CI job often failing

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#3928]
Problem seems to be due to intersphinx trying to retrieve the docs of `click` and getting a 502.
Example failure: https://github.com/aiidateam/aiida-core/pull/3921/checks?check_run_id=583767290
```
failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://click.palletsprojects.com/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 502 Server Error: Bad Gateway for url: https://click.palletsprojects.com/objects.inv
```

**Comment by ltalirz** [comment]
Hm yeah, I encountered this as well already
Even opened an issue but then closed it again when I realized it worked again:
https://github.com/pallets/click/issues/1523

One workaround would be to remove the intersphinx mapping for click

**Comment by ltalirz** [comment]
The better way would be for them to fix it, of course. Feel free to reopen the issue

**Comment by sphuber** [comment]
> One workaround would be to remove the intersphinx mapping for click

it isn't just `click` though, also `flask`, although that is also from the same organization, so I think it is rather something all their packages might be suffering from

**Comment by sphuber** [comment]
Just encountered this again, but this time for the `plumpy` docs which are hosted by ReadTheDocs, so I am not sure if this is really the fault of click/flask.

[Example run](https://github.com/aiidateam/aiida-core/pull/3931/checks?check_run_id=585916854)
```
loading intersphinx inventory from https://click.palletsprojects.com/objects.inv...
loading intersphinx inventory from http://flask.pocoo.org/docs/latest/objects.inv...
loading intersphinx inventory from https://flask-restful.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://kiwipy.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://plumpy.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
intersphinx inventory has moved: https://click.palletsprojects.com/objects.inv -> https://click.palletsprojects.com/en/7.x/objects.inv
intersphinx inventory has moved: http://flask.pocoo.org/docs/latest/objects.inv -> https://flask.palletsprojects.com/en/1.1.x/objects.inv

Warning, treated as error:
failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://plumpy.readthedocs.io/en/latest/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 502 Server Error: Bad Gateway for url: https://plumpy.readthedocs.io/en/latest/objects.inv
make: *** [html] Error 2
Makefile:58: recipe for target 'html' failed
```

**Comment by greschd** [comment]
I think this needs to be fixed somehow on our side. Since there are 6 different intersphinx links, we rely on all of them being up for the build to pass. It seems these services are not really engineered for high availability (as they probably shouldn't).

Some possibilities on our side:
- Use build artifacts to keep the intersphinx inventory in between runs. We would need to make sure that it gets updated often enough that we don't hit the cache timeout (http://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_cache_limit) - which would mean we're back to the original issue.
- Simply retry the doc build. Obviously doesn't help much if some service is offline for a significant time.
- Run sphinx without the `-W` (turn warnings into errors) option. This reduces the usefulness of the doc run quite a bit.

**Comment by sphuber** [comment]
I agree that we need to fix this on our side, especially since it now seems clear that it can happen for any docs provider.

Your second option is complicated because the Github actions interface currently does not support restarting a single job. You have to rerun all of the jobs in the workflow even if just the docs failed.

The third is also not an option, unless we can just disable that flag for the intersphinx part

**Comment by ltalirz** [comment]
Indeed, we could use the cache action: https://github.com/actions/cache
I think this is the simplest option

**Comment by greschd** [comment]
With "retry the doc build" I meant in bash, within the same Github action step.. but I agree it's not an ideal solution.

For the cache, I think the difficult bit is keeping the cache up to date. Naively using the cache option will fix the issue until the cache is considered "outdated" by Sphinx, at which point we again rely on the inventories being available. Maybe that reduces the incidence of this problem enough, but it's still not great. 
Ideally, whenever the inventories are available the cache would be updated.

**Comment by ltalirz** [comment]
Let's perhaps take a step back:

 * I think what actually matters here is the aiida-core documentation shown on readthedocs.
 * This build of the docs will fail just as our CI builds, no matter what retrying or caching mechanism we implement on our CI
 * Being able to jump to the documentation of dependencies via a link can save time but at the same time it's not essential.

So, I would propose to remove the intersphinx mapping for the packages hosted on palletsprojects.com until a time where they are available reliably.
Sounds good?

**Comment by sphuber** [comment]
Except that it is not just the mapping of the palletsprojects failing. Like I reported I have also seen it fail for `plumpy` which is hosted on ReadTheDocs...

**Comment by ltalirz** [comment]
Oh... sorry, I had missed that comment. Hm.

Perhaps then I'm also wrong about 2. - I thought the recent build failure on rtd was related to this as well but it seems it was unrelated (not clear to me what caused [it](https://readthedocs.org/projects/aiida-core/builds/10831999/) though).
Since merging the intersphinx mapping ([docs build](https://readthedocs.org/projects/aiida-core/builds/10720618/)), I'm counting over 25 successful documentation builds of `develop` on RTD https://readthedocs.org/projects/aiida-core/builds/?page=1

If the issue is just with the github actions CI workers, then adding a cache could be a workaround (or trying to look into the network issue).

Just a bit strange that this issue only shows up for intersphinx, not pip installs etc.

**Comment by ltalirz** [comment]
P.S. No, it's just that on RTD, we don't fail on warnings - there are actually a couple of them.
And among them also warnings about the intersphinx mapping.

https://readthedocs.org/projects/aiida-core/builds/10840863/

**Comment by sphuber** [comment]
I don't think it is necessarily a generic network issue, as in the runner loosing network connectivity now and again, I think it might be the runners' http requests for the `objects.inv` being rejected somehow. For pallets we consistently get a 502 as exit code, i.e. Bad Gateway. Haven't been able to figure out more info on what could cause this

**Comment by greschd** [comment]
Maybe related to the "this object has moved" we get when the inventory _is_ available?

**Comment by greschd** [comment]
> Just a bit strange that this issue only shows up for intersphinx, not pip installs etc.

Not _that_ surprising when considering that Github might have a PyPI mirror, and PyPI itself is probably more concerned with high availability than a documentation hosting service..

**Comment by sphuber** [comment]
Since it hasn't been happening for a while, I am temporarily closing this, until it crops up again
