### ISSUE TITLE
Exporting sub-sets of groups

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3972]
This is a question about the following use case:

 * you have used a group "my_nodes" to organize your nodes (in practice, there might be multiple ones)
 * you want to export only a subset of the nodes in "my_nodes"
 * but: you would like your export to contain a group "my_nodes" that contains the nodes you've exported (e.g. because you have tools that, given the group, know what to do).

Of course, you could think of modifying the group before the export; then exporting; then undo the modifications - I'm just wondering whether with the new group classes + traversal tools there are now more elegant ways to achieve this 

If yes, I would put this in the (to-do) docs on exporting 

mentioning @sphuber @giovannipizzi

**Comment by giovannipizzi** [comment]
Question: How would you specify on the command line which subset to export?
Isn't it easier to create another group with a different name and export that?
E.g. you could leverage on the group path and append `/export` to the group name or something like this to make it clearer to reuse? (and then you search groups that are either your original name or a 'subpath' of the original name)

**Comment by sphuber** [comment]
Not sure if this would be an acceptable solution, but if the subset nodes is the only thing in the export file, you can use the `-G` option of `verdi import`. If you pass it a group name, `verdi import` will create it if it does not already exist and store the nodes in that group.

**Comment by danieleongari** [comment]
Hi, I think we want to clarify better our user case: 
we don't have only one group, but many of them, one for each material, which contains all the important results that are related to that material. Still we are using this solution because `with_ancestor` search from the initial structure is too slow to query and gives us less flexibility on what to include.

Now, in this user case we would like to export only, let's say, only some of the results in the same group, so that we can run some calculations in another profile (e.g., by another user) and then merge back.
We don't necessarily need a cml command, since it is something that anyway we need to organize with some scripting.

**Comment by sphuber** [comment]
With the current API, I don't see a way to do of what you are asking. Essentially you want to add a `Group` instance to the export file, but not automatically include all the nodes that it contains. Functionality that would allow this would have to be implemented.

**Comment by chrisjsewell** [comment]
Closing this, since I think it's just to niche to implement in the core code. Obviously happy to receive PR proposals if you are still kean on it though
