### ISSUE TITLE
Add automated namespace support to `inputs` and `outputs` node neighbor manager

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#3978]
The `inputs` and `outputs` node neighbor managers support addressing process node inputs or outputs through attribute dereferencing by the link labels, e.g.:
```
node.outputs.some_output
```
Both the inputs and outputs can have arbitrarily nested namespaces, for example:
```
{
    'relax': {
        'structure': StructureData()
    }
}
```
However, since the links are flat, the resulting link label is `relax__structure`, where the namespace is indicated by the double underscore. To retrieve this output one should use `node.outputs.relax__structure`. However, it would be nice if the neighbor manager understands the double underscore and allows it to be retrieved through the syntax `node.outputs.relax.structure`.

**Comment by espenfl** [comment]
@sphuber Any updates to this? I also noticed that for instance when you want in a workchain to do something quickly in a calcfunction it would make sense to be able to parse the node output directly to the input of the calcfunction in a namespace fashion. Now one would have to reconstruct it in a dict (due to the `__` prepend), unless of course you use the keys directly.
