### ISSUE TITLE
Docs: How to extend workflows

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#3993]

**Comment by mbercx** [comment]
Some questions/comments that came to mind while working on this:

- My interpretation of this section is explaining how you can use one work chain/calcjob in another work chain, i.e. by exposing (with possible exclusions) the inputs of the work chain/calcjob on a name space and submitting the work chain/calcjob inside on of the steps of the work chain using the `self.submit()` method. Is there an aspect of "Extending workflows" that I'm missing here?
- Exposing inputs is already explained very well in @sphuber's [section on advanced workflows](https://aiida-tutorials.readthedocs.io/en/tutorial-2020-intro-week/source/sections/workflows_adv.html) from the last tutorial. I would simply reuse this content here, since it also uses basic arithmetic examples.
- I don't think the other content of this advanced workflows tutorial has been integrated in the documentation. I think it would be good to add another section to the "How to run multi-step workflows" section that explains how to use the `BaseRestartWorkChain` based on this content. Not all of this should go into the how-to section on workflows, though. Here's my suggestions for the various subsections:
  * **7.1. Exit Codes**: There is already a [section on exit codes](https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/processes/functions.html?highlight=exit#exit-codes) in the "Topics - Processes" part of the documentation, but I think it would be good to take some of the arithmetic examples @sphuber explains and add them to a `BaseRestartWorkChain` section.
  * **7.2.1. The problem**: This seems like a section that belongs in the "Topics - Workflows" section.
  * **7.2.2. Writing a base restart work chain**: This would go into the "How to run multi-step workflows" section on the `BaseRestartWorkChain`.
  * **7.2.3. Exposing inputs and outputs**: As I already mentioned, I would use this in the "How to extend workflows" section.
  * **7.2.4. Error handling** and **7.2.5. Multiple process handlers**: Both of these can go into the "How to run multi-step workflows" section on the `BaseRestartWorkChain`.

What do you think? If we agree on adding a "How to run multi-step workflows" section on the `BaseRestartWorkChain`, I'll open a separate issue for this.

**Comment by ramirezfranciscof** [comment]
Hi, I just wanted to mention that there is also issue #1927 that I think should be considering when doing this. I thought this was already incorporated and so I was going to do #1927 myself, but now that I see this is still here maybe it makes no sense to do them separately. Is this ok @mbercx ?

**Comment by mbercx** [comment]
> Is this ok @mbercx ?

Yes, for sure! I had already assigned myself to the issue. :)

**Comment by mbercx** [comment]
Opened #4706 re the `BaseRestartWorkChain` section.
