### ISSUE TITLE
Docs: Consider adding the sphinx-copybutton extension

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#4062]
See: https://sphinx-copybutton.readthedocs.io

Very simple, you just add `sphinx_copybutton` to the extension list in `conf.py`

**Comment by csadorf** [comment]
@chrisjsewell In favor, can you create the PR?

**Comment by chrisjsewell** [comment]
Will do

**Comment by mbercx** [comment]
I tried out the `sphinx-copybutton` extension for the tutorial, and was wondering if you can somehow configure for which code blocks the copy button is added. The issue is that some of the code blocks also include the output, so for these I wouldn't add the copy button. I also was only able to configure one prompt with the `copybutton_prompt_text` configuration, which wasn't ideal because the tutorial has both Python and terminal code blocks.

**Comment by chrisjsewell** [comment]
> if you can somehow configure for which code blocks the copy button is added

@mbercx yes you can, see https://sphinx-copybutton.readthedocs.io/en/latest/#configure-the-css-selector-used-to-add-copy-buttons.
In the PR I can try something like:

```python
copybutton_selector = "div.highlight:not(.no-copy) pre"
```

Such that you "should" be able to do

```rst
.. code-block:: python
    :class: no-copy
```

FYI in #4060 I am removing the `accordion` directive I recall you had added to your tutorial, since I've moved the functionality to `dropdown` in https://sphinx-panels.readthedocs.io/en/latest/#dropdown-usage 😄

**Comment by mbercx** [comment]
@chrisjsewell Nice! I saw the section on the selector, but my css knowledge was too limited to put it into practise. 😄 

Good to know about the switch from `accordion` to `dropdown`! I'll try and remember to fix that in the final version of the tutorial.
