### ISSUE TITLE
IOError vs OSError

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#4082]
This in the past has caused confusion, re which one is the right one to check.
Now that we are py3 only, we should only catch OSError, as IOError is just a backward-compatible alias (see a few lines before [this](https://docs.python.org/3/library/exceptions.html#IOError)).

We might want to do some ~prepping~`grep`ping to replace all IOError checks, and also any `except (IOError, OSError)` with simply `except OSError`.

Pinging @ramirezfranciscof @sphuber @greschd for comments

**Comment by greschd** [comment]
Agreed, as per the docs replacing `IOError` with `OSError` should not change behavior.

In some specific cases, it might make sense to replace `OSError` with one of its more specific subclasses (e.g. `FileNotFoundError`). This was not possible previously because these were added in 3.3.

I'd suggest doing the replacement `IOError` -> `OSError` globally, and while doing so check if there are obvious places where a more specific error is more suitable.

**Comment by ramirezfranciscof** [comment]
> We might want to do some prepping

What do you mean "do some prepping"? What is there to prepp before doing the replacement?

**Comment by giovannipizzi** [comment]
It was grepping (as in `grep`) but the automatic spell check changed it (or I mistyped) ;-)
