### ISSUE TITLE
command to print python path of the currently running AiiDA daemon

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#4189]
### Problem

When playing around with e.g. new Calculations or Workchains that aren't yet part of a plugin package, users frequently have difficulties making sure that the corresponding classes can be found by the AiiDA daemon.

### Solution

One way to improve upon the status quo would be a `verdi daemon pythonpath` command (or similar) that simply prints out the `PYTHONPATH` seen by the currently active daemon in a nicely formatted way.
This would allow users to quickly spot whether the folder where they placed their python files is indeed in the `PYTHONPATH` of the daemon (most often, this being *not* the case is the origin of the issue).

### Additional context

As @sphuber mentioned, at the moment it is theoretically possible that different runners of the same daemon see different `PYTHONPATH`s (e.g. if new runners were added at a later time; probably quite rare in practice).
To me, this is problematic in itself and probably worth preventing altogether [1], but for the feature described above, I would simply not care about this implementation detail for the moment and just use whatever daemon runner is available to print the `PYTHONPATH`.

[1] Since jobs are assigned to daemon runners based on availability (effectively at random from a user perspective), it seems one would like to avoid that these runners can process jobs differently because they see different python environments.

**Comment by sphuber** [comment]
> One way to improve upon the status quo would be a `verdi daemon pythonpath` command (or similar) that simply prints out the `PYTHONPATH` seen by the currently active daemon in a nicely formatted way.

We should be a bit careful with the language here to make sure we know what we refer to when we see daemon. The reason is that there is no _one_ daemon process. There is the circus process, which daemonizes the daemon runner processes. Each of these is its own system process and so therefore potentially has its own virtual environment, which as you pointed out is not what we want. This is why we implemented it such that the circus process will forward its virtual environment when it spawns a daemon runner process. This is done here in the `verdi daemon start-circus` hidden command:
https://github.com/aiidateam/aiida-core/blob/41f5d5d0a4ea4bd3b9eb5e450e0a3956bb07baa5/aiida/cmdline/commands/cmd_daemon.py#L290

This `get_env_with_venv_bin` copies the `PATH`, among other things, to ensure all daemon workers have the same environment.
```python
def get_env_with_venv_bin():
    """Create a clone of the current running environment with the AIIDA_PATH variable set directory of the config."""
    from aiida.manage.configuration import get_config

    config = get_config()

    currenv = os.environ.copy()
    currenv['PATH'] = os.path.dirname(sys.executable) + ':' + currenv['PATH']
    currenv['AIIDA_PATH'] = config.dirpath
    currenv['PYTHONUNBUFFERED'] = 'True'

    return currenv
```
I am not a 100% sure that this absolutely guarantees that there is no way to cause differences in the path. I tested adding an `export PYTHONPATH` statement in the activation script of the virtual environment where the daemon was already running and then called `verdi daemon incr` to create another runner. I added a debug statement to the runner on start up to print its `sys.path` and the new path did not show up. I am not sure if this is conclusive proof however.

For example, there are definitely ways to create different environments. If a daemon runner is active and the source code of some python package is updated, the active daemon runner won't see that change. But any new runners _will_ see the new code. This is of course not the same as having a different `sys.path`, but I would consider this as being a "different Python environment" as you described it. I see three potential solutions here:
#. Forbid `verdi daemon incr`, one simply needs to launch straight away with as many workers as you want
#. Pipe `verdi daemon incr` first through `verdi daemon stop` and then call `verdi daemon start` with as many workers as one would have created with the increase
#. Try to detect changes in the Python environment when `verdi daemon incr` is called compared to when the current circus instance was launched with `verdi daemon start

I think the last one is technically super complicated and error prone. The first two are a hit to user-friendliness.The `verdi daemon incr` functioanility is very important so I think we should definitely keep it. Of course we could pipe it automatically through a complete restart of all active workers, but this will cause a performance hit, since all workers have to be restarted, all processes are sent back to RabbitMQ that afterwards have to be loaded and started again by the restarted runners and finally, the work that the daemon runners were currently doing will have to be redone.

All this to say that I think we have to accept this limitation of Python and that hot loading of code is not supported. This is an important concept for AiiDA users, completely independent of the `verdi daemon incr` question, for example when they change code during development or install new entrypoints, and so they will anyway have to be aware of this.


What I would propose then as a solution for your request is to add a logging statement with the `INFO` level on daemon runner startup. When the user enables `verdi config logging.aiida_loglevel` and starts a new daemon runner, the content of its `sys.path` will be logged to the daemon log. Would that work?

**Comment by ltalirz** [comment]
Hi Seb, thanks a lot for the detailed writeup!

Very briefly (I have to run)

About the issue of having different paths for different workers:
I was thinking of your option 2. It could be the default behavior, with a cli option `--no-restart` to prevent this if people have reasons not to?

About the feature request itself: perhaps it could be a cli option of `verdi daemon status` (or a separate command) - I think when you are testing things you would like to ask the daemon what its status is right now (to understand why something doesn't work), and asking people to set a config value (which they need to remember to unset again) and then to restart the daemon is not idea in my view.

**Comment by sphuber** [comment]
> About the feature request itself: perhaps it could be a cli option of `verdi daemon status` (or a separate command) - I think when you are testing things you would like to ask the daemon which `PYTHONPATH` it is seeing _right now_ (to understand why something didn't work), and asking people to set a config value (which they need to remember to unset again) and then to restart the daemon is not ideal in my view.

Fair point, this might just be quite difficult to implement. The reason is that the "daemon", either the circus process or any of the daemon runners, all run in a separate system process. To get them to print the content of their `sys.path` then requires an RPC call of sorts (a remote procedure call). I am not sure if there are any easy solutions here, other than really adding a full blown separate RPC subscriber to each daemon runner that listens to this "print your sys.path" commands over RabbitMQ and does it.

> P.S. Of course, a logging option is already an improvement upon the status quo, so if this is much easier to implement than the alternative, that's also a good step forward.

Compared to the solution you were thinking off, this is tons easier

**Comment by greschd** [comment]
> 
> About the issue of having different paths for different workers:
> I was thinking of your option 2. It could be the default behavior, with a cli option `--no-restart` to prevent this if people have reasons not to?
> 

That might just be left-over paranoia from old issues, but I really dislike the idea of silently restarting the daemon. At the very least, I think there should be a confirmation dialog before restarting.

Note also that `incr` isn't the _only_ way you can have different module states in different daemon workers: For example:
- worker A loads `mymodule`, worker B doesn't
- user updates `mymodule`
- worker B loads `mymodule`
now worker B has the new version, while A doesn't.

**Comment by sphuber** [comment]
Exactly the reason why I am not too enthusiastic about the proposed feature. In addition to the examples @greschd and I gave, there might be many more very subtle ways in which the environment of daemon runners can go out of sync. I think we should just make this very clear to users as it might be near impossible to prevent this. On top of that, providing a tool to give the path of one of the processes, which may even very well be the incorrect answer, is _worse_ than not giving this information at all. At least we should certainly _not_ claim that the result will hold for all daemon workers.

**Comment by ltalirz** [comment]
I'm fine with leaving the issue with the different `PYTHONPATH`s be for the moment - this was not driven by an actual use case (I've never heard of this causing problems in the wild), it was just triggered by @sphuber mentioning that different runners may have different `PYTHONPATH`s, which I feel is problematic.

As for printing the `PYTHONPATH`, I'm also ok with the logging option. It's just a bit less convenient.

P.S. While looking a bit through the code I noticed that you are storing the `VIRTUAL_ENV` here 
https://github.com/aiidateam/aiida-core/blob/cc49ee924bdef3be346f8ad1b6c578ebd48d0beb/aiida/engine/daemon/client.py#L24
which seems to be used nowhere in the entire codebase (?)

**Comment by sphuber** [comment]
> which seems to be used nowhere in the entire codebase (?)

It is. It is exposed through the `virtualenv` property on the `DaemonClient`:
https://github.com/aiidateam/aiida-core/blob/41f5d5d0a4ea4bd3b9eb5e450e0a3956bb07baa5/aiida/engine/daemon/client.py#L109
which is actually called in the `start-circus` command to setup the arbiter:
https://github.com/aiidateam/aiida-core/blob/41f5d5d0a4ea4bd3b9eb5e450e0a3956bb07baa5/aiida/cmdline/commands/cmd_daemon.py#L280

**Comment by ltalirz** [comment]
Sorry, searched for the wrong string ;-)
