### ISSUE TITLE
Create endpoint for statistics that contains process_type

### ISSUE THREAD

**Issue by vgranata** [aiidateam/aiida-core#4247]
To correctly calculate the statistics for Materials Cloud [1], @giovannipizzi suggests to create an endpoint:
/process_statistics or /full_types_statistics 
similar to /full_types [2] and that should also display the counts.

[1] https://www.materialscloud.org/home#statistics
[2] https://dev-aiida-dev.materialscloud.org/autowannier/api/v4/nodes/full_types

**Comment by ramirezfranciscof** [comment]
@sphuber Maybe you can explain to me what this would involve this wednesday and I could try to do this? If you have any resource you want me to read or part of the code to check out to prepare for that, let me know.

**Comment by sphuber** [comment]
Sure. Sometime ago I added the `/nodes/full_types` endpoint to the REST API:
https://github.com/aiidateam/aiida-core/blob/99e608c55bef5a9b8e8ee9e851f2e2d91ae86150/aiida/restapi/api.py#L133

This will return a nested mapping of all the "process types" that are present in a database. Each `Process` has a process type, which is a string identifier, that is stored as the `process_type` attribute on the corresponding process node. I wrote [a utility function](https://github.com/aiidateam/aiida-core/blob/99e608c55bef5a9b8e8ee9e851f2e2d91ae86150/aiida/restapi/common/identifiers.py#L336) that performs a query of all process types in the database and represents the unique set of them in a nested namespace. What @vgranata is asking for is another endpoint that in addition to this mapping also adds information on how many concrete instances there are in the database for each process type.

**Comment by ramirezfranciscof** [comment]
Hi @giovannipizzi and @vgranata :

1 - How exactly were you plannning to use this? We were thinking of using the same routine as for `process_type` but with an optional keyword for getting the counts. I think it would still be better to have a different endpoint so you can access this directly instead of having to pass the keyword. Probably how AiiDA does this internally would not be of your concern but anyways wanted to check if this is compatible with the use case. BTW: just as a test, could you verdi run [this scrip](https://drive.google.com/file/d/1JXFTteHQWMVCN1C52nnyt0xQUyZCPgyG/view?usp=sharing) in an aiida profile with a big DB to check how fast it would perform (I don't have any very big one)?

2 - How would you want to count the nodes that can be both a "stand-alone" type and a group of other types? For example, you can have the following nodes: Data, DataDict (subtype of Data). Would you want to get that there are two "Data" nodes or one?

**Comment by giovannipizzi** [comment]
For 1, I think it does not matter, and we will write the REST API wrapper for the routine. Just make sure to keep the function call backward-compatible with proper defaults. If using a flag makes it easier because you can just put some if switches rather than copy-paste, then it's good. Just make sure not to trigger at all the logic for counting if not required, because counting is potentially expensive.
@Valeria can you try the script of Francisco on some of the DBs to check how long they take? (They should ideally take max ~1sec also on big DBs on Materials Cloud)

For 2: I think we had some logic for this already. We distinguish between the 'bare' note (e.g. a pure 'Data' node, not a subclass) and 'Data' as a container superclass.
So we should get
- Data (container) -> 2
  - Data (bare) -> 1
  - Dict -> 1

You can check the code of the current logic, and inspect how the current endpoint works. Create a new profile (`verdi quicksetup` on your computer or in the Quantum Mobile), then in a `verdi -p quicksetup shell` do
```python
Data().store()
Dict().store()
```
Then run `verdi -p quicksetup restapi`, and finally ` wget http://localhost:5000/api/v4/nodes/full_types` and then inspect the `full_types` file that was downloaded.

In this simple example the `subspaces` part reads:
```json
      "subspaces" : [
         {
            "full_type" : "data.%|",
            "namespace" : "data",
            "subspaces" : [
               {
                  "label" : "Data",
                  "path" : "node.data",
                  "subspaces" : [],
                  "full_type" : "data.Data.|",
                  "namespace" : "data"
               },
               {
                  "path" : "node.data.dict",
                  "label" : "Dict",
                  "full_type" : "data.dict.Dict.|",
                  "namespace" : "dict",
                  "subspaces" : []
               }
            ],
            "path" : "node.data",
            "label" : "Data"
         }
      ]
```
and I think we want to get, when counting, something like (I added the `count` keys):
```json
      "subspaces" : [
         {
            "full_type" : "data.%|",
            "namespace" : "data",
            "count": 2,
            "subspaces" : [
               {
                  "label" : "Data",
                  "path" : "node.data",
                  "subspaces" : [],
                  "full_type" : "data.Data.|",
                  "namespace" : "data",
                  "count": 1
               },
               {
                  "path" : "node.data.dict",
                  "label" : "Dict",
                  "full_type" : "data.dict.Dict.|",
                  "namespace" : "dict",
                  "count": 1
                  "subspaces" : []
               }
            ],
            "path" : "node.data",
            "label" : "Data"
         }
      ]
```
and so on recursively, if needed.

**Comment by ramirezfranciscof** [comment]
Thanks for the reply. I have two follow up questions:

1. I've implemented it as a separate endpoint like you requested, but then we were wondering if maybe you would prefer the option of using the same endpoint but passing an optional argument instead?

2. Is there a problem with changing the old endpoint to also return a `count=None` key/value pair? If not I could remove the pair just before returning it (its easier than introducing it conditionally in the creation of the dict), but I think there might be some value to having both output be consistent.

**Comment by giovannipizzi** [comment]
Hi, 
For 1 I don't have a preference, it's probably ok also to provide it as an option (maybe better to avoid proliferating too many endpoints). But please discuss with @vgranata if this is OK for use in Materials Cloud (@vgranata -> it might be interesting to see if this count can be used when generating the left menu in Explore, we are already using it to generate it, maybe we can show the count as well near the class name, e.g. with a badge, in this way).

I mean this menu:
<img width="266" alt="Screenshot 2020-07-22 at 23 16 21" src="https://user-images.githubusercontent.com/16132028/88229644-6076f180-cc71-11ea-9595-a20a2cd8ada6.png">
that could do something like this for instance for the count:
<img width="438" alt="Screenshot 2020-07-22 at 23 16 03" src="https://user-images.githubusercontent.com/16132028/88229674-6967c300-cc71-11ea-9aac-b71371d272f2.png">

For 2: maybe it's better if you pop `None` out to avoid chaining the format, and reducing the number of bytes transferred; but probably it doesn't really matter. Again, please check with @vgranata (the important thing to check is that Materials Cloud does not break with this change).

Finally, please also make sure that there is documentation for the existing endpoint, and for the new feature you are adding, and before merging check that everything works and is efficient (<1 or 2 seconds also for very big DBs) - once merged we cannot do changes of names, response dictionary schemas, ...
@vgranata can help testing it on the DBs on Explore, but you should also try e.g. on the big DBs of Sebastiaan to see that they are efficient also when you have millions of nodes

**Comment by ramirezfranciscof** [comment]
@vgranata I already have a working solution for this in [this PR](https://github.com/aiidateam/aiida-core/pull/4277), could you please check that it doesn't break the Materials Cloud and that performance-wise it is acceptable?

In the meantime I will prepare the unit tests but it would be of grean help to have confirmation of this.
