### ISSUE TITLE
Nightly test install workflow will run on forks as well

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#4257]
If I read the setup of the test-install workflow correctly, then the cronjob will run on every fork as well:

https://github.com/aiidateam/aiida-core/blob/9636ac773f8e92da6f7a8e882e469576ba9c1ce3/.github/workflows/test-install.yml#L1-L13

I think we will want to put in a guard to restrict this to the main repository as e.g. here
https://github.community/t/do-not-run-cron-workflows-in-forks/17636/3

I suspect this is the reason why I'm getting emails both from the main repo and from @Crivella 's fork whenever these workflows fail.
I suspect the reason this does not happen for other people's forks is because these cron jobs may be limited to the default branch of the fork (`develop`) and most people don't update their `develop` branch (?).
If that is the case, we should act quickly, since every new fork of aiida-core would create a new source of these emails.

I don't know... anyhow, it would be great to get to the bottom of this

@csadorf let me know whether you think this assessment is correct

**Comment by Crivella** [comment]
Regarding my fork, I am keeping it up to date with the upstream repo.

Weirdly, even without me doing anything, the "test-install" seems to sometime work and sometime fail.

If you could point me to some documentation on how to handle this jobs without straight out deleting the workflow files from the repo I'll try to see if i can restrict them.

**Comment by csadorf** [comment]
Yes, it seems like the cron-jobs are by default also executed on forks, which is probably not what we want. See [here](https://github.com/csadorf/aiida-core/actions?query=workflow%3Atest-install) for an example.

I see a few alternative solutions to this problem:

1. We add a guard [like this](https://github.community/t/dont-run-actions-on-pull-request-from-fork/17560/2) to only execute this particular workflow on the "main" repository:
```
    if: github.actor == 'aiidateam'
```
To my understanding the workflow would still be triggered, but we would skip all the jobs, so that we at least don't waste any resources.

2. We use a microservice (like the AiiDA bot) to trigger the action using a repository_dispatch action. That would give us more control about how and when this particular workflow is triggered, but also requires a bit more maintenance effort in maintaining the bot.

3. We do not use GitHub actions for this particular test, but maybe CircleCI that we can enable more selectively?

No matter what solution we choose, we would probably want to check all forked repositories and recommend to maintainers to merge `origin/develop` where the cron job is inadvertently run by creating an issue.

@ltalirz Before I state my preference, thoughts?

**Comment by csadorf** [comment]
@ltalirz @sphuber I think we should resolve this issue rather quickly. Do you have an opinion on the best solution here? Otherwise I'll probably proceed with option 1 in combination with option 2.

**Comment by ltalirz** [comment]
1 is a fix already, 2 sounds even better. Not quite sure what "option 1 in combination with option 2" means, but I'll find out when I look at it :-) Please go ahead!

> @ltalirz @sphuber I think we should resolve this issue rather quickly. Do you have an opinion on the best solution here? Otherwise I'll probably proceed with option 1 in combination with option 2.

That's why I brought it up ;-)

**Comment by sphuber** [comment]
How about just stopping the job from running it if it is not on the main repo?
```
jobs:
  validate-dependency-specification:
    if: github.repository == 'aiidateam/aiida-core'
```

This would have to be copy pasted in every job of `test_install.yml` but I think that is ok. I think that is lower maintenance than the bot option, which I think is preferable.

**Comment by csadorf** [comment]
> 1 is a quick fix already, 2 sounds even better. Not quite sure what "option 1 in combination with option 2" means, but I'll find out when I look at it :-) Please go ahead!

We don't need option 1, if we implement option 2, however it could serve as an additional safe-guard. I would primarily implement option 1 to have an immediate fix.

> How about just stopping the job from running it if it is not on the main repo?
> 
> ```
> jobs:
>   validate-dependency-specification:
>     if: github.repository == 'aiidateam/aiida-core'
> ```
> 
> This would have to be copy pasted in every job of `test_install.yml` but I think that is ok. I think that is lower maintenance than the bot option, which I think is preferable.

That is equivalent to option 1, so I'm already proposing to do this.
