### ISSUE TITLE
Control verbosity of click output

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#4330]
So far, the verdi cli has been using variations of `click.secho` in order to write information to the command line
(e.g. `echo_info()`, `echo_warning()`, `echo_critical()`, ...). This automatically adds colored indicators for info/warning/... levels but offers no way to suppress any of the echoed information.

As evidenced by https://github.com/aiidateam/aiida-core/issues/3864, it is sometimes useful to print information for debugging purposes -- or, more generally, to control the verbosity of the information printed by a verdi command.

It would therefore be useful to introduce a command line option that allows to control the verbosity of the output of verdi commands.

**Comment by ltalirz** [comment]
PR https://github.com/aiidateam/aiida-core/pull/3896 contains an implementation of this, using python's built-in logging module to build a custom handler that outputs log messages to the console via click.
It also adds a click VERBOSITY option (that can be added to any command) which allows to specify the verbosity of the logger.

Note: The code is inspired by the `click_log` package (but needed to be modified in order to fit the needs of AiiDA).

### Remaining design decisions

 - [ ] decide where to place the verbosity option (`verdi -v DEBUG profile list` vs `verdi profile list -v DEBUG`)
click [has decided not to support the definition of shared options for subcommands](https://github.com/pallets/click/issues/108#issuecomment-194465429), i.e. if we want the verbosity option to be available at the level of the subcommand, we need to add it to each subcommand individually (as needed).

 - [ ] decide the format of the verbosity option (`-v DEBUG` vs `-v -v -v` etc.)  
        I prefer to keep in line with `click_log` which uses `-v DEBUG`. This is more flexible since it also allows to *decrease* the log level.


Mentioning @sphuber @CasperWA @csadorf in case you have input on this

**Comment by csadorf** [comment]
1. I think that placing it globally makes more sense. If we feel strongly then we could add it to the sub-commands, but then we probably want to add it everywhere, otherwise it's going to be frustrating when it works sometimes and sometimes not.
2. As a user I usually prefer the _add more `-v`s_ approach, because it is more concise and does not require consulting the manual for log-level names. If we needed to decide between one approach, then I would personally prefer that one. However, I can also see a combination, where adding `-v`s increases the verbosity by one level, but providing a named option such as `-v DEBUG` or `--verbosity=DEBUG` overrides that and provides then even more control.

**Comment by sphuber** [comment]
I agree with @csadorf that if we are going to homogenize this then it makes most sense if it is available for all commands so I would also go that route. I agree also though that having to add it right after `verdi` just like the `--profile` option can be annoying. I can imagine people executing a command and it failing, then wanting to reexecute and so press up in history and type `-v`. With this solution they would have to seek in the command first in order to add the flags. I am wondering if there is another solution that will allow us to automatically add the option to all our subcommands. Couldn't we define a subclass of `click.Command` and have `verdi` commands always use this as base class, which automatically adds the `VERBOSE` option for all terminal commands. Would be worth investigating if this could be implemented I think.

Regarding the option style: I am ambivalent and see advantages/disadvantages for both. It is true that the `--verbose=warning` requires more typing and knowing the value, given that the value would correspond to the prefix of the messages and these are Python default names, I think it would potentially be ok. Actually it could be clearer, because although with `-v` you don't need to know the value, what does `-v` correspond to? And `-v -v`? Is that "warning" or "info" or what?

This shows another downside of the `-v` style. Normally, CLI's have three levels, so there is `-v`, `-vv` and `-vvv`. However, we have more than 4 levels.

To conclude, if we are going to tie it anyway to the logging levels, I think I prefer the `--verbosity warning` form for the option. Ultimately this will feel more intuitive and be easier to use.

**Comment by CasperWA** [comment]
Both @sphuber and @csadorf's suggestions concerning `-vv` and `-v LOG_LEVEL`  seems to coincide, unless I should interpret @sphuber's comment as _not_ wanting the `-vv` at all, but _only_ the `-v LOG_LEVEL`. For this I would support both options being available, as @csadorf also suggests. The shortcomings of not exactly knowing the level when using `-vv` can be overcome by using `-v LOG_LEVEL`, and more experienced users can then use the shorter, more effecient `-vv` option.

I'm interested in seeing what can be found out through @sphuber's suggestions concerning the global use as well, since I think it should definitely be globally available as well, because as a user, you may not always be aware of which commands actually make use of logging and which don't, so it's good to have it work globally. And preferably no matter where the option is placed in the command.

**Comment by sphuber** [comment]
I would actually definitely not provide both types of option, I think that only causes more confusion. When to use both? What is the difference.

For clarity, I think the `-v LEVEL` form is the better one.

> since I think it should definitely be globally available as well, because as a user, you may not always be aware of which commands actually make use of logging and which don't, so it's good to have it work globally.

Note that it is not a question of knowing which commands use the logging to produce their messages (we should make sure that all commands only use one method, i.e. all use the new logging method) but knowing which commands actually provide the verbosity option to control the output.

**Comment by ltalirz** [comment]
Ok, I agree that supporting both `-v` and `-v DEBUG` is not a good idea, already because it will cause problems with arguments (if the command has an argument, you would need to use `-v DEBUG --` or similar, in any case, it gets complicated).
Let's stick with `click_log` is doing for the time being.

I did have a look at adding the option globally and I believe I've found a simple way to make it work. Will play around with it a bit more.

**Comment by sphuber** [comment]
> Let's stick with what `click_log` is doing for the time being.

which is?

**Comment by ltalirz** [comment]
See aboveL

> I prefer to keep in line with click_log which uses -v DEBUG. This is more flexible since it also allows to decrease the log level.

**Comment by chrisjsewell** [comment]
Right this `-vv` vs `-v LOG_LEVEL` has come up again in #4904, so lets put it to bed:

- I vote for `-v LOG_LEVEL` (plus I've already implemented that for `verdi archive` lol)
- @sphuber voted for `-v LOG_LEVEL`
- @ltalirz voted for `-v LOG_LEVEL`
- @csadorf voted for both 
- @CasperWA voted for both

thats 3 to 2 for `-v LOG_LEVEL`, any objections?
