### ISSUE TITLE
Noisy but harmless exceptions reported when interpreter, that has run processes, ends

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4346]
When a Python interpreter ends that has run processes, the stdout will be flooded with the following stack trace:
```
Exception ignored in: <generator object create_task.<locals>.run_task at 0x7f174d3ce6d0>
Traceback (most recent call last):
  File "/home/sph/code/aiida/env/dev/plumpy/plumpy/futures.py", line 102, in run_task
  File "/usr/lib/python3.7/contextlib.py", line 158, in __exit__
AttributeError: 'NoneType' object has no attribute 'exc_info'
```
This is due to the change of f9f6c9ca4ddd4f216c5a0e3e784976a78e8c5ca6 that now closes the event loop if the `Runner` shutsdown. Closing the loop allows these messages that have been collected to be printed. The messages themselves come from the future that add and remove task and broadcast subscribers, when a `Process` is initialized and destroyed, respectively. 

These exceptions do not not show up in Python 3.8, but do for lower version. Have confirmed it for Py 3.5 and 3.7. The exception seems to come from the following line in the Python built in module `contextlib`:
https://github.com/python/cpython/blob/4e02981de0952f54bf87967f8e10d169d6946b40/Lib/contextlib.py#L158

Somehow, it seems that at that point `sys` is already `None`.
We should try and find a way to prevent this exception from happening, or at the very least suppress the messages, because there wlll be two copies printed for each process run, and so they are really numerous.

**Comment by sphuber** [comment]
The workaround needs to happen in `plumpy` which is taken care of in [this issue](https://github.com/aiidateam/plumpy/issues/168). Once merged, this will be shipped in `0.15.1` and we can update the requirement in `aiida-core`.

**Comment by greschd** [comment]
Ha, by chance I was reading up on the Python shutdown process yesterday: The modules being replaced by `None` is known behavior, mentioned e.g. [in the weakref.finalize doc](https://docs.python.org/3/library/weakref.html#weakref.finalize).

The fact that exceptions can be raised due to this is also mentioned here: https://docs.python.org/3/glossary.html#term-interpreter-shutdown.

**Comment by sphuber** [comment]
[Putting in a fix right now that is perfect and by no means a horrible dirty work-around](https://github.com/aiidateam/plumpy/pull/169) ;)

**Comment by sphuber** [comment]
I thought about making a `v1.3.2` for this, but people can simply install `plumpy==0.15.1` and the problem will have been fixed. I think this should not require a release on our side, upping the patch version, because everything works with the current dependencies, there are just annoying messages printed to screen.

**Comment by ltalirz** [comment]
@sphuber Is there a reason why plumpy was not bumped to 0.15.1 in aiida-core 1.4.0?
https://github.com/aiidateam/aiida-core/blob/01845181740c2768ce3c31165a3f80e18d241a9f/setup.json#L39

Should we do this now?

**Comment by sphuber** [comment]
No particular reason, other than it is not required to have 0.15.1 so didn't see the need to bump it. I thought `pip` would automatically update it. Anyway, I will have to release `1.4.1` soon, so I will include a bump.

**Comment by ltalirz** [comment]
> I thought pip would automatically update it.

I think you're right, if people do `pip install --upgrade aiida-core` (which is what [we officially recommend](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/installation.html?highlight=update#updating-your-installation)).
However, people tend to be wary of upgrading all packages in an environment, so we should not assume that everyone does that.

(I came across this because Daniele noticed these errors in our runs)
