### ISSUE TITLE
Docs: remove old content from 'working_with_aiida/'

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-core#4452]
This is a structure that was left over from the old documentation and needs to be removed, but first we need to check if all the content has been re-assigned in the new documentation. The files considered are:

- [x] [index.rst](https://aiida-core.readthedocs.io/en/v1.1.0/working_with_aiida/index.html): This is mostly an index but also contains a few intro lines before the scripting section and the schedulers section that might be worth looking into.
- [x] [python_api.rst](https://aiida-core.readthedocs.io/en/v1.1.0/working_with_aiida/python_api.html): This content could maybe go in the internals: global design?
- [x] [daemon_service.rst](https://aiida-core.readthedocs.io/en/v1.1.0/working_with_aiida/daemon_service.html): This seems like short and practical information on how to set up the daemon, not sure if it is still relevant, but if it is maybe it should be a sub-section of the ["howto: manage your installation"](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/installation.html)?
- [x] [resultmanager.rst](https://aiida-core.readthedocs.io/en/v1.1.0/working_with_aiida/resultmanager.html): This content seems to already be included in ["howto: run external codes"](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/run_codes.html) section.
- [x] [deleting_nodes.rst](https://aiida-core.readthedocs.io/en/v1.1.0/working_with_aiida/deleting_nodes.html): This content seems to already be considered in ["howto: work with data"](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/data.html#deleting-data) section.
- [x] [scripting.rst](https://aiida-core.readthedocs.io/en/v1.1.0/working_with_aiida/scripting.html): This is a general introductory description on how to run scripts; maybe it is already covered by the tutorial?
- [x] [cookbook.rst](https://aiida-core.readthedocs.io/en/v1.1.0/working_with_aiida/cookbook.html): This contains two useful scripts which are actually not so related to one another? Perhaps this would could be in a section of the AiiDA blog for recipes and useful scripts.

### Proposition:

Here it seems like each file is very different and should receive a different treatment. I outlined a general description of the content and some ideas of where to put it in the new docs in the cases I could think of, but this is the section I'm most unsure of and would appreciate some extra feedback.

**Comment by mbercx** [comment]
> * [ ]  [python_api.rst](https://aiida-core.readthedocs.io/en/v1.1.0/working_with_aiida/python_api.html): This content could maybe go in the internals: global design?

The paragraph on the "second-level packages" and the use of `__all__` should probably be put into #4039, indeed. As for the structure of the packages themselves, I suppose this is already provided by the ["Reference"](https://aiida.readthedocs.io/projects/aiida-core/en/latest/reference/apidoc/aiida.html#subpackages)?

> * [ ]  [daemon_service.rst](https://aiida-core.readthedocs.io/en/v1.1.0/working_with_aiida/daemon_service.html): This seems like short and practical information on how to set up the daemon, not sure if it is still relevant, but if it is maybe it should be a sub-section of the ["howto: manage your installation"](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/installation.html)?

I'm also not sure if this is still relevant/recommended.

> * [x]  [resultmanager.rst](https://aiida-core.readthedocs.io/en/v1.1.0/working_with_aiida/resultmanager.html): This content seems to already be included in ["howto: run external codes"](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/run_codes.html) section.

Is it? This file seems to be more about retrieving results, which seems to be missing from the "How to run external" codes section. Maybe we should add a subsection after "How to submit a calculation"?

> * [x]  [deleting_nodes.rst](https://aiida-core.readthedocs.io/en/v1.1.0/working_with_aiida/deleting_nodes.html): This content seems to already be considered in ["howto: work with data"](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/data.html#deleting-data) section.

👍 

> * [ ]  [scripting.rst](https://aiida-core.readthedocs.io/en/v1.1.0/working_with_aiida/scripting.html): This is a general introductory description on how to run scripts; maybe it is already covered by the tutorial?

The only thing that's not covered by the tutorial is the `verdi run` command and the `runaiida` executable. If we want people to use these, perhaps these can be moved to "How to submit a calculation"?

> * [ ]  [cookbook.rst](https://aiida-core.readthedocs.io/en/v1.1.0/working_with_aiida/cookbook.html): This contains two useful scripts which are actually not so related to one another? Perhaps this would could be in a section of the AiiDA blog for recipes and useful scripts.

I'm also not sure where to place these. Would there be room for a "CookBook" subsection in the How-to section, where we place useful code snippets that don't really have a home elsewhere?

**Comment by sphuber** [comment]
* `index.rst`: remove it, the few lines of texts are not very useful and even incorrect in some parts.
* `python_api.rst`: this is actually user facing documentation. It tells users which resources are intended to be used by clients and therefore come with stability guarantees. Ideally then, it should be close to the actual API reference. However, this one is automatically generated, so we should see how to best integrate it.
* `daemon_service.rst`: this is a bit OS-specific but potentially still valuable information. The suggestion is to move this to `howto/installation.rst` after the "Isolating multiple instances" section, in a section called "Daemon as a system service". Instead of copying the content of the script inline, use [this link](https://github.com/marvel-nccr/ansible-role-aiida/blob/c709088dff74d1e1ae4d8379e740aba35fb2ef97/templates/aiida-daemon%40.service) for the template that they can copy and then [this link](https://github.com/marvel-nccr/ansible-role-aiida/blob/c709088dff74d1e1ae4d8379e740aba35fb2ef97/tasks/aiida-daemon.yml) to describe how to install it.
* `resultmanager.rst`: we couldn't actually find anywhere in the current docs that explains the `inputs`, `outputs` and `res` managers, but this is crucial information. We think there should be a new top-level How-to called "How to explore the provenance graph" that describes all these methods: `get_incoming`, `get_outgoing`, the `inputs` and `outputs` short cuts and the `res` manager for `CalcJobNodes`.
* `scripting.rst`: this information is important and is not yet present. Should probably be a new page in the how-tos, the very first one, called "How to interact with AiidA". Should explain that there are multiple ways of interacting, give itemization: shell, script, REST API. Each one is then explained a bit, with links to other parts of documentation with more detailed information (e.g. in the case of REST API), not sure it applies to the shell and scripts.
* `cookbook.rst`: make this a new How-to page, just before the FAQ

**Comment by chrisjsewell** [comment]
note that when https://github.com/aiidateam/aiida-core/pull/4457 is merged, you can add redirects to these pages to the new documentation in docs/source/redirects.txt

**Comment by sphuber** [comment]
These are now all addressed, all content of `working_with_aiida` has been moved into place or removed
