### ISSUE TITLE
Is there a way to get all valid options of `verdi config`?

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#4480]
Currently (but maybe I just missed it) I don't find an easy way to list valid `verdi config` options.

They are listed here 
https://github.com/aiidateam/aiida-core/blob/2174924e40c3c9f00263f2e892e63a07eb90b40f/aiida/manage/configuration/options.py#L25
and there is also a list of descriptions, defaults, ...
However I cannot find a way to get them.

E.g. `verdi config -h`
only returns
```
Usage: verdi config [OPTIONS] OPTION_NAME OPTION_VALUE

  Configure profile-specific or global AiiDA options.

Options:
  --global    Apply the option configuration wide.
  --unset     Remove the line matching the option name from the config file.
  -h, --help  Show this message and exit.
```
Should we add e.g. a `-l/--list` option that provides a human-readable list of valid options?
E.g.  something like:
```
- runner.poll.interval [int, default = 60; key = runner_poll_interval]
   The polling interval in seconds to be used by process runners

- daemon.default_workers [int, default = 1; key = daemon_default_workers
  The default number of workers to be launched by `verdi daemon start`
...
```

**Comment by sphuber** [comment]
They are tab-completed, so you can just tab twice to get them all listed. We already had a discussion before with @chrisjsewell that it would be good to be able to see the default.

**Comment by giovannipizzi** [comment]
Ok thanks. I think that a `-l` option would work (see e.g. the behaviour of `git tag`)

**Comment by mbercx** [comment]
I was also looking for this feature today. 😅 

Adding a `-l` option would definitely work. Maybe we should consider two different lists, i.e. the list of valid options with explanations and defaults, as @giovannipizzi described, and also the list of options that have been configured by the user (as e.g. `git config -l`.

Another idea would be to add subcommands like `list`, `set`, `unset`, ... This wouldn't be backwards compatible, but it would match better with the rest of the CLI. Since I'm always typing `verdi code list`, `verdi group list`, etc, it's more intuitive to then use `verdi config list`.

**Comment by chrisjsewell** [comment]
> EDIT: This seems to be a duplicate of #4260.

Exactly what I was going to say lol.
I think I'm seeing a consensus here that, as I've already said `verdi config` is not a good interface and needs "another level" to manipulate the config, much like the rest of our CLI (list, show, ...)

**Comment by chrisjsewell** [comment]
folding in to #4584
