### ISSUE TITLE
Docs: RTD site switched from aiida-core to aiida

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#4484]
At some point (relatively recently) our docs moved from https://aiida-core.readthedocs.io/ to https://aiida.readthedocs.io/. It is unclear if this was intentional (nobody recalls doing this, although apparently we do have both aiida and aiida-core RTD projects), or something RTD did.

The main issue here is that the aiida-core homepage above relinks to https://aiida.readthedocs.io/, but if you go to a specific page like e.g. this:
https://aiida-core.readthedocs.io/en/v1.1.0/developer_guide/core/internals.html
you get a banner saying "You are not reading the most recent version of this documentation. v1.3.1 is the latest version available." (i.e., it "stops" at v1.3.1).

Also, typically the link to v1.3.1 breaks and goes to a 404.

If people land on the old pages there is a good possibility they may get lost.

**Comment by chrisjsewell** [comment]
cc @ltalirz @giovannipizzi

**Comment by giovannipizzi** [comment]
Thanks @chrisjsewell for the report!
We've investigated with @ltalirz and fixed it.

Some background info:
- the main project is still `aiida-core` on RTD
- in the settings for the `aiida` project on RTD, under admin/subprojects, aiida-core is listed: in this way, the domain becomes aiida.readthedocs.io and pages get redirected

What we did to fix the issue:
- version v1.4.0 was active but not built: we triggered a build
- on readthedocs, we manually activated v1.4.1 and v1.4.2, they now show up as versions both in the new docs, and in the old ones (check e.g. [this page](https://aiida.readthedocs.io/projects/aiida-core/en/v1.0.1/get_started/computers.html) that now correctly says that the most recent version is v1.4.2)
- the link to the most recent version v1.4.2 still doesn't work because the redirects were just merged, so they are not in v1.4.2, therefore the [v1.4.2 link](https://aiida.readthedocs.io/projects/aiida-core/en/v1.4.2/get_started/computers.html) is still broken; but if you replace v1.4.2 with latest, the new redirects get correctly triggered, i.e. this one specifically:
https://github.com/aiidateam/aiida-core/blob/db659ddf8a36db77963e2955df5066876c0d8017/docs/source/redirects.txt#L15

 - Regarding version activation: for now we've [added a paragraph in the release wiki](https://github.com/aiidateam/aiida-core/wiki/How-to-make-a-new-release#activating-the-version-on-readthedocs) - but we've also found a way to activate automatically new tagged semvers - since we couldn't test it, we've left the paragraph, with a note for the next release to check if the automation works, in which case the paragraph can be removed.

**Comment by giovannipizzi** [comment]
As a side note: @chrisjsewell as soon as we merge the most important redirects, it would be good to release a v1.4.3 to make sure that the documentation links continue working (say by the end of this week, or next week latest, unless there are blocking issues to make a PR - great to discuss this tomorrow at the AiiDA meeting)
