### ISSUE TITLE
Set default tag of Groups in QueryBuilder as "Group_1"

### ISSUE THREAD

**Issue by danieleongari** [aiidateam/aiida-core#4533]
Using often the QueryBuilder, it becomes particularly convenient for the shorter ones not to set tags but to use default tags, such as `CifData_1`, `Dict_1`, `Node_1` etc. with progressive number depending of the Data of the same tipe in the query.
I'm wondering why Groups are tagged by default as  `core_1` instead of `Group_1` and if it wouldn't be more convenient to use the second. 
Indeed it is not very intuitive to remember `core_1`, especially with lower case, and personally I have to check it out every time.

**Comment by chrisjsewell** [comment]
> I'm wondering why Groups are tagged by default as core_1 instead of Group_1

this is the typestring of the group.

Basically in `aiida/orm/querybuilder.py::get_querybuilder_classifiers_from_cls` the classifier is set as `group.core` (or whatever the type string is for that group subclass).

But then in `aiida/orm/querybuilder.py::_get_unique_tag` the classifier is split on '.' and so you end up with only `core`.

I agree though, in `get_querybuilder_classifiers_from_cls` we should just set it as something like `GROUP_ENTITY_TYPE_PREFIX + cls._type_string + '.' + cls.__name__`, i.e. `group.core.Group`, `group.core.auto.AutoGroup`, etc

**Comment by sphuber** [comment]
You cannot change these classifiers though like this, because they are actually used in the querying and changing them will break querying. The functionality that automatically creates the tags, merely repurposes the classifiers to define a tag if not specified by the user. You could update that particular code to provide something more intuitive, but honestly I am not sure if we should suggest that people use the default tags. I am not sure that we can guarantee the stability and consistency of these tags. Ultimately the solution is very simple: just define an explicit tag. It also makes the `QueryBuilder` definition code much more explicit and easy to read I think

**Comment by danieleongari** [comment]
Ok, thanks for the explanation. It is not a big problem, so if there is not a trivial solution to rename the default tag to `Group_x`, I think it is fine to close this issue.

**Comment by chrisjsewell** [comment]
No worries I will go ahead and close this for now cheers
