### ISSUE TITLE
Why `get_function_source_code` return source file of the function not the source function itself?

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#4543]
https://github.com/aiidateam/aiida-core/blob/06063e7c38b6e40d3d2fbafe84e4e7f6adc8782a/aiida/orm/utils/mixins.py#L108-L113

Would this more make sense if the source code of function rather than the source of the file is returned? 
Besides, if I understand it correctly, every process function will be stored along with a source file in the repository. Is that too redundant to store the same files every time when the `ProcessNode` call and store?

**Comment by sphuber** [comment]
Not sure, because the rest of the file can also be important for the process function, for example other functions that may be defined or imports. Of course we can add a method that gives just the source code of the function itself, and potentially rename the current one, that would be possible I would say.

I just noticed by the way that the docstring is incorrect, the `:returns:` is incorrect as it says the filepath will be returned.

With respect to the duplication of the source code: this is indeed very inefficient, but fortunately with the new repository implementation that will be merged for `aiida-core==2.0.0`, that will be automatically fixed. That repo implementation will automatically deduplicate content.

**Comment by unkcpz** [comment]
I just find that display the source code of the function rather than the whole file is much concise in Material Cloud explore. I propose to add the method to give the source code.
However, It might not be a good idea to store the source of the function as an attribute.

**Comment by ltalirz** [comment]
> I propose to add the method to give the source code.

That sounds good to me.

> However, It might not be a good idea to store the source of the function as an attribute.

I agree that this can be problematic and would advise against it, see also https://github.com/aiidateam/aiida-core/issues/3714 
The basic principle should be to store in the DB what you want to query for and I imagine that querying the source code of workfunctions is not really a use case people have (?)
