### ISSUE TITLE
indicate development version in AiiDA version number

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#4551]
### Is your feature request related to a problem? Please describe

As of today, the AiiDA version number in the `develop` branch tends to be the version number of the last release.

This means when running on the `develop` branch and
 - creating AiiDA archives
 - running calculations
 - ...

the version number recorded will be that of the latest AiiDA release, despite the fact that the source code may have changed significantly since then.

The output of 
```
$ verdi --version
AiiDA version 1.4.2
```
also currently gives no indication on whether one is running an official release or a development version.

### Describe the solution you'd like

It would be useful, if the AiiDA version reported by an install based on the `develop` branch would have *some* indication of the fact that it is a development version.

This is not something that would have to be invented from scratch; other packages have already built solutions for this - see .e.g

 - [bokeh](https://github.com/bokeh/bokeh/blob/branch-2.3/bokeh/__init__.py#L67)
 - [panel](https://github.com/holoviz/panel/blob/master/panel/__init__.py#L10)
 - [django](https://github.com/django/django/blob/master/django/__init__.py)

(please feel free to add to the list)

**Comment by greschd** [comment]
I see basically two options:
- use the last-released version + suffix
- use the upcoming version + suffix

Since it's not always known which will be the next version, the first option seems better to me. PEP440 then dictates which kind of suffixes can be used: https://www.python.org/dev/peps/pep-0440

I see two options that would make sense (in order of preference):
- `x.y.z+dev`: https://www.python.org/dev/peps/pep-0440/#local-version-identifiers
- `x.y.z.post0`: https://www.python.org/dev/peps/pep-0440/#post-releases (drawback: this has the semantic of being a post-_release_)

Of course you could also do something where the git commit hash is incorporated in some way like `x.y.z+<hash_part>`. Maybe that'd involve too much extra scaffolding?

**Comment by ltalirz** [comment]
> Since it's not always known which will be the next version, the first option seems better to me.

Fully agree.

`x.y.z+dev` sounds fine to me - I don't have strong feelings about the exact string.

> Of course you could also do something where the git commit hash is incorporated in some way like `x.y.z+<hash_part>`. Maybe that'd involve too much extra scaffolding?

Well, that scaffolding already exists e.g. in panel/bokeh
```
>>> import panel
>>> panel.__version__
'0.10.0a25.post3+g834940c'
```
```
>>> import bokeh
>>> bokeh.__version__
'2.2.0rc3-28-gb624d48a'
```
I.e. we would just need to decide which one to reuse

**Comment by greschd** [comment]
> '2.2.0rc3-28-gb624d48a'

I think the dash is not PEP440-compatible:

```python
In [2]: from packaging import version

In [3]: version.parse('1.0.2-foo')
Out[3]: <LegacyVersion('1.0.2-foo')>

In [4]: version.parse('1.0.2+foo')
Out[4]: <Version('1.0.2+foo')>
```

It seems panel uses this: https://param.holoviz.org/Reference_Manual/param.html#param.version.Version

I guess the usual considerations of adding an additional dependency apply.

Another side effect of adding the git hash would be that every commit invalidates caches - I'm not sure if that'll be annoying, or a feature.

**Comment by sphuber** [comment]
As a side-note: `verdi --version` will also not necessarily display the correct current version even if we were to add a specific `+dev` qualifier. If you install `aiida-core` in editable mode, let's say at tag `v1.4.2` after install `verdi --version` will show `v1.4.2`. However, if you now switch to another branch with another version, `verdi --version` will still show the same and not the new version. I think this is a limitation or bug, depending on how you look at it, of the `@click.version_option` decorator that we use for this functionality. It apparently just checks the version that gets written once the package is installed and does not dynamically check the actual package. I will open another issue for this because I think this is a problem in and of itself that I encountered myself before.

**Comment by greschd** [comment]
Guess that's a limitation of `importlib.metadata.version`, in the `master` branch they added some more documentation for that: https://click.palletsprojects.com/en/master/api/#click.version_option

We should be able to get around that by simply passing `version=aiida.__version__`. That might be a few milliseconds slower, but at least it'll be correct.

**Comment by sphuber** [comment]
As far as I understand it would require us to  literally include the source code of the `_version.py` file that is generated by the tool, which is not small. This would also mean we would have to maintain this file. At that point I am not sure this is an easier solution than to just adopt a small convention ourselves as described previously that when after a merge of `develop` into `master` a new commit is placed on `develop` to update the `__version__` attribute to the next tentative release, with `+dev` suffix. This shouldn't be much work given that we don't release that often and would solve the issue

**Comment by jbweston** [comment]
> As far as I understand it would require us to literally include the source code of the _version.py file that is generated by the tool, which is not small.

FYI there is https://github.com/jbweston/miniver, which does not include quite as much stuff as versioneer (< 200 lines).

It also works properly when you "download Zip" from GitHub

**Comment by sphuber** [comment]
This was addressed in https://github.com/aiidateam/aiida-core/commit/8fa2d4e1744715a27d0b34285094861b62196ad8
I have updated the wiki on creating a release with the procedure and justification: https://github.com/aiidateam/aiida-core/wiki/How-to-make-a-new-release#post-release-adding-post0-qualifier-to-version-attribute
