### ISSUE TITLE
make_hash: positive and negative zero have different hashes

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-core#4610]
The `make_hash` function produces different results for positive (``0.``) and negative zero (``-0.``) floats:

```python
In [1]: from aiida.common.hashing import make_hash

In [2]: make_hash(0.)
Out[2]: '20a995d105ee978f320718c436d64a725454f61a3684b4751b34756e04d58365'

In [3]: make_hash(-0.)
Out[3]: '7c8fd8f1e2ffeffd8938d846a8aa1be14780cc8b6d003cd6fe124cb30ccb2cc8'
```

The code responsible for hashing floats is 

https://github.com/aiidateam/aiida-core/blob/e303cc450d3dd1e949de39785cbc141aa340ac70/aiida/common/hashing.py#L194-L200

and 

https://github.com/aiidateam/aiida-core/blob/e303cc450d3dd1e949de39785cbc141aa340ac70/aiida/common/hashing.py#L283-L292

The "truncation" to a specific number of significant digits here is to ensure consistent hashes before and after storing, because floats can be slightly changed when stored to the database. In this case however, this goal isn't met:

```python
In [2]: from aiida import orm

In [3]: f = orm.Float(-0.)

In [4]: f
Out[4]: <Float: uuid: 1723092d-5e30-46d3-b72a-b9957d5479ec (unstored) value: -0.0>

In [5]: f._get_hash()
Out[5]: '446391aa2fa4107ce1a3640eb96d4b3fcc2c4e107925362e9616eb3af0bd1b93'

In [6]: f.store()
Out[6]: <Float: uuid: 1723092d-5e30-46d3-b72a-b9957d5479ec (pk: 252658) value: 0.0>

In [7]: f.get_hash()
Out[7]: '09193d9becebc2ebb09dae8102f02a04aa82478ac7507c6d9b55d253ed7167f6'
```

Now technically `-0.` and `0.` are different objects, and it's valid (but not required) that they hash differently. However, since the storing converts `-0.` to `0`, I feel it would be more practical if they had the same hash. This could be achieved e.g. by adding 
```python
if value == 0:
    value = 0.
```
to `float_to_text`.

I believe this won't need rehashing of the DB, because _when stored_ the zeroes are already converted, and this only affects unstored values. Not 100% sure there isn't some edge case here, though.

**Comment by greschd** [comment]
After looking into this a bit, it seems a more general solution to this would be passing everything through `clean_value` if `_get_hash` is called on an unstored node.

**Comment by ramirezfranciscof** [comment]
Is this backend specific? I'm not getting any conversion for `-0.` with `clean_value`:

```ipython
In [2]: from aiida.orm.implementation.utils import clean_value

In [3]: clean_value(0.)
Out[3]: 0.0

In [4]: clean_value(-0.)
Out[4]: -0.0
```

Or maybe I am misunderstanding your proposed solution?

**Comment by greschd** [comment]
The point is that `clean_value` _doesn't_ convert, but the database might / does, which is why storing the node changes the value from `-0.` to `0.`.

```python
In [2]: from aiida import orm

In [3]: f = orm.Float(-0.)

In [4]: f
Out[4]: <Float: uuid: 1723092d-5e30-46d3-b72a-b9957d5479ec (unstored) value: -0.0>

In [5]: f._get_hash()
Out[5]: '446391aa2fa4107ce1a3640eb96d4b3fcc2c4e107925362e9616eb3af0bd1b93'

In [6]: f.store()
Out[6]: <Float: uuid: 1723092d-5e30-46d3-b72a-b9957d5479ec (pk: 252658) value: 0.0>

In [7]: f.get_hash()
Out[7]: '09193d9becebc2ebb09dae8102f02a04aa82478ac7507c6d9b55d253ed7167f6'
```

It might also be backend specific, I don't know. But since only `clean_value` is called before hashing, in this case the hash changes when storing.

**Comment by ramirezfranciscof** [comment]
So, I found a little practical problem whem implement the solution. The modification with the `if value == 0: ...` inside of `clean_value` seems to work fine, but apparently whats get passed to `make_hash` inside of `_get_hash` can't be directly parsed by `clean_value`.

Here is the code of `_get_hash`; my idea was to call `clean_value` on the return of `self._get_objects_to_hash()` inside the arguments of `make_hash`.

<details> <summary> aiida/orm/nodes/node.py : _get_hash </summary> <br>

```python
    def _get_hash(self, ignore_errors=True, **kwargs):
        """
        Return the hash for this node based on its attributes.

        This will always work, even before storing.
        """
        try:
            return make_hash(self._get_objects_to_hash(), **kwargs)
        except Exception:  # pylint: disable=broad-except
            if not ignore_errors:
                raise
```
</details>

The problem is that the return `_get_objects_to_hash()` can't be fed directly into `clean_value` (apparently it doesn't know what to do with the `Folder` object). Here is what it looks like when I try it:

<details><summary> Tests in the shell </summary><br>

```python
In [1]: from aiida import orm

In [2]: from aiida.orm.implementation.utils import clean_value

In [3]: f = orm.Float(-0.)

In [4]: f._get_objects_to_hash()
Out[4]: ['1.5.2', {'value': -0.0}, <aiida.common.folders.Folder at 0x11125f6d0>, None]

In [5]: clean_value(f._get_objects_to_hash())
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
<ipython-input-5-cb217e744d32> in <module>
----> 1 clean_value(f._get_objects_to_hash())

~/Codes/aiida-core/aiida/orm/implementation/utils.py in clean_value(value)
    111         # This should also properly take care of dealing with the
    112         # basedatatypes.List object
--> 113         return [clean_value(v) for v in value]
    114 
    115     # If I don't know what to do I just return the value

~/Codes/aiida-core/aiida/orm/implementation/utils.py in <listcomp>(.0)
    111         # This should also properly take care of dealing with the
    112         # basedatatypes.List object
--> 113         return [clean_value(v) for v in value]
    114 
    115     # If I don't know what to do I just return the value

~/Codes/aiida-core/aiida/orm/implementation/utils.py in clean_value(value)
    118     # but is not an integer, I still accept it)
    119 
--> 120     return clean_builtin(value)

~/Codes/aiida-core/aiida/orm/implementation/utils.py in clean_builtin(val)
     98 
     99         # Anything else we do not understand and we refuse
--> 100         raise exceptions.ValidationError(f'type `{type(val)}` is not supported as it is not json-serializable')
    101 
    102     if isinstance(value, BaseType):

ValidationError: type `<class 'aiida.common.folders.Folder'>` is not supported as it is not json-serializable
```
</details>

I'm not familiar enough with the possible different values for this `_get_objects_to_hash()` method, so I don't think trying to open the list and deal with each element separatedly is a good idea.

Now, I have also checked the code of `make_hash` you quote in the OP. I think ideally one would want the "homogenization" code to be in a single place, right? Here it would seem we have a way of doing it in `@_make_hash.register(numbers.Real)` and a way of doing it in `clean_value` and they need to remain consistent (opposed to having `@_make_hash.register(numbers.Real)` call `clean_value` for example). Am I correct?

If I do this (call `clean_value` inside `@_make_hash.register(numbers.Real)`) everything seems to work fine (I am having some problems when running the unit tests locally in general, but the ones that work on develop also work with this modifications). I am unsure of how it might complicate the dependency tree to add an import from `aiida.orm` inside `aiida.common.hashing`, I didn't get any redundancy complaint so far but I think it is not ideal.

<details>
<summary> aiida/common/hashing.py : @_make_hash.register(numbers.Real) </summary>
<br>

```python
@_make_hash.register(numbers.Real)
def _(val, **kwargs):
    """
    Before hashing a float, convert to a string (via rounding) and with a fixed number of digits after the comma.
    Note that the `_singe_digest` requires a bytes object so we need to encode the utf-8 string first
    """
    from aiida.orm.implementation.utils import clean_value
    clean_val = clean_value(val)
    return [_single_digest('float', float_to_text(clean_val, sig=AIIDA_FLOAT_PRECISION).encode('utf-8'))]
```
</details>

<details>
<summary> Tests in the shell </summary>
<br>

```python
In [1]: from aiida import orm

In [2]: from aiida.orm.implementation.utils import clean_value

In [3]: f = orm.Float(-0.)

In [4]: f._get_hash()
Out[4]: 'b3f47d77dd54ddc0f726be7fb0d060678ec81a591ed2da896e612ba92a96cc42'

In [5]: f.store()
Out[5]: <Float: uuid: 88640c56-5580-45a8-bb32-f967bd982cd7 (pk: 2) value: 0.0>

In [6]: f.get_hash()
Out[6]: 'b3f47d77dd54ddc0f726be7fb0d060678ec81a591ed2da896e612ba92a96cc42'
```

</details>

Thoughts?

**Comment by greschd** [comment]
Hmm.. it seems I missed the detail that `clean_value` is intended only for "base type" nodes. Maybe it's a bad idea to link `clean_value` and `make_hash` together after all. We could go back to adding

```python
if value == 0:
    value = 0.
```
to `float_to_text`. 

I don't think for `clean_value` it's really required that `-0.` is turned into `0.`, but I know the purpose of `clean_value` less well than `make_hash`.
