### ISSUE TITLE
Docs: 404

### ISSUE THREAD

**Issue by RubelMozumder** [aiidateam/aiida-core#4674]
### Describe the current issue

The page for ```create data backup``` corresponds to the ```v1.5.0``` is not available for the on the expected ``` new page``` ```https://aiida.readthedocs.io/projects/aiida-core/en/v1.5.0/backup/index.html```. But the ```new page``` is being recommended from the ```old version page``` ```https://aiida.readthedocs.io/projects/aiida-core/en/v0.11.3/backup/index.html```. If the procedure described for the old version page is the same as for the new version, then it might be helpful if the ```new version page``` would be redirected to the ```old version page```.

**Comment by greschd** [comment]
The current documentation regarding backups is at https://aiida.readthedocs.io/projects/aiida-core/en/v1.5.0/howto/installation.html#backing-up-your-installation

Since the documentation was overhauled (I think, between `1.2.0` and `1.3.0`) there are many pages that moved, and I don't think it's reasonably possible to cross-link them all. The recommendation to switch to the newest version is something that is automatically added on all pages by `readthedocs` -- not sure if there's a way to fix where they link to.

That being said, I wasn't really involved in the documentation overhaul, and someone else may give a more detailed answer.

**Comment by mbercx** [comment]
Indeed, many of the pages were moved in the documentation revamp, so the link to the newest version from readthedocs often doesn't direct to the correct page in the new documentation. We've been adding redirects to the `docs/source/redirects.txt` file to fix these, but there are still some that we've missed. So it's greatly appreciated when these are pointed out so we can fix them! 

I'll open a PR that adds a redirect for the database backup page.
