### ISSUE TITLE
IndexError when trying to load self.report

### ISSUE THREAD

**Issue by mpougin** [aiidateam/aiida-core#4788]
I am doing a screening on several structures. For some structures, I experience the following error when trying to run a Cp2k Calculation:
![cp2k_error](https://user-images.githubusercontent.com/72666131/109539114-361bcb00-7ac1-11eb-9289-bf0e36c810ce.png)

I am working on Linux, and aiida-core 1.5.2. I have python 3.8.5 installed. By the time I was running the calculation, I accidently had tornado 6.1 installed, which I downgraded now. 

Following up on a discussion with @ltalirz , did someone encounter this error before and has a suggestion what the problem in my environment might be?

**Comment by ltalirz** [comment]
Just to pull out from the error message what seems interesting:

This is an error encountered while calling `self.report('remote folders will not be cleaned')`
https://github.com/aiidateam/aiida-core/blob/f4a537d0eb4618e90d56ca8dc2ccecd74ef3958c/aiida/engine/processes/process.py#L552

I.e. it seems the call to `inspect` can not be expected to be safe.

@chrisjsewell should we simply wrap the call to `inspect` in a try/except?

**Comment by chrisjsewell** [comment]
> should we simply wrap the call to inspect in a try/except?

it seems reasonable to not allow this to fail the process, although it would be good to know why `inspect.stack()` did not work in this instance. I guess its possibly due to: https://docs.python.org/3/library/inspect.html#inspect.currentframe

> CPython implementation detail: This function relies on Python stack frame support in the interpreter, which isn’t guaranteed to exist in all implementations of Python. If running in an implementation without Python stack frame support this function returns None.

note, from python 3.5, a named tuple is returned (https://docs.python.org/3/library/inspect.html#inspect.stack)

so I think we could do something like:

```python
function_name = ''
frame = inspect.currentframe()
if frame is not None:
  caller_frame = frame.f_back
  if caller_frame is not None:
      function_name = inspect.getframeinfo(caller_frame).function
```

also to note this is the commit it was added: 5bc6f3010a97f8a015c2b4b393f8af1ef22ef3a8

**Comment by ltalirz** [comment]
Hmm... my blind guess would be that this error occurs when you change a file after the daemon has started (e.g. `git checkout` another branch). The module in question has already been imported by the daemon but the corresponding code is no longer in the file system, and so `inspect` gets confused.

@chrisjsewell  Do you think your implementation would be safer in this case?

If not, I'd also be ok to close this and reopen it if someone else encounters it and can provide more information on the possible origin - as you mention, this code is in aiida-core since 2017 and I've never seen this error before.

**Comment by mpougin** [comment]
Thank you both for your suggestions. @ltalirz , probably that's what happened. That also explains why only part of my calculations failed. Can it also be that it happened when I used aiida from another environment (I got a bit confused with that lately)? I will see if I can reproduce the error, this time changing no settings during the calculation, otherwise I think we can close this for now.

**Comment by ltalirz** [comment]
Ok, then let's close this for the moment.

> Can it also be that it happened when I used aiida from another environment (I got a bit confused with that lately)?

Hm... not sure.

> I will see if I can reproduce the error, this time changing no settings during the calculation

Feel free to reopen if you encounter this again. No need to hunt further if you don't.
