### ISSUE TITLE
Support SQLAlchemy v1.4

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-core#4813]
The sqlalchemy dependency is constrained to v1.3 (#4809 ) as v1.4 is incompatible (see #4808 ). The sqlalchemy project follows a [modified semver approach](https://www.sqlalchemy.org/download.html), where minor releases can have major breaking changes.

**Comment by csadorf** [comment]
@sphuber pointed out that this would likely just require a fix in sqlalchemy-utils: https://github.com/aiidateam/aiida-core/pull/4809#issuecomment-800222797

**Comment by sphuber** [comment]
The issue in `sqlalchemy-utils` [is tracked  here](https://github.com/kvesteri/sqlalchemy-utils/issues/505)

**Comment by sphuber** [comment]
Just FYI: [`sqlalchemy-utils==0.37.0` was just released](https://pypi.org/project/SQLAlchemy-Utils/), which now support `sqlalchemy==1.4`. This should allow us to remove the pin of `sqlalchemy` in our dependencies

**Comment by giovannipizzi** [comment]
After this issue is solved, it would be good to open another one (less urgent than this one) to check which deprecation warnings we get if we turn on `RemovedIn20Warnings`, as explained here: https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#migration-to-2-0-step-two-turn-on-removedin20warnings so we get ready for SQLA 2.0

**Comment by chrisjsewell** [comment]
#4855 did not unpin sqlachemy from 1.3 (it updated sqlalchemy-utils)

**Comment by chrisjsewell** [comment]
this is now done
