### ISSUE TITLE
Improve stashing documentation

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#4814]
_Originally posted by @sphuber in https://github.com/aiidateam/aiida-core/issues/4812#issuecomment-800111916_

> @sphuber you wrote a lovely commit message for [9359b07](https://github.com/aiidateam/aiida-core/commit/9359b079bc49cec6d3f1e871ec856b71928c0696), but didn't add any of this to the documentation wink
> 
> (also some minor improvements to the new  documentation)

I take pride in my commit messages ;) the reason I didn't add it to the docs was because @mbercx was going to do this. Thanks for opening this PR. I will already give some quick comments, but then I let @mbercx say whether he wants to add more to this PR or we merge this and then he can extend the docs in a later separate PR. Note also that the commit message contained quite some details on design choices, for example on the choice of which  plugin to use for the stash folder. This would be ideal to add to the [internal architecture docs](https://aiida-core.readthedocs.io/en/latest/internals/index.html).

**Comment by ramirezfranciscof** [comment]
One thing to consider when improving the stashing docs: from the [current explanation](https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/calculations/usage.html?highlight=stashing#stashing-files-on-the-remote) it is not super clear that you can put folders instead of files (this is not me being nit-picky btw, I have some users ask me for this explicitly).

**Comment by mbercx** [comment]
I actually checked the docs a while back and thought they were ok, forgot to close this issue. Fair point on the folders though, I also didn't think about this. Will open a PR that then also closes this issue.
