### ISSUE TITLE
Docs: Backup Settings are Unclear

### ISSUE THREAD

**Issue by DanielMarchand** [aiidateam/aiida-core#4853]
I'm having some trouble understanding these settings. In particular, `backup_length_threshold`. I thought it was an upper limit for how long the backup is allowed to run, but the 'default' seems to be 1? Maybe it's a setting on how old the file must be before it is considered for backup? 

I would also suggest that perhaps all of these settings just be given a reasonable default value.

**Comment by ramirezfranciscof** [comment]
Hi @DanielMarchand , thanks for the feedback! We are currently working in some changes that may impact how the backup system works, so although we may not act on this right now, we will take your suggestion and try to better document the interface once these modifications are in place!

**Comment by DanielMarchand** [comment]
Hi, @ramirezfranciscof thanks for letting me know! If you want you can ping me here and I can take a look at the new version when it's ready. 

Daniel

**Comment by Irratzo** [comment]
Hi! I recently changed my aiida profile backup setup, perhaps this is useful for you.

As the manual explains, backing up an aiida profile involves three steps:

1. backup the current `/.aiida/config.json`
2. backup the profile's database (psql dump)
3. backup the profile's file repository

For step 3., the manual suggests using `rsync` or the provided aiida backup py script (which uses rsync under the hood). For step 3., I recently switched from this to using [borg](https://borgbackup.readthedocs.io) backup instead. Advantage: aiida file repo gets compressed into a borg repo archive, i.e., smaller and less files. Since `borgmatic` can backup also PostgreSQL databases and such, using `borg` can maybe even be extended to the whole profile backup.
