### ISSUE TITLE
`Repository.hash` seems very inefficient

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#4918]
https://github.com/aiidateam/aiida-core/blob/5f87661e9099b1e8875254df8b133dd43b58c5bc/aiida/repository/repository.py#L96-L110

@giovannipizzi @sphuber Why do we need to read every file and regenerate their hash?
why not just re-use the hashes of the files that are already stored e.g.:

```python
    def hash(self) -> str:
        """Generate a hash of the repository's contents.

        :return: the hash representing the contents of the repository.
        """
        objects = {}
        for root, dirnames, filenames in self.walk():
            objects['__dirnames__'] = dirnames
            for filename in filenames:
                objects[str(root / filename)] = self.get_object(root / filename).key

        return make_hash(objects)

```

**Comment by chrisjsewell** [comment]
I would imagine this is one of the reasons why the new repository implementation and significantly reduced the performance of node storage: 
https://aiidateam.github.io/aiida-core/dev/bench/ubuntu-18.04/django/

<img width="555" alt="image" src="https://user-images.githubusercontent.com/2997570/117233630-c9f07700-ae23-11eb-8526-4e62c123b7fd.png">

**Comment by sphuber** [comment]
True, in the case of the DOS, the key _is_ the hash of the file so we might as well use it. The reason I didn't use this initially is that the `Repository` is backend independent and so the `key` doesn't necessarily have to be the hash of the content. As you can see this is actually also not the case for the `SandboxRepositoryBackend` implementation which just uses a UUID.

Now I can see how this inefficient for our current situation even though "correct". I see two possible solutions:

1) Either we just change the `SandboxRepositoryBackend` to also use the hash as the key, which can be easily done and then we change the `Repository` class to use this, but then we should document that all future implementations, for example a `SwiftRepostioryBackend` should also use the content hash as the key or functionality will probably break.
2) Alternatively, we change the `AbstractRepositoryBackend` interface to add a method that returns the hash of an object and it can then do this in the most efficient way possible for each implementation. For the DOS we can then simply return the key and don't have to compute anything.

If there is no major downside or bottleneck to 2) I would definitely go for that one.

**Comment by giovannipizzi** [comment]
I agree point 2 seems reasonable, with the idea that only some repository backends actually compute hashes (and we can reuse it), and for the others we need to re-compute it.
Note however that we need to document that then we start relying on the hashing algorithm used in the Container backend (and this can be changed). This is probably not an issue here (the hashing is useful only on a per-instance basis), but since it can be changed, one needs to be careful (e.g. if in the future we were to decide to use two different containers to split up files according to some criterion, we would need to ensure that both containers use the same algorithm, otherwise the hash of two nodes with identical files (but stored in different containers using different hashing algorithms) would not match.

For now we can proceed, but I would leave a future-proof comment in the code so we don't forget.

**Comment by sphuber** [comment]
If we agree on the solution, I will happily implement it

**Comment by chrisjsewell** [comment]
no I'm already working on it
