### ISSUE TITLE
append_text not executed if executable not working

### ISSUE THREAD

**Issue by sygout** [aiidateam/aiida-core#5229]
### Describe the bug

We  (@CasperWA and I)  developed a plugin for a software that requires us to copy in the working directory the license file. We want to remove that license file after the calculation so we added that operation in the "append_text" of the code definition. But this operation is not performed if the executable returns an error.
So it seems like a bug but it might actually be the intention of AiiDA team.

### Steps to reproduce

1. Create a plugin with append_text operation
2. Make the executable not working.
3. Check that append_text operations are not performed.

### Expected behavior

append_text operations should be performed even when the executable returns an error.

### Your environment

- Operating system [e.g. Linux]: Ubuntu 20.04 via WSL2
- Python version [e.g. 3.7.1]: 3.7.5
- aiida-core version [e.g. 1.2.1]: 1.6.5

**Comment by sphuber** [comment]
Thanks for the report. This is not necessarily an intentional decision on the behavior. I think it is probably simply a result of the fact that we do not write the submit script such that it captures any errors in the executable call and first run the rest of the script (defined by the `append_text`) before returning the error of the executable call. The thing I don't fully understand is why the script would exit straight away. It should be a bash script and that should continue, even after an error, unless the `set +e` flag is set, which I think is not the case. Could you share the `_aiidasubmit.sh` script in question? You can get it through:
```
verdi calcjob inputcat PK _aiidasubmit.sh
```
where you replace `PK` with the pk of the failed calculation.

I think it should be possible to check the error of a failed executable call and still try to execute the rest of the script, but there is no guarantee that we can do this. For example, the scheduler can kill the script (for a variety of reasons, out-of-walltime, out-of-memory, etc.) and so the code from the `append_text` won't be executed. We can reduce the number of pathways in which this occurs, but it is important to realize that we cannot prevent it. You might want to try and find another approach to your original problem if the data is really sensitive.

**Comment by sygout** [comment]
I get an error message when trying to get the script:

Critical: Could not open output path "_aiidasubmit.sh". Exception: [Errno 2] No such file or directory: '/home/sygo/.aiida/repository/sygo/repository/node/4a/6b/c525-594e-475a-8a5e-485281b26456/raw_input/_aiidasubmit.sh'

It is not really critical for our case.

**Comment by sphuber** [comment]
That's weird. Can you run `verdi calcjob inputls PK` instead to show what it does contain?

**Comment by sygout** [comment]
verdi calcjob inputls return nothing. It seems empty.

**Comment by sygout** [comment]
I checked the wrong calculation node. So here is the content of the _aaidasubmit.sh:
#!/bin/bash
exec > _scheduler-stdout.txt
exec 2> _scheduler-stderr.txt


cp /usr/local/bin/Alsim/ALSIM5.lic .


'/usr/local/bin/Alsim/Alsim_v8_r22.exe' 'template_billet.txt'

echo "$(pwd)" > /home/sygo/aiida/current_location.txt
rm ALSIM5.lic

**Comment by CasperWA** [comment]
Note that when it was run and was successful the files `current_location.txt` was created, revealing that it was indeed in the Node's UUID-sharded working directory where the license (`ALSIM5.lic`) is located - and indeed, for the successful run the file was removed.
But not for the ones where the calculation failed.

I guess one can/should add `set +e` to the prepend text?

**Comment by sphuber** [comment]
That's the thing that I don't understand. The default for bash is to ignore script errors and just continue with the next line. Setting `set -e` changes this default behavior to exit the script as soon as any command returns a non-zero exit code. So in your case, the script should have just continued even if `Alsim_v8_r22.exe` is not found. What machine is this running one? Not where AiiDA is running, but to what type of machine is this submitted to? What OS is it running and what is the bash version? I notice it has an `.exe`. Is there any chance this is Windows?

Also, to prevent any xy-problems: what is the exact use case that you are trying to solve. I gather you have to run a binary through AiiDA that requires some text file with the license to be available in the working directory. Is that the only option? Is it possible to configure some directory where it can be located in the input parameters or something? And if not, does the license have to be removed immediately? If you are running this on a scratch space, it will be cleaned at some point anyway, wouldn't it?

**Comment by sygout** [comment]
Actually the executable is a Linux executable run in Ubuntu inside the WSL.

**Comment by sphuber** [comment]
> It should be possible to (generally) trust that the append text is executed with a similar guarantee level as a finally block in Python is executed.

Not from within the script itself it isn't. As I already mentioned above, nothing can stop the scheduler from killing the script for whatever reason and there is nothing _in the script_ that you can do about this. To absolutely guarantee this operation is executed, you would need a cleaning operation that is executed by AiiDA after the job has finished. This feature does not currently exist, but that is the only way to guarantee the removal of the file will happen.

**Comment by sphuber** [comment]
And by the way, if the file is available on the same filesystem as the working directory of the job, why not just symlink it?

**Comment by CasperWA** [comment]
> And by the way, if the file is available on the same filesystem as the working directory of the job, why not just symlink it?

First thing we tried. The executable is a stubborn one.

**Comment by ltalirz** [comment]
Hey guys, just had a look into the `direct` scheduler plugin and I think I discovered the culprit:

https://github.com/aiidateam/aiida-core/blob/develop/aiida/schedulers/plugins/direct.py#L213

This does indeed enable the `-e` mode inside the script:

```
$ cat test.sh
cat nosuchfile;
echo "hey";

$ bash test.sh
cat: nosuchfile: No such file or directory
hey

$ bash -e test.sh
cat: nosuchfile: No such file or directory
```

In my view this is an inconsistency, since we do not `set -e` on slurm jobs, and I therefore propose to remove this in AiiDA 2.0 (it is a change that can lead to different behavior).

Looking back through the commits, it turns out that this was present already from the beginning, added by Andrea Cepellotti in 2015: https://github.com/aiidateam/aiida-core/blame/c5dfeeaf0a1b0d63eb62d3f25d475620d4bc8e88/aiida/scheduler/plugins/direct.py
Interesting that noone came across this so far.
