### ISSUE TITLE
python API for managing the AiiDA daemon & processes

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#5258]
Much of the utilities for managing the AiiDA daemon & Processes are currently buried in the command line interface.

It would be nice to expose these through the python API.

This feature requests originates e.g. from
https://github.com/microsoft/aiida-dynamic-workflows/blob/main/aiida_dynamic_workflows/control.py

Mentioning @jbweston (in case of further input) and @muhrin (since he signalled interest).

I'll have a look into this later today if I find time

**Comment by ltalirz** [comment]
@jbweston I've now started looking inside the code and I'd just like to clarify a few things before I start making changes to make sure we go in the most useful direction.

1. For your `control.py`, is the "printing" of the cli functions a nuisance or a feature?
I.e. if we now create a python API that will raise if there is an error, and otherwise be silent, will you then need to re-introduce the text output or will you be able to use the API directly?

2. I remember you mentioning some concrete issues you ran into with using the "clickerized" functions, could you share these?

**Comment by jbweston** [comment]
1. As long as the error is semantic (so we can use a fine-grained `except` to catch it) that's fine
2. On the command line you specify numeric IDs or UUIDs to refer to nodes in the DB, but if you `.invoke()` directly you need to have already `orm.load_node`ed the node. Also click constructs a [Context](https://click.palletsprojects.com/en/7.x/complex/) when it is invoked on the command line, and I didn't grok the docs enough to figure out how set that up properly for invoking ad-hoc commands. I also don't know how much click assumes about what the correct error handling behavior is.

**Comment by sphuber** [comment]
I support this feature request. It is indeed not easy to invoke the `click` commands directly from Python and actually directly invoking a subcommand will have unexpected results. For example, the callbacks and automatic type serializations of the command arguments are not automatically applied. We have addressed this with the click developers, but they say this an intentional design choice and won't be changed. We therefore really just need most of the functionality to be directly accessible through the Python API, with the `verdi` CLI just being ultra-thin wrappers.

**Comment by ltalirz** [comment]
@jbweston you may want to have a look at the new API and let us know whether it addresses all your needs
