### ISSUE TITLE
Migration: `core.` prefix is not added correctly for some data types

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-core#5266]
### Describe the bug

During testing, I noticed that after the migration loading any `KpointsData` raised a deprecation warning:

```
In [1]: k = load_node(770)
/home/aiida/envs/aiida-test/code/aiida-core/aiida/plugins/entry_point.py:308: AiidaDeprecationWarning: The entry point `array.kpoints` is deprecated. Please replace it with `core.array.kpoints`.
  warn(
```

This was not an issue for e.g. `StructureData`. It seems that there are some typo's in the SQL commands for the `core.` prefix migration, e.g.:

https://github.com/aiidateam/aiida-core/blob/29915bdb3314dc37171bd264a792b4bbfa6de167/aiida/backends/sqlalchemy/migrations/versions/34a831f4286d_entry_point_core_prefix.py#L27

Note how `KpointData` is missing an `s`. Another faulty migration is the `RemoteStashFolderData` one:

https://github.com/aiidateam/aiida-core/blob/29915bdb3314dc37171bd264a792b4bbfa6de167/aiida/backends/sqlalchemy/migrations/versions/34a831f4286d_entry_point_core_prefix.py#L44

I haven't noticed any others so far. @sphuber if I remember correctly, these migration files are generated via a script. Can we simply correct the SQL commands in the current files or should we regenerate them?

### Steps to reproduce

1. Migrate a database from v1.6.5 to the current `develop` branch.
2. Try loading e.g. any `KpointsData`

**Comment by sphuber** [comment]
Nope, that SQL would be handwritten (by yours truly)
![](https://media.giphy.com/media/vX9WcCiWwUF7G/giphy.gif)

Good that you spotted them, would be good to have someone else also give another thorough scan to see if we can find more errors. Then we can simply update the migration (both backends) and it should be good. Of course databases that have already applied the migration will not work, but since this hasn't been officially released, that should be only on test databases.
