### ISSUE TITLE
`populate_defaults = False` is uneffective when one of the inputs of a namespace is defined

### ISSUE THREAD

**Issue by bosonie** [aiidateam/aiida-core#5286]
### Describe the bug

The `populate_defaults` option can be insert in the the call `expose_inputs` of a `spec` in order to avoid that the defaults of the workchain whose inputs are exposed are set in the current workchain. The expected behavior is not registered, however, when the exposed inputs are in a `namespace` and one of them is set by the user.  

### Steps to reproduce
In verdi shell:

```
from aiida import orm
from aiida.engine import WorkChain, run

class ClassA(WorkChain):
    @classmethod
    def define(cls, spec):
        super().define(spec)
        spec.input("www",valid_type=Float,default=lambda: Float(1.0))
        spec.input("ooo",valid_type=Float,default=lambda: Float(3.0))
        spec.outline(cls.brun)
    def brun(self):
        return None


class ClassB(WorkChain):
    @classmethod
    def define(cls, spec):
        super().define(spec)
        spec.input("ee",valid_type=Float,default=lambda: Float(2.0))
        spec.expose_inputs(ClassA, namespace="qqq", namespace_options={'required': False, 'populate_defaults': False}) 
        spec.outline(cls.run)
    def run(self):
        self.report(self.inputs)

a=ClassB.get_builder
a.qqq.www = Float(2.2)
run(a)
```

The expected behavior would be that  `qqq.www` is set to a value, but `qqq.ooo` remains without any value. However what I see (showed in the report) is that   `qqq.ooo` assumes the default value. This is undesired since 'populate_defaults' is set to False

### Your environment

- Operating system [e.g. Linux]: Ubuntu 16.04
- Python version [e.g. 3.7.1]: 3.7.10
- aiida-core version [e.g. 1.2.1]: 1.6.5 and develop branch

**Comment by sphuber** [comment]
This is the intended behavior though, although I can see that it might not always be expected. The option was explicitly introduced  to prevent defaults from being populated _if and only if_ the namespace was empty. This was done to make it possible for workchains to keep namespaces truly optional and determine whether the process, to whom the exposed inputs belong, should be run or not, based on whether the input namespace was empty. The fact that the defaults are populated as soon as it is no longer empty, was a conscious decision. We could think of another option that has the behavior that you describe though, although I am not sure if that is required, because one can always remove the defaults on the port if they are not desired.
