### ISSUE TITLE
The `serializer` of an aiida processes is not applied to `Data`s. Reconsider the decision?

### ISSUE THREAD

**Issue by bosonie** [aiidateam/aiida-core#5342]
### Is your feature request related to a problem? Please describe

In the `serialize` method of `engine.processes.InputPort` a decision is made to skip the serialization in case the received value is an instance of `orm.Data`. Here the line:
 https://github.com/aiidateam/aiida-core/blob/dce004143043c9f2d41c1b6f82cb037dd642a46d/aiida/engine/processes/ports.py#L88-L89

This is a fair decision if one defines the "serialization" process as the "process that transforms whatever value into an instance or `orm.Data` so that it can be stored as input of a workchain".

However, looking at the more general sense of "serialization" as "the process of translating an object state into a format that can be stored", the choice to limit the application of the serialization function only to non `orm.Data` inputs appears quite limiting.
For instance, one user might want to serialize the content of an `orm.Data`. A practical example would be to serialize the items of an `orm.List` or `orm.Dict` because otherwise they are not storable. In fact, only json-serializable objects are admitted as items of  `orm.List` and `orm.Dict`. This is for sure another type of serialization compared to the simple passing from a python type to a `orm.Data`, but still it is a quite useful feature that is completely admissible by the flexible way the serializers are implemented (developers can define directly the serialization function), but it is prevented by the check in the lines above.
At the moment, a practical solution is to ask users to pass directly a `list` (`dict`) instead of an `orm.List` (`orm.Dict`), but it does not look very aligned with the aiida directives.
 
Therefore the question is what we want to allow in the serialization. We either limit the allowed serialization functions to functions that return a  `orm.Data` from a non  `orm.Data` (current behavior, but must be better documented), or we open up the serialization to other uses. In the latter case the serialization function itself (created by the developers) should take care to cover all the cases ( `orm.Data` in inputs and NON  `orm.Data` in input). For instance the `orm.to_aiida_type` function will need a modification, since now it raises when receiving in input a `orm.Data`.

Another solution is to try to support both the current behavior and my feature request, for instance allowing another argument to the method `serialize` or create another type of serializer alongside the present one. If one wants to go in that direction, the price to pay is that the user must set another keyword in the spec of ports.

**Comment by chrisjsewell** [comment]
Heya, I guess my opening question would be, how do you serialize an `orm.Data` instances that store parts of its data in the repository (i.e. in binary blobs)?
Obviously, it is indeed perfectly possible with base types, like `orm.Dict`/`orm.List`, but I don't feel it is possible more generally

**Comment by sphuber** [comment]
Thanks for the writeup @bosonie . I think I understand what you are trying to accomplish, but I am not sure that is the direction we should go in.

The original idea of the `serializer` keyword for an `InputPort` was indeed merely to simplify turning certain input values of base Python types into their associated `Data` type. Most common example is to have a plain `int`, `str`, `float` or `bool` be automatically converted in an instance of `Int`, `Str`, `Float` and `Bool` respectively. The `to_aiida_type` single dispatch is simply an implementation that automatically adds support for all "base" types that have a `Data` plugin as analog.

The concept was never to allow functions that would convert arbitrary input data and make it "storable". I don't think we should stray away from this definition and so at best should improve the documentation of the `serializer` key and say that this its function.

If there is a problem is design here, isn't it rather that a `List` node can be constructed that is not storable because it contains unserializable content? Ideally this should raise as soon as the node is instantiated or the unsupported element is added. But maybe there a question of performance comes into the picture if you have to serialize the content each time it is modified as opposed to just once when the node is stored.

**Comment by sphuber** [comment]
Just coming back to this issue. I have checked the docs and the current limitation is actually documented: https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/processes/usage.html?highlight=Automatic%20input%20serialization#automatic-input-serialization

I am still not sure that we should remove the restriction. As you say yourself, there is an easy solution for your use case: users just have to pass a non-AiiDA type as input. Given that the content itself is not yet in the form that it should have and is expected to be modified, to me that makes sense. So I am closing this for now. If you have a concrete example that shows that the limitation makes for a much more complicated user interface, feel free to reopen.
