### ISSUE TITLE
Non-unix compatibility

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida-core#56]
Originally reported by: **Giovanni Pizzi (Bitbucket: [pizzi](https://bitbucket.org/pizzi), GitHub: [giovannipizzi](https://github.com/giovannipizzi))**

----------------------------------------

I believe that at the moment the only issue that we have is that we use
os.path
not only for local folders, but also for managing the remote computers (in particular, but probably also in the execmanager and maybe somewhere else). This is ok if both the machine on which we work and the cluster are posix-like.

However, this does not allow AiiDA to work when installed on Windows (for instance). I am pretty sure that this apart from this (and probably the daemon configuration) everything else should work properly in Windows.

Task: replace calls to os.path to os.posixpath (NOT for local files, but for remote files).

Or, EVEN BETTER: define a class-level 'pathmodule' variable, pointing by default to os.posixpath, that gives in the future the possibility to support also remote computers that are not posix-like.

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/56

**Comment by giovannipizzi** [comment]
Not really, the whole daemon uses supervisor (even if it does not appear as 'import supervisor' - e.g. in setup.py there is a full template to create a supervisor input file).

This does not mean we cannot replace it with something else, but I think that supporting windows should not be at this stage a priority (also because I'm pretty sure there are a few things that will need to be improved, like setting file permissions, using os.path.join properly (I think this is now incorrectly done also for the supercomputers, so running AiiDA on windows might be a problem if the supercomputer is linux, etc.). Probably easy to fix all, but requires to setup a set of tests to test windows.
But as claimed above, I would not invest energies at this point on this (of course we can rediscuss).

**Comment by ltalirz** [comment]
Ok, I didn't realise that supervisor is more deeply integrated.
I would still vote to remove this dependency, if it's not too much work (I am happy to help).
This doesn't mean we will support Windows in the near future but at least it makes it possible for someone with enough energy to go through the code, fix the problems and make it work.
conda makes it easy to install AiiDA on Windows and, who knows, there might be such a person.

I don't think it would be wise to block Windows because of this single package.

**Comment by ltalirz** [comment]
Just for reference: After discussing this issue offline, it was agreed to postpone it until a relevant use case for AiiDA on Windows arises, at which point we are happy to reopen it.
