### ISSUE TITLE
numpy.narray size issue raised from pymatgen

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#5767]
Is anyone had the same issue encountered, to be honest, I am a bit sick of dependencies handled by pymatgen I think this is not the first time we have problem with it. 
In AiiDAlab, we pinned the numpy version to workaround this. Now I encounter it again with sssp workflow, not sure tune numpy version is a good idea.

```
  File "/opt/conda/lib/python3.9/site-packages/pymatgen/core/lattice.py", line 22, in <module>
    from pymatgen.util.coord import pbc_shortest_vectors
  File "/opt/conda/lib/python3.9/site-packages/pymatgen/util/coord.py", line 17, in <module>
    from . import coord_cython as cuc
  File "pymatgen/util/coord_cython.pyx", line 1, in init pymatgen.util.coord_cython
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

numpy version `1.21.4`.
pymatgen version `2022.1.9` (I think this pinned by aiida-core)

**Comment by danielhollas** [comment]
@unkcpz perhaps related what I reported here:

https://github.com/aiidalab/aiidalab-docker-stack/issues/320

I think in AiiDAlab this issue is compounded by the fact that aiida-core and its dependencies are installed via conda, but app dependencies are installed via pip, which might lead to these mismatches (but I haven't confirmed this)
