### ISSUE TITLE
Allow user to display meaning of exit status in `verdi process list`

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#5852]
### Is your feature request related to a problem? Please describe

`verdi process list` presents information about why calculations fail:

```
$ verdi process list -a -L PwCalculation
  PK  Created    Process label    Process State     Process status
----  ---------  ---------------  ----------------  ---------------------
 194  21h ago    PwCalculation    ☠ Killed          Killed by parent<186>
 243  20h ago    PwCalculation    ⏹ Finished [410]
 280  20h ago    PwCalculation    ☠ Killed          Killed by parent<263>
 287  20h ago    PwCalculation    ☠ Killed          Killed by parent<282>
 733  18h ago    PwCalculation    ⏹ Finished [0]
 741  18h ago    PwCalculation    ⏹ Finished [400]
 785  16h ago    PwCalculation    ⏹ Finished [0]
 790  16h ago    PwCalculation    ⏹ Finished [312]
 834  16h ago    PwCalculation    ⏹ Finished [340]
 837  16h ago    PwCalculation    ⏹ Finished [0]
 856  13h ago    PwCalculation    ⏹ Finished [305]
 873  13h ago    PwCalculation    ⏹ Finished [0]
 887  12h ago    PwCalculation    ⏹ Finished [305]
 903  12h ago    PwCalculation    ⏹ Finished [305]
```

Some of it is self-explanatory ("Killed"), but the exit codes are not (and they depend on the plugin, so it's not enough to "learn them once").

In order to figure out what they mean, a new user has to go through the reports of the individual calculations.

### Describe the solution you'd like

It would be great if a user could request to print the message associated with the exit status as a last column in `verdi process list`.

@sphuber What do you think?

**Comment by sphuber** [comment]
I think it makes sense, as long as it is an option, since the output can get quite large. Essentially we want to print the `exit_message` attribute. The easiest solution would be to add that key to the `-P/--project` option. The `exit_status` already is, so we can just add `exit_message`. But I can already hear you say that that is maybe not user-friendly enough :sweat_smile: , because a user would have to do something like `verdi process list -a -L PwCalculation -P pk process_state exit_message`. So we might need another stand-alone flag that simply adds this info to the default projections.

**Comment by ltalirz** [comment]
Thanks for the feedback. Adding the `exit_message` sounds like a good first step.
