### ISSUE TITLE
Docs: move info on workers/slots from wiki to main docs

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#5863]
### Describe the current issue

The wiki page https://github.com/aiidateam/aiida-core/wiki/Scaling-of-AiiDA-workers-and-slots is difficult to find and should be moved to the main documentation on performance scaling / troubleshooting

**Comment by sphuber** [comment]
Seems like this is more additional information for the issue that it links of idling processes waiting for subprocesses causing deadlocks. Would it make more sense to just move it there rather than the documentation? Part of the info is outdated and there is no concrete information for the user to address the problem, is there?

**Comment by ltalirz** [comment]
Fine with me!

**Comment by sphuber** [comment]
Done, moved it to #1397
