### ISSUE TITLE
Respect config-file log levels if `-v / --verbosity` option is not set

### ISSUE THREAD

**Issue by astamminger** [aiidateam/aiida-core#5923]
### Describe the bug

In PR #5119 the CLI verbosity behavior was changed such that the verbosity can now also be controlled via the CLI `-v / --verbosity` option passed to any command. In this context the `CLI_LOG_LEVEL` variable was introduced to store and persist the chosen log level between different calls to the `configure_logging()` function. Furthermore, the `REPORT` log level was chosen as the default log level that is used as the default 'CLI verbosity'. 

However, because of this default value the `CLI_LOG_LEVEL`  variable is **always** set. Due to the chosen implementation in the `aiida.common.log` module this results in some severe consequences:
1. any value set for the `aiida` logger and its descendants inside the config will **always** be discarded and overridden by the default `REPORT` log level and can only be controlled by setting the `-v / --verbosity` flag, but never from the config
2. any set of handlers assigned to any logger, before the `CLI_LOG_LEVEL` is processed, is **always**  replaced with the `cli` handler only, thus not a single `aiida` logger output will be logged to the log file, ever

It would be nice if someone could tell me if this is a bug or really the intended behavior!?

### Steps to reproduce

Set the `aiida` log level in the config file to a level different from `REPORT`, for instance `DEBUG`:
```bash
verdi config set logging.aiida_loglevel DEBUG
```
Open a verdi-shell (without the `-v / --verbosity` option) and check the log levels and handlers on the `aiida` logger:
```python
from aiida.common.log import AIIDA_LOGGER
print(AIIDA_LOGGER)
<Logger aiida (REPORT)>
print(AIIDA_LOGGER.handlers)
[<CliHandler (NOTSET)>, <DBLogHandler (DEBUG)>]
```
Log level is decreased to the default CLI `REPORT` loglevel, console and any other handlers is gone and replaced with CLI handler (`DBLogHandler` is available from the handler list only because it is set **after** `CLI_LOG_LEVEL` is processed) 

Alternatively, you could also set `aiida_loglevel` to `DEBUG` comment out the following code
https://github.com/aiidateam/aiida-core/blob/68cc06277b17d5895cacba43c391069abdb2de92/aiida/common/log.py#L207-L209
submit a calculation and watch your log file being flooded with logs

### Expected behavior

The log level defined in the config file should only be overridden and redirected to CLI, if the log level is explicitly set from the CLI, i.e. by explicitly passing a log level to the command via the `-v / --verbosity` flag. However, if this flag is not defined, there's IMHO no intent to redirect the logs to the command line and the default values set in the config should be respected.

### Your environment

- Operating system [e.g. Linux]: Linux 
- Python version [e.g. 3.7.1]: 3.8.15
- aiida-core version [e.g. 1.2.1]: main

**Comment by sphuber** [comment]
Thanks for the report @astamminger . I had noticed myself as well that the `DbLogHandler` was being overridden when going through the CLI. For example, when submitting a calculation through the CLI that uses the `VerbosityOption`, the log messages no longer are stored in the database as `Log` entries attached to the `ProcessNode`. This is definitely a bug I would say and we should fix it.

> The log level defined in the config file should only be overridden and redirected to CLI, if the log level is explicitly set from the CLI, i.e. by explicitly passing a log level to the command via the -v / --verbosity flag. However, if this flag is not defined, there's IMHO no intent to redirect the logs to the command line and the default values set in the config should be respected.

Here I am not sure if I fully agree. I _do_ agree that the log level specified in the config should probably be respected by the verbosity option. However, I don't think that if the option is not specified whatsoever, that no logging whatsoever should be redirected to stdout. Or maybe put differently, would you expect to see _any_ output from a CLI command if `-v` is not explicitly specified? Seems to be counter intuitive to me.

Did I understand your expected behavior correctly? I.e., what I would propose is:

* Respect the log levels specified in the config, unless explicitly overridden by `--verbosity`
* Do not remove handlers when the `--verbosity` option is used, but simply _add_ the `CliHandler`.

**Comment by sphuber** [comment]
> Agreed. However, for some reason (maybe due to the click handling of callbacks?) the defined default value on the click option will always set the CLI_LOG_LEVEL, thus, always triggering the override (even if it was not set by the user upon command invocation)

That is because the option is attached to all commands, and it specified the `default`, which means its callback `set_log_level` is always called.

> Well, it does not do any harm to log to the console when asked for and to the log file. So I would be positive on that one as well.

Actually, what I suggested is incorrect: the file handlers are _not_ removed when the `CLI_LOG_LEVEL` is set, they are simply never defined by default. They _are_ enabled when `configure_logging` is called with `daemon=True`. This is done by the daemon process. This was also the main purpose of the log file: for the daemon workers to log to. I am actually curious why you would expect logging that is emitted because a CLI command is invoked to also end up in the log file, if it already is shown on the console? If you want to write it to file, why not simply redirect the stdout/stderr to the file desired? In any case, I personally would not expect to have logs emitted during a `verdi` call to also end up in the daemon log file.

Maybe I should explain the main reason for the current design. Before the changes of #5119 the handling of verbosity was not handled generically but was left up to each command. Certain commands had options like `--silent` (to suppress all output) or something like `--verbose` to increase logging verbosity. The problem was that sometimes this applied to the output of the command itself, but sometimes to API code _called_ by the command. This lack of consistency made it difficult to maintain but also to use `verdi`. The goal was to have a single option to reliably control the verbosity of all output to the console when using `verdi`. Important point was that the solution did not just affect the output of the commands itself, but any logging of the API code it might call. There is no point in allowing a user to specify `--verbosity WARNING` and then have the API code just log debug messages. Does this behavior make sense to you? Because if you agree, then it is just a question of fixing the implementation to achieve it.

> What I still don't get though: What exactly is the purpose of the CliHandler?

It allows the use of custom attributes in log records to impact the formatting, such as omitting the newline. This was necessary to basically pipe the `aiida.cmdline.utils.echo` methods through the logging system, while keeping the various additional formatting options of `click.echo` which we use to style the output.

One final point as to why we decided to set `REPORT` as the default log level when invoking a `verdi` command. We originally considered indeed getting this value from the `logging.aiida_loglevel` config setting. However, we thought this could have intuitive consequences for users. It is very much possible that at some time (maybe even long ago) the user set `logging.aiida_loglevel` to `WARNING` because they were getting too much logging in their daemon log file. Once they would have the new version of AiiDA, all of a sudden the majority of their `verdi` commands no longer report any output, since the output of commands is now tied to the logging system and this log level setting, and most normal messages are output at `REPORT` level.

Should we maybe introduce a new config option `logging.verdi_loglevel` which defaults to `REPORT` and use that for all messages logged directly by CLI commands, and keep `logging.aiida_loglevel` for all other Python API code? Should the `--verbosity` option then override both levels, if and only if explicitly specified? Would that work?

**Comment by astamminger** [comment]
Hi @sphuber,

>  I am actually curious why you would expect logging that is emitted because a CLI command is invoked to also end up in the log file, if it already is shown on the console? 

Nevermind, that was a misunderstanding on my side :)

> Important point was that the solution did not just affect the output of the commands itself, but any logging of the API code it might call. There is no point in allowing a user to specify `--verbosity WARNING` and then have the API code just log debug messages. Does this behavior make sense to you?

I guess, when thinking about the problem I simply separated `verdi` and `AiiDA` into two distinct entities in my head too much, although I actually should have treated them as a single entity. So, yeah, in retrospective that line of thought makes more sense now.

> It allows the use of custom attributes in log records to impact the formatting, such as omitting the newline. This was necessary to basically pipe the `aiida.cmdline.utils.echo` methods through the logging system, while keeping the various additional formatting options of `click.echo` which we use to style the output.

Ok, so basically some kind of console logger on steroids , thanks for the clarification!

> Should we maybe introduce a new config option logging.verdi_loglevel which defaults to REPORT and use that for all messages logged directly by CLI commands, and keep logging.aiida_loglevel for all other Python API code? Should the --verbosity option then override both levels, if and only if explicitly specified? Would that work?

Actually no, the implementation you already did in #5925 seems to be sufficient to fix my problem (see also my comment over in the PR)

Thanks!
