### ISSUE TITLE
syntax for filters with `verdi calcjob res` doesn't match documentation

### ISSUE THREAD

**Issue by mkotiuga** [aiidateam/aiida-core#5932]
When filtering the results of a calcjob with the cli the  documentation says to use the keys before the CALCJOB node:
```
$>verdi calcjob res --help
Usage: verdi calcjob res [OPTIONS] [--] CALCJOB

  Print data from the result output Dict node of a calcjob.

Options:
  -k, --keys TEXT...              Filter the output by one or more keys.
  -f, --format [json+date|yaml|yaml_expanded]
                                  The format of the output data.
  -v, --verbosity [notset|debug|info|report|warning|error|critical]
                                  Set the verbosity of the output.
  --help                          Show this message and exit.
```
but one has to put the CALCJOB first, otherwise:
```
$> verdi calcjob res -k energy 1937549 
Usage: verdi calcjob res [OPTIONS] [--] CALCJOB
Try 'verdi calcjob res --help' for help.

Error: Missing argument 'CALCJOB'.
```
The following works:
```
 verdi calcjob res 1937549 -k "energy" 
{
    "energy": -31498.786230468
}
```

Using AiiDA version 2.1.2, python 3.8  on Ubuntu

**Comment by sphuber** [comment]
The documentation is not really incorrect. The problem is just that the `-k` option takes _one or more_ values and so it is "greedy". In your first example, it interpreted the pk of the calcjob as another value for the `-k` option. This is a known problem of command line argument parsing. The standard (POSIX) approach is to add the `--` option, which is the `ENDPOTS` marker. This signals the parser that there are no more options, and everything that follows are positional arguments.

The `verdi` command also implements this, see the `[--]` marker in the usage string. See here for explanation in the documentation: https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/cli.html#multi-value-options

So the solution is to use:
```
verdi calcjob res -k energy -- 1937549
```
This pattern is part of many `verdi` commands. Anytime a command has an option that takes multiple values, the `[--]` marker is automatically added in the usage string. I agree that this is not the most intuitive thing, but we have looked into this in detail, and I am afraid there is no better solution available.
