### ISSUE TITLE
Problem during aiida-lsmo installation: MissingEntryPointError and problem when reconnecting to conda environment

### ISSUE THREAD

**Issue by vincentdufourdecieux** [aiidateam/aiida-core#5938]
- [ ] [AiiDA Troubleshooting Documentation](https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/troubleshooting.html)
- [x] #5943

### Describe the bug

I am trying to install aiida-lsmo and I follow the steps on this link (https://github.com/lsmo-epfl/aiida-lsmo-setup) with a few differences. I use the install_editable.txt attached here. Before 'verdi quicksetup', I run 'verdi config downgrade 5' and 'pip install aiida-core==1.6.7' because otherwise I run in some compatibility problems. I use localhost_setup.txt, raspa@localhost.txt and zeopp@localhost.txt attached here for the 'verdi computer setup' and 'verdi code setup' instead of the configure.py mentioned in the link. 

Once I arrive at step 8 of the link sent above, I run 'verdi run run_IsothermWorkChain_HKUST-1.py raspa@localhost zeopp@localhost' and I obtain the following error: 

verdi run run_IsothermWorkChain_HKUST-1.py raspa@localhost zeopp@localhost
Traceback (most recent call last):
  File "/home/vdufour/.conda/envs/aiida1/bin/verdi", line 8, in <module>
    sys.exit(verdi())
  File "/home/vdufour/.conda/envs/aiida1/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/vdufour/.conda/envs/aiida1/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/vdufour/.conda/envs/aiida1/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vdufour/.conda/envs/aiida1/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vdufour/.conda/envs/aiida1/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/vdufour/.conda/envs/aiida1/lib/python3.9/site-packages/aiida/cmdline/utils/decorators.py", line 74, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/vdufour/.conda/envs/aiida1/lib/python3.9/site-packages/aiida/cmdline/commands/cmd_run.py", line 147, in run
    exec(compile(handle.read(), scriptname, 'exec', dont_inherit=True), globals_dict)  # yapf: disable # pylint: disable=exec-used
  File "run_IsothermWorkChain_HKUST-1.py", line 14, in <module>
    IsothermWorkChain = WorkflowFactory('lsmo.isotherm')  # pylint: disable=invalid-name
  File "/home/vdufour/.conda/envs/aiida1/lib/python3.9/site-packages/aiida/plugins/factories.py", line 216, in WorkflowFactory
    entry_point = BaseFactory(entry_point_group, entry_point_name)
  File "/home/vdufour/.conda/envs/aiida1/lib/python3.9/site-packages/aiida/plugins/factories.py", line 46, in BaseFactory
    return load_entry_point(group, name)
  File "/home/vdufour/.conda/envs/aiida1/lib/python3.9/site-packages/aiida/plugins/entry_point.py", line 206, in load_entry_point
    entry_point = get_entry_point(group, name)
  File "/home/vdufour/.conda/envs/aiida1/lib/python3.9/site-packages/aiida/plugins/entry_point.py", line 266, in get_entry_point
    raise MissingEntryPointError(
aiida.common.exceptions.MissingEntryPointError: Entry point 'lsmo.isotherm' not found in group 'aiida.workflows'. Try running `reentry scan` to update the entry point cache.

In addition, if I deactivate the conda environment and come back later, I cannot run a 'verdi' command as it gives me every time:

 verdi status
Critical: Validation Error: /home/vdufour/.aiida/config.json:/profiles/vdufour/AIIDADB_BACKEND: 'psql_dos' is not one of ['django', 'sqlalchemy']
  schema:
  {'type': 'string', 'enum': ['django', 'sqlalchemy'], 'default': 'django'}

### Expected behavior

I would expect to be able to run 'verdi run run_IsothermWorkChain_HKUST-1.py raspa@localhost zeopp@localhost' and obtain  the output given here: https://aiida-lsmo.readthedocs.io/en/latest/get_started.html.

I would expect to be able to run verdi command after reactivating the aiida1 environment.

### Your environment

- Operating system [e.g. Linux]: Linux
- Python version [e.g. 3.7.1]: 3.9
- aiida-core version [e.g. 1.2.1]: 1.6.7

Other relevant software versions, e.g. Postres & RabbitMQ

### Additional context
[localhost_setup.txt](https://github.com/aiidateam/aiida-core/files/11026361/localhost_setup.txt)
[raspa@localhost.txt](https://github.com/aiidateam/aiida-core/files/11026362/raspa%40localhost.txt)
[zeopp@localhost.txt](https://github.com/aiidateam/aiida-core/files/11026363/zeopp%40localhost.txt)
[install_editable.txt](https://github.com/aiidateam/aiida-core/files/11026364/install_editable.txt)

I am happy to give more information if needed !
Thank you in advance for your help !
Vincent

**Comment by sphuber** [comment]
As the first error message indicates, after you run `pip install aiida-core==1.6.7` you need to run `reentry scan` to make sure the entry points are properly registered. This is still necessary for AiiDA before v2.0.

Then for the second error is because the config file is invalid. You should open the file `/home/vdufour/.aiida/config.json` and find the key `AIIDADB_BACKEND` and change that to `sqlalchemy`. Here I am assuming that you run `verdi quicksetup` _before_ you installed `aiida-core==1.6.7`. If the case though, I think the database that was created will be incompatible, so even when you fix this, there will be a problem connecting.

The real problem is that the [install script](https://github.com/lsmo-epfl/aiida-lsmo-setup/blob/master/install_editable.sh) seems to be installing the `main` branch of `aiida-core`, which is currently at v2.2.2, but then all the plugins require v1.6. This script should really be fixed to simply install the required aiida-core version from PyPI using `pip install aiida-core==1.6`. Then you won't need to downgrade the config and there shouldn't any issues that you encountered.

**Comment by sphuber** [comment]
> So I changed AIIDADB_BACKEND to sqlalchemy and I can run verdi status now but i obtain : '✘ postgres: Database schema version is incompatible with the code: run verdi database migrate. I did 'verdi quicksetup' after 'pip install aiida-core==1.6.7'. I am not sure to understand what it changes

This is exactly the problem I predicted in my previous post. The database that was created by `verdi quicksetup` was created with AiiDA v2 and this can never be used with v1.6 since there are no downgrade possible. You should simply delete this database.

Then, you can follow the following steps:

#. Run `pip install aiida-core==1.6.9`.
#. Make sure you have the correct version by running `pip freeze | grep aiida-core`
#. Run `reentry scan`
#. Run `verdi plugin list aiida.calculations` and make sure the plugins you expect are listed (this means the `reentry scan` worked)
#. Remove the old `config.json` which is probably in the `~/.aiida` folder (Note, I am assuming the only profile is the broken one created with `verdi quicksetup`. If you have other profiles that need to be kept, make a backup first)
#. Now run `verdi quicksetup` and create a profile with database that should be compatible with v1.6.9

**Comment by sphuber** [comment]
Closing this for now. Feel free to reopen if you are still experiencing issues
