### ISSUE TITLE
calcjob hash is not stable

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#5997]
- [x] [AiiDA Troubleshooting Documentation](https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/troubleshooting.html)
- [x] [AiiDA Users Forum](https://groups.google.com/forum/#!forum/aiidausers)

### Describe the bug

The `_aiida_hash` in extras is not equal to `node.get_hash()`. 

I just encounter this and think this should never happen. I don't know how to further debug. It may be worth to check together with https://github.com/aiidateam/aiida-core/issues/2000

### Your environment
- aiida-core version [e.g. 2.3.0]:

**Comment by unkcpz** [comment]
I find the open PR https://github.com/aiidateam/aiida-core/pull/5840, @sphuber is the hash of calcjob already updated based on the remote folder content? If so the behaviour of the issue is explainable.

**Comment by sphuber** [comment]
Is the node stored when you call `node.get_hash()`?

**Comment by unkcpz** [comment]
> Is the node stored when you call node.get_hash()?

Yes, I run this after the calcjob is stored, directly call function from verdi shell after the calcjob is finished.

**Comment by sphuber** [comment]
Can you reliably reproduce it? Please try to make a minimally working example, otherwise it will be impossible to debug.

**Comment by unkcpz** [comment]
Okay, I run a minimal `PwBaseWorkChain` twice with caching on, the hash of the source calcjob is not the same with the cached calcjob. 

This is the status of the workchain node and the extras of calcjob:

```
╰─○ verdi process status 369967
PwBaseWorkChain<369967> Finished [0] [3:results]
    ├── create_kpoints_from_distance<369969> Finished [0]
    └── PwCalculation<369973> Finished [0]
(aiida-sssp-unstable) ╭─jyu at mpc3086 in ~
╰─○ verdi node extras 369973
PK: 369973
{
    "_aiida_cached_from": "b6e21c67-e87c-4e61-9e8d-11f46bbbfc20",
    "_aiida_hash": "a568645d2683e8ec7b08b70850cbf734f7c96c5d0a3194a864ca1cff78894541"
}
(aiida-sssp-unstable) ╭─jyu at mpc3086 in ~
╰─○ verdi node extras b6e21c67-e87c-4e61-9e8d-11f46bbbfc20
PK: 369959
{
    "_aiida_hash": "1ca9c13b01afdda8c5ee148d9d753dbb7533805f44e1f858ae56022e6e6ab6ec"
}
```

When I check the call `get_hash` for the node `b6e21c67-e87c-4e61-9e8d-11f46bbbfc20` above, it is not equal to its `_aiida_hash`.

**Comment by unkcpz** [comment]
I think I narrow down the issue to it is comes from the `_get_objects_to_hash()` is changed before and after the calcjob is finished, 

```
['2.3.0',
 {'version': {'core': '2.3.0', 'plugin': '4.3.0'},
  'withmpi': True,
  'resources': {'num_machines': 1, 'num_mpiprocs_per_machine': 2},
  'append_text': '',
  'parser_name': 'quantumespresso.pw',
  'prepend_text': '',
  'input_filename': 'aiida.in',
  'metadata_inputs': {'metadata': {'dry_run': False,
    'options': {'withmpi': True,
     'resources': {'num_machines': 1, 'num_mpiprocs_per_machine': 2},
     'append_text': '',
     'parser_name': 'quantumespresso.pw',
     'prepend_text': '',
     'input_filename': 'aiida.in',
     'output_filename': 'aiida.out',
     'scheduler_stderr': '_scheduler-stderr.txt',
     'scheduler_stdout': '_scheduler-stdout.txt',
     'mpirun_extra_params': [],
     'max_wallclock_seconds': 1800,
     'import_sys_environment': True,
     'submit_script_filename': '_aiidasubmit.sh',
     'custom_scheduler_commands': '',
     'environment_variables_double_quotes': False},
    'call_link_label': 'iteration_01',
    'store_provenance': True}},
  'output_filename': 'aiida.out',
  'scheduler_stderr': '_scheduler-stderr.txt',
  'scheduler_stdout': '_scheduler-stdout.txt',
  'mpirun_extra_params': [],
  'environment_variables': {},
  'import_sys_environment': True,
  'submit_script_filename': '_aiidasubmit.sh',
  'custom_scheduler_commands': '',
  'environment_variables_double_quotes': False},
 '8e0c9283b9309db95740a406e673a85f26b2acb427cd6ad1df5cebd8fd51d23e',   <----- this is the info changed before and after the calculation is done
 '2ce04e48-97c9-4609-a6e6-601e252642c3',
 {'code': '522c24f36dff0e1b0510635ec4871e3041a23be2cd0308226b217ed3ad66536f',
  'structure': '34cde544a3a2e8b774aa83e31e5c076dffd38fd9c4f439168d29c9553bd93485',
  'parameters': 'cf00f54baf680dc3114db69ff545e83e23350730aee20251dfd9006460730a63',
  'pseudos__H': '87dab28bd90c8dfdf5dd0d97dee8860d249dd9d533d2e3b4aa752f6c4d9803e2',
  'parallelization': '8405c275684ee68eb77790d5b42f3babc11ad7458260bf76c8802f2697715f3e',
  'settings': '020f679e7567db5854f9c997458db8dac392120d2b4509aa05111a441ef568f0',
  'kpoints': '7e7293731c39770591e6836e8a194a3eea56927811422677ad6472996f373440'}]
```.

**Comment by sphuber** [comment]
Is that the hash of the repository? And you are saying that is changing as soon as the `CalcJob` finishes? Would be interesting to copy the contents of the repository while it is running (and compute the hash) and then once the calculation is done. We can then manually inspect the files. There must be some files changed, but I cannot see which. The files in the repository of the `CalcJobNode` are the input files that are generated by the plugin, and should not be updated after the node is stored.

**Comment by sphuber** [comment]
I can confirm this bug. It has existed as early as `v2.1` and probably even before. The problem is the following.

* The hash is computed when the `CalcJobNode` is stored. At this point, the repository is empty, and so its hash is computed based on the dictionary `{'__dirnames__': []}`. This hash is stored in the `_aiida_hash` extra.
* The input files are written to the repository of the `CalcJobNode` in the `upload_calculation` step. At this point, since the repository now contains files, its hash is different, and so `node.get_hash()` will also be different.

I am pretty sure that this inconsistency should not affect the caching functionality, since when a `CalcJobNode` is stored and so it checks the cache, it checks the database for matches of _its_ hash, which at that point _also_ doesn't contain any input files. The inputs are already included in the hash directly by computing the hash of each input node. The input files are essentially just a derivative of those input nodes, created by the `CalcJob` plugin, so we don't really _need_ to consider the input files.

I see two potential solutions to this:

1. Make sure that the input files are written to the `CalcJobNode`'s repository _before_ the hash is computed.
2. Simply exclude the repository hash for `CalcJobNode`'s

I would definitely favor option 2. Number 1 will probably very difficult and require a lot of refactoring. I am not even sure it is possible. Currently, before we can even go to the upload step, the node _has_ to be stored.

Option 2 would be quite straightforward, and it also makes sense. Since the repository merely contains files that are a _derivative_ of the input nodes, by including the version of the `CalcJob` plugin and the hash of the actual input nodes, all the necessary information is included in the hash.

**Comment by sphuber** [comment]
🤦 Well looky here:

https://github.com/aiidateam/aiida-core/blob/9e5f5eefd0cd6be44f0be76efae157dcf6e160ed/aiida/orm/nodes/process/calculation/calcjob.py#L35--L62

Seems I already thought of this, but in a refactor, the subclass was not actually used. Will push a fix soon.

Think this may officially require a database migration to rehash all the `CalcJobNode` hashes....
