### ISSUE TITLE
Consider raising an error or issuing warning when caching rule does not match known class

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#6064]
I would regard this as a feature request because I know how to workaround it by setting caching turned on globally for all calculations. In my case, the calcjob process class is not loaded from entry_point but from the class name by the function `load_object` so it can dynamically load different functions to my workflow. 
The calcjob class is loaded by `evaluate_process = load_object(self.inputs.evaluate_process.value)` and the `evaluate_process` then is used as normal calcjob or workchain process and I run it by `node = self.submit(self.ctx.evaluate_process, **inputs)`

```python
def load_object(cls_name):
    """
    Loads the process from the serialized string.
    """
    if isinstance(cls_name, orm.Str):
        cls_name_str = cls_name.value
    else:
        cls_name_str = str(cls_name)
    try:
        return ObjectLoader().load_object(cls_name_str)
    except ValueError as err:
        if cls_name_str.startswith(_YAML_IDENTIFIER):
            return yaml.load(cls_name_str[len(_YAML_IDENTIFIER):])
        raise ValueError(f"Could not load class name '{cls_name_str}'.") from err
```

The calcjob is registred to entry point `opsp.pseudo.oncv`, and the caching for it is turned on. But the caching is not working. If the caching is turned on globally, the cached node is used and everything is fine. I guess the reason is function https://github.com/aiidateam/aiida-core/blob/cb8af9f3d52f887260c52f99aa429d18db2d8f75/aiida/manage/caching.py#L139C1-L147 only check the entry_points so when the process is instantiated with class directly it will not activate. @sphuber am I correct?

It would be useful if the class can be deducted from the entry_point and directly apply to the process that is instantiated from the class directly.

**Comment by sphuber** [comment]
I am not sure that the analysis is a 100% correct. Whether the cache is used for a node when being stored is indeed determined by `get_use_cache`, however, it passes the `process_type` of the `Node`: https://github.com/aiidateam/aiida-core/blob/cb8af9f3d52f887260c52f99aa429d18db2d8f75/aiida/orm/nodes/node.py#L453
The process type is a string that can take multiple forms. If the class has an associated entry point, then it uses that. If not, it falls back on the absolute module path to the class name.

Example: consider we have the class `aiida_plugin.module.SomeCalcJob`. If it is not registered with an entry point, the process type will be `aiida_plugin.module.SomeCalcJob`. If it has entry point `some.entry_point` the `process_type` will be `aiida.calculations:some.entry_point`. See here for the code:
https://github.com/aiidateam/aiida-core/blob/cb8af9f3d52f887260c52f99aa429d18db2d8f75/aiida/engine/processes/process.py#L565

Now if you look at the implementation of `get_use_cache` nowhere does it limit that only entry points are matched. If you add a rule to enable caching for `aiida_plugin.module.SomeCalcJob`, it should cache those, even without an entry point.

So I have the feeling something else is going on in your case. I would call `load_node()._get_objects_to_hash()` on the node that you think should have been cached and the expected cache source and look for differences. My bet is that the hash actually isn't the same and that is why it is not being cached.

Also, if you are registering your `evaluate_process`es with an entry point, why don't you just use those entry points for the `evaluate_process` input and use the `aiida.plugins.load_entry_point` method to load the corresponding class instead of the custom `load_object`.

**Comment by unkcpz** [comment]
> why don't you just use those entry points for the evaluate_process input and use the aiida.plugins.load_entry_point method to load the corresponding class instead of the custom load_object.

Thanks for the advice, I have other evaluated classes that are not registred as entry_points, and I want to make my workchain more generic that can accept a class. But I think you are correct, I can add a condition if it is an entry_point I use `load_entry_point` or use load_object if it is a class. 

> I would call load_node()._get_objects_to_hash() on the node that you think should have been cached and the expected cache source and look for differences.

I checked the hash is exactly the same. Moreover, as I mentioned when I turn on the caching globally, the caching is working! 

>  If you add a rule to enable caching for aiida_plugin.module.SomeCalcJob

I guess I need to do it explicitly through code? I turn on the caching for entry_point by `verdi config set -r caching.enabled_for`.

**Comment by sphuber** [comment]
Are you running on v2.4? Remember we fixed an issue with the caching there right. Also, what is the `process_type` of one of those nodes? Do `load_node().process_type`.

**Comment by unkcpz** [comment]
I find where the problem came from. It was my carelessness that I set the caching for the class by `verdi config -a caching.enabled_for opsp.pseudo.oncv`, it should be `verdi config -a caching.enabled_for aiida.calculations:opsp.pseudo.oncv`. Maybe it is fair to check the target for caching is exist and can be loaded by run `get_use_cache` to the input of `enabled_for` and raising some warnings.

**Comment by sphuber** [comment]
There is already a validation function for this:
https://github.com/aiidateam/aiida-core/blob/cb8af9f3d52f887260c52f99aa429d18db2d8f75/aiida/manage/caching.py#L204

We should just make sure that it is called by the `verdi config set` functionality.
