### ISSUE TITLE
possible hints for packaging improvements

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#6084]
just came across repo review

https://learn.scientific-python.org/development/guides/repo-review/?repo=aiidateam%2Faiida-core&branch=main

(not urgent)

**Comment by sphuber** [comment]
Results with items that it flagged below:

[ ]: **[PY007](https://learn.scientific-python.org/development/guides/tasks#PY007): Supports an easy task runner (nox or tox)**: This seems to be a bug because we actually _do_ have tox config, it is just in `pyproject.toml`
[ ]: **[PP304](https://learn.scientific-python.org/development/guides/pytest#PP304): Sets the log level in pytest**:
[ ]: **[PP305](https://learn.scientific-python.org/development/guides/pytest#PP305): Specifies xfail_strict**:
[ ]: **[PP306](https://learn.scientific-python.org/development/guides/pytest#PP306): Specifies strict config**:
- [ ]: **[PP307](https://learn.scientific-python.org/development/guides/pytest#PP307): Specifies strict markers**:
- [ ]: **[PP308](https://learn.scientific-python.org/development/guides/pytest#PP308): Specifies useful pytest summary**:
- [ ]: **[GH200](https://learn.scientific-python.org/development/guides/gha-basic#GH200): Maintained by Dependabot**: We update dependencies in static requirements files for each supported Python version, once before every release.
- [ ]: **[PC110](https://learn.scientific-python.org/development/guides/style#PC110): Uses black**: Not applicable since we use `yapf`
- [ ]: **[PC140](https://learn.scientific-python.org/development/guides/style#PC140): Uses mypy**: Another bug as we _do_ use `mypy`
- [ ]: **[PC160](https://learn.scientific-python.org/development/guides/style#PC160): Uses codespell**:
- [ ]: **[PC170](https://learn.scientific-python.org/development/guides/style#PC170): Uses PyGrep hooks (only needed if RST present)**:
- [ ]: **[PC180](https://learn.scientific-python.org/development/guides/style#PC180): Uses prettier**: Not applicable since we use `yapf`
- [ ]: **[PC190](https://learn.scientific-python.org/development/guides/style#PC190): Uses Ruff**: Not applicable since we use `pylint`
- [ ]: **[PC901](https://learn.scientific-python.org/development/guides/style#PC901): Custom pre-commit CI message**:
- [ ]: **[MY103](https://learn.scientific-python.org/development/guides/style#MY103): MyPy warn unreachable**:
- [ ]: **[MY104](https://learn.scientific-python.org/development/guides/style#MY104): MyPy enables ignore-without-code**:
- [ ]: **[MY105](https://learn.scientific-python.org/development/guides/style#MY105): MyPy enables redundant-expr**:
- [ ]: **[MY106](https://learn.scientific-python.org/development/guides/style#MY106): MyPy enables truthy-bool**:

**Comment by chrisjsewell** [comment]
> Uses black: Not applicable since we use yapf

Yeh but black is better 😏

> but it doesn't have the same coverage as pylint
> I know that at least @chrisjsewell would be a proponent of the switch.

Yeh mainly I have switched all my repos to ruff.
Indeed pylint checks more, but I feel this is because it covers both linting and type checking, which these days can be covered separately by ruff and mypy (assuming you use strict type checking, which we are gradually moving towards)

For sure it would at least be a lot quicker!
