### ISSUE TITLE
CalcJob has exit_status=0 but missing required output node

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#6100]
I have a `PwCalculation` that has the state `Finished [0]` but even don't have `output_parameters` which is required. 

After some analysis, I more or less narrowed down the issue to the caching (yes, the beloved caching again :smile_cat: ) 

This problematic node let's label it as `PW-C` is cached from `PW-B` (health) which is cached from `PW-A` (health). 
In the function `_store_from_cache` the `self._add_outputs_from_cache` is happened after `self._store`, which means before all the outgoing nodes are set from `PW-A` to `PW-B`, the `PW-B` is a valid caching source and it used by `PW-C` which cause the issue. 

I don't know if we can swap two lines? I guess not, the node cannot be used as incoming before it is stored. 

https://github.com/aiidateam/aiida-core/blob/9bde86ec7700b3dd2df55c69fb8efb9887ed07d6/aiida/orm/nodes/node.py#L528-L529

Then the only solution I can think of is to disable the caching in extras and enable it after all the outgoing nodes are properly set.

**Comment by sphuber** [comment]
I think there is another potentially better solution. Just before the lines you link, all attributes are copied, _except_ for the `sealed` attribute. This is left to the rest of the engine code that will finish the process like normal and when the process terminates, the node is sealed. So I think we can just update the `is_valid_cache` condition to include that for `ProcessNode`s it should be sealed.

**Comment by unkcpz** [comment]
> Just before the lines you link, all attributes are copied, except for the sealed attribute.

But then when to copy the sealed attributes? I assue nearly in this case all the attributes (inputs nodes) are sealed? 

> So I think we can just update the is_valid_cache condition to include that for ProcessNodes it should be sealed.

The result of `is_valide_cache` is the combination of node exit_code state and `_aiida_valid_cache`. The `_aiida_valide_cache` is not set in extras as default. That means by default all the finished process are vaild cached which means no update from the invalid cache to valid cache.

**Comment by sphuber** [comment]
> But then when to copy the sealed attributes? I assue nearly in this case all the attributes (inputs nodes) are sealed?

I am not suggesting to change those lines, I was just pointing them out that when a node is being stored by copying from the cache, all the attributes are copied over _except_ for the sealed attribute. This is for a good reason, because the actual `Process` is still active when this `ProcessNode` is being stored. After the store is done, the process will continue and wrap up, eventually sealing the node. That is why it is not copied over here.

> The result of is_valide_cache is the combination of node exit_code state and _aiida_valid_cache. The _aiida_valide_cache is not set in extras as default. That means by default all the finished process are vaild cached which means no update from the invalid cache to valid cache.

This is my point though, we should update `is_valid_cache` to _also_ consider unsealed nodes as invalid.

The bug that you seem to have found is due to the fact that a node that is not yet sealed (and so doesn't yet have its output nodes attached yet) is still considered a valid cache source. I am saying that if add the node being sealed as a requirement for it being a valid cache source, I am pretty sure that the problem should be fixed.
