### ISSUE TITLE
verdi setup causes a silent failure downstream if no email is set

### ISSUE THREAD

**Issue by ljbeal** [aiidateam/aiida-core#6164]
Simple bug to reproduce, though this was done on a new install which might be required to create actual _breaking_ behaviour.

Using a fresh aiida-core 2.4.0 install: 

After [manually setting up](https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/installation.html#creating-the-database) the psql database, `verdi setup` but make sure to set no value using `!` for email 
(possibly also name is required to be None, since that is a part of the `user`)

Now the created profile is listed in `verdi profile list`, however no user was created.

Verifiable by checking the user list, but also any database operations appear to fail:
Setting up a Computer gives a non-obvious `AttributeError: 'NoneType' object has no attribute 'pk'` error
However verdi shell tests with orm loaded give a more sensible `user cannot be None` error

**Comment by sphuber** [comment]
Thanks for the report @ljbeal I think this bug was already fixed in https://github.com/aiidateam/aiida-core/commit/c53ea20a497f66bc88f68d0603cf9a32614fc4c2  It is slated for release soon with v2.5. If you want, you could try to checkout the `main` branch and try again. Pretty sure now it will no longer accept `!` and force you to put in an email address.

**Comment by ljbeal** [comment]
Perfect, thanks! I can confirm that `verdi setup` forces an email, both names and institution with `verdi --version` `AiiDA version 2.4.0.post0`, so this looks to be already fixed.
