### ISSUE TITLE
🐛 Using `engine.submit(wait=True, ...)` always prints a report

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-core#6209]
### Describe the bug

When using `engine.submit()` with `wait` I _always_ get at least one of these reports:

```python
12/08/2023 10:55:18 AM <72751> aiida.engine.launch: [REPORT] Process<44395> has not yet terminated, current state is `ProcessState.FINISHED`.
```

Which is a little confusing and cluttering. ^^ 

### Steps to reproduce

```python
from aiida.calculations.arithmetic.add import ArithmeticAddCalculation

inputs = {'x': orm.Int(1), 'y': orm.Int(2), 'code': orm.load_code('add@localhost')}

engine.submit(ArithmeticAddCalculation, wait=True, wait_interval=5, **inputs)
```

### Expected behavior

We should probably check the process state here and only report that its not yet terminated in case it's not in one of the terminated states:

https://github.com/aiidateam/aiida-core/blob/184fcd16e9a88fbf9d4e754870416f4a56de55b5/aiida/engine/launch.py#L127-L129

### Your environment

- Operating system [e.g. Linux]: macOS Ventura
- Python version [e.g. 3.7.1]: 3.9.18
- aiida-core version [e.g. 1.2.1]: `main` branch

### Additional context

Encountered when testing https://github.com/aiidateam/aiida-core/pull/6202

**Comment by sphuber** [comment]
Is the complaint that you always see this line with the state `ProcessState.FINISHED`? Because if its that, we can simply switch the report before the timeout, then it will always show one line:
``` 
Report: Process<157132> has not yet terminated, current state is `ProcessState.CREATED`.
```
I think this would be fine, because it is correct and the whole point of `wait=True` is to use it in interactive use and so having it print at least one message can be useful to show it did _something_.

Other solution would be to change the implementation to:
```python
while True:
    time.sleep(wait_interval)
    if not node.is_terminated:
        LOGGER.report(f'Process<{node.pk}> has not yet terminated, current state is `{node.process_state}`.')
    else:
        break
```
It is uglier, but the result will be there is no report if the process finishes within the first wait interval. I think I still prefer the first solution. Thoughts @mbercx ?

**Comment by mbercx** [comment]
I agree, the first solution is cleaner. One thing I was still considering to add is the `wait_interval`, so you get something like this:

```
Report: Process<157132> has not yet terminated, current state is `ProcessState.CREATED`. Waiting for 5 seconds.
Report: Process<157132> has not yet terminated, current state is `ProcessState.RUNNING`. Waiting for 5 seconds.
```
