### ISSUE TITLE
🐛 Strange behavior for !has_key filter with SQLite storage backends

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-core#6256]
### Describe the bug

When using the `!has_key` filter for e.g. the `SqliteTempBackend`, the query will return the result multiple times equal to the number of items in the dictionary if that dictionary contains the key.

### Steps to reproduce

The following code for a fresh kernel:

```python
from aiida import orm, load_profile

from aiida.storage.sqlite_temp import SqliteTempBackend

temp_profile = SqliteTempBackend.create_profile('temp-profile')
load_profile(temp_profile, allow_switch=True)

node = orm.Int(1).store()
node.base.extras.set_many({'a': 1, 'b': 2, 'c': 3})

qbuild = orm.QueryBuilder()

filters = {"extras": {"!has_key": "a"}}

qbuild.append(
    orm.Int,
    project=['id'],
    filters=filters,
)
qbuild.all()
```

will return `[[1], [1], [1]]`.

### Expected behavior

The above query should have no results

### Your environment

- Operating system [e.g. Linux]: macOS Sonoma v 14.1
- Python version [e.g. 3.7.1]: 3.10.13
- aiida-core version [e.g. 1.2.1]: 2.5.0

**Comment by danielhollas** [comment]
This is I guess somewhat of a feature request, but at the very least we should fail loudly instead of producing wrong result when user tries to use `has_key` filter with SQLite backend.

**Comment by danielhollas** [comment]
Had a brief look and the `has_key` operator **is** implemented for the SQLite backends, but I guess it just doesn't work correctly when combined with the negation operator?

https://github.com/aiidateam/aiida-core/blob/04926fe20da15065f8f086f1ff3cb14cc163aa08/src/aiida/storage/sqlite_zip/orm.py#L290-L297

In case it's helpful, here's what the function returns for the example in the OP:

```
CASE WHEN (json_type(db_dbnode_1.extras[:extras_1]) = :json_type_1) THEN anon_1.key = :key_1 ELSE :param_1 END
```

@sphuber unless this is resolved, I'd remove the `has_key` implementation for 2.6 so that we don't produce wrong results.
