### ISSUE TITLE
Prefix labels when an archive is imported?

### ISSUE THREAD

**Issue by GeigerJ2** [aiidateam/aiida-core#6333]
Alright, just wanted to bring the idea up here for general discussion. Some background:

I recently stumbled on an issue when trying to run a `WorkChain` defined in an AiiDA plugin ([aiida-icon-clm](https://github.com/DropD/aiida-icon-clm)). As I am new to the plugin, I imported an archive that contained some successful `WorkChain` runs previously done by the author to familiarize myself with it.

In the plugin code, there is a `RemoteData` node loaded via its label, which points to a large calculation input file (in the order of hundreds of gb), located on a special `/store` location on Piz Daint. Now, the import of the `RemoteData` node via its label in the source code of the plugin led to the **corresponding node of the imported archive to be loaded**. However, this `RemoteData` node had a `Computer` instance associated with it from the person who created the archive, which was different from my own `Computer` instance used to then try and run a `WorkChain` myself. Thus, symlinking the `RemoteData` node via the `remote_symlink_list` as done in the `prepare_for_submission` of the `CalcJob` led to the exception:
```shell
It is not possible to create a symlink between two different machines for calculation <pk>.
```
thrown by the `upload_calculation` function in the `execmanager`.

I don't think this is an `aiida-core` issue itself, and it would not occur if one did not import an archive before, or manually loading nodes would be done unambiguously, e.g. via their `uuid`. Also, hard-coded labels should probably not be contained in general AiiDA plugins ([aiida-icon-clm](https://github.com/DropD/aiida-icon-clm) just serves as a proof-of-concept for now).

However, I still think this issue could arise in the future for new users who are just starting out and might do so by importing an archive (like I did myself with the plugin). In that case, similar naming clashes could arise, especially if the `aiida-resource-registry` (`aiida-code-registry`) becomes more widely used, as it basically standardizes `Computer` and `Code` labels. So, should we prefix `Node` labels when an archive is imported, e.g. with `import.`? If so, all of them, or only e.g. `Code`s, `Computer`s and `RemoteData`s? And would that break something?

**Comment by sphuber** [comment]
As you mentioned, the problem here is really the design of the plugin. Not only hardcoding the label of a node in order to load it is far from idael, it also _assumes_ that the user has access to the `/scratch/snx3000/mjaehn/sandbox_workflow/spice/icon-nwp-gpu/externals/ecrad/data` path that it is supposed to reference. To me, this is clearly not part of the plugin itself, but surrounding requirements that should be set up by the user manually. I think it would be like the `aiida-quantumespresso` hardcoding the path of some directory on the remote computer and expecting the pseudopotentials to be there.

I don't think prefixing the labels are going to change much (although it is already done for computers, mind you, since there the label _has_ to be unique). Node labels are not unique, and so are by definition not safe to use as an identifier for loading since it can be ambiguous. This is _especially_ the case when you are sharing nodes with others as you don't know whether others my happen to use the same label for some other node already. Prefixing imported node labels is not going to guarantee that they are unique. There can still be overlaps, breaking the loading functionality using labels. You would have to start scanning the database for all existing labels and trying to figure out a unique label. This is just something users will have to learn: labels are not unique and cannot always be used to load a node.

**Comment by GeigerJ2** [comment]
Thanks for your quick reply, @sphuber! Yeah, I think these things weren't taken care of as it was just a first proof-of-concept. I'll make sure to externalize them as I work on it. The data that is referenced is a bit tricky, though, as it has to be supplied by the corresponding people from the weather and climate community, so one has to get access to that by being in contact with them in any case. Let's see how it evolves, but good to keep all those points in mind if they end up integrating AiiDA into their workflows, and more people use it, hopefully.

Ah, interesting that computers behave like that, and it's already done there! Prefixing certainly wouldn't make them unique, and it wouldn't be a fool-proof solution, but it might resolve the ambiguity when using generic labels, like 'pw-72', for loading `Code`s, which I guess most people do. One could also just apply the prefixing for the `Code`s, where it could occur more frequently, akin to the `Computer`s. Doing it for all nodes does seem unnecessary, so I'll close this. Just wanted to write it out somewhere as it took me some time to trace back :')

**Comment by sphuber** [comment]
> Ah, interesting that computers behave like that, and it's already done there! Prefixing certainly wouldn't make them unique, and it wouldn't be a fool-proof solution, but it might resolve the ambiguity when using generic labels, like 'pw-72', for loading Codes, which I guess most people do.

This is already sort happening indirectly. Because those codes are often created as `InstalledCode` instances, which always define a computer, their "full label" (formed as `code_label@computer.label`) _has_ to be unique. But because the imported computers are suffixed, the associated installed codes will automatically be unique, on their full label that is.

> Just wanted to write it out somewhere as it took me some time to trace back :')

Appreciate the write up! I don't want to discourage these kinds of discussions. They can be very useful.
