### ISSUE TITLE
Problem with --input-calc-forward option of verdi archive create command ?

### ISSUE THREAD

**Issue by sylviancadars** [aiidateam/aiida-core#6506]
### Bug description
Trying to share data produced within aiida (v. 2.5.1) with colleagues, following aiida documentation on the verdi archive create command, I realized that the  --input-calc-forward option appears to yield very strange behaviour. 

### Data organization
For the most part, my database is organized in groups of structures imported (typically with `StructureData(pymatgen=...)` ) from an external crystal structure-prediction (CSP) program, each group corresponding to a single CSP run, and containing nothing but StructureData nodes. Metadata associated with the external calculations are stored in the StructureData.base.extras. All structures are then used as inputs to a rather simple VaspWorkChain, and a post-processing calculation function fetching parameters from the (retrieved) outputs and storing them as an ArrayData. Below is a typical provenance graph associated with one structure in these groups:

![image](https://github.com/aiidateam/aiida-core/assets/3882007/a929fcee-46b9-4c9e-ab95-cf77d6b2f352)

### Steps leading to th bug
A very simple command such as :
`verdi archive create MY_ARCHIVE.aiida --nodes STRUCTURE_PK --test-run`
predicts an archive containing a single node, as expected:

> Report:
> Archive Parameters
> --------------------  ---------
> Path                  tmp.aiida
> Version               main_0001
> Compression           6
> 
> Inclusion rules
> ----------------------------  --------
> Computers/Nodes/Groups/Users  Selected
> Computer Authinfos            False
> Node Comments                 True
> Node Logs                     True
> 
> Traversal rules
> ---------------------------------  -----
> Follow links input calc forwards   False
> Follow links input calc backwards  True
> Follow links create forwards       True
> Follow links create backwards      True
> Follow links return forwards       True
> Follow links return backwards      False
> Follow links input work forwards   False
> Follow links input work backwards  True
> Follow links call calc forwards    True
> Follow links call calc backwards   True
> Follow links call work forwards    True
> Follow links call work backwards   True
> 
> Report: Validating Nodes
> Report: Test Run: Stopping before archive creation
> Report: Archive would be created with:
> ----------------  --
> users              1
> nodes             10
> links              9
> Repository Files   3
> ----------------  --
> Success: wrote the export archive file to tmp.aiida
> 

### Bug description
However, if I run the same command with the --input-calc-forward option: `verdi archive create MY_ARCHIVE.aiida --nodes STRUCTURE_PK --test-run`, aiming at including the workchains and calculations outgoing the StructureData node, the number of predicted nodes explodes to reach more than 16 000, which probably corresponds to my entire database. And importantly, the number is exactly the same if I apply the same command to another structure PK in the same or in another group, or even to an entire group with `verdi archive create MY_ARCHIVE.aiida --groups GROUP_PK --test-run`

> Report:
> Archive Parameters
> --------------------  ---------
> Path                  tmp.aiida
> Version               main_0001
> Compression           6
> 
> Inclusion rules
> ----------------------------  --------
> Computers/Nodes/Groups/Users  Selected
> Computer Authinfos            False
> Node Comments                 True
> Node Logs                     True
> 
> Traversal rules
> ---------------------------------  -----
> Follow links input calc forwards   True
> Follow links input calc backwards  True
> Follow links create forwards       True
> Follow links create backwards      True
> Follow links return forwards       True
> Follow links return backwards      False
> Follow links input work forwards   False
> Follow links input work backwards  True
> Follow links call calc forwards    True
> Follow links call calc backwards   True
> Follow links call work forwards    True
> Follow links call work backwards   True
> 
> Report: Validating Nodes
> Report: Test Run: Stopping before archive creation
> Report: Archive would be created with:
> ----------------  -----
> users                 1
> computers             2
> nodes             16466
> logs               4968
> links             24336
> Repository Files  12839
> ----------------  -----
> Success: wrote the export archive file to tmp.aiida

### Expected behavior

What I wished to produce was to include the original (group of) structure(s) and outgoing calculations, workchains and corresponding outputs in the archive, such that colleagues importing the archive could then access the data with queries targeting the (group -> ) structure(s) -> outgoing processes, using the QueryBuilder.

### Your environment

- Operating system [e.g. Linux]: Linux Ubuntu 20.04.6 LTS
- Python version [e.g. 3.7.1]: 3.11.0
- aiida-core version [e.g. 1.2.1]: 2.5.1

Could you please help me figuring out wether I am doing or understanding something wrong, or is this is a bug of the `--input-calc-forward` option ?

Thank you very much.
All the best.
Sylvian.

**Comment by sphuber** [comment]
Hi Sylvian, thanks for the details description. The behavior of the `--input-calc-forward` option is expected. Given a starting node, it will follow _recursively_ all links that go to calculations. Since you are targeting a "starting" node, i.e., your `StructureData` inputs are the starting point as pretty much all other nodes flow from them, specifying `--input-calc-forward` essentially globs all the nodes in your database. See [this section in the documentation](https://aiida.readthedocs.io/projects/aiida-core/en/stable/topics/provenance/consistency.html#data-and-calculation-nodes) for more details.

What you probably will want to do instead, is to export the `VaspWorkChain` or one of its outputs, instead of the input `StructureData`. The structure will then automatically be included since it is an input. The easiest would be to create a group where you add all your `VaspCalculation` nodes and then write a query to add them. You can then export with the default graph traversal flags.

Something like:
```python
from aiida.orm import Group, StructureData, WorkChainNode
group_structure = load_group('structures')
group_workchains = Group('workchains').store()
query = QueryBuilder()
query.append(Group, filters={'label': group_structure.label}, tag='group')
query.append(StructureData, with_group='group', tag='structure')
query.append(WorkChainData, with_incoming='structure)
workchain_nodes = query.all(flat=True)
group_workchains.add_nodes(workchain_nodes)
```
You should now be able to export with
```
verdi archive create -G workchains -- archive.aiida
```

The one problem remaining is that (based on the layout of your provenance graph) this _won't_ include the `store_nmr_parameters_from_structure` because that is only linked through a forward input-calc link. Does this calcfunction really only use the original input `StructureData` node as input? Anyway, since it doesn't seem linked to the workchain, you will have to do a similar approach to add these to a group to be able to easily export them.

**Comment by sylviancadars** [comment]
Thank you very much Sebastiaan for your answer. However, I may be wring of course, it does not seem correct to me. Indeed, I cannot see how the different starting StructureData nodes can be connected through the outgoing calculations that the --input-calc-forward options asks to follow, even recursively. From my point of view these structures and calculations are completely independent from each other, and none of the outgoing calculations actually create new structures (they are not relaxations), but even if this was the case, I would expect that only the ouput structures (along with other outputs) and, by recursion, calculations that would use them as inputs (but in my case there are no such calculations) would be included in the archive.

This is the reason why this makes me think that it could potentially be a bug.

One possibility that I can see is that generic inputs such as the code, which is the same for all calculations, could be the link connecting all structures ? Does this make any sense at all, and if so and can it be avoided ?

Your alternative solution makes complete sense, however, and I suppose that adding the `store_nmr_parameters_from_structure` CalcFunctionNodes to the group via a similar query would do the job. Initially it just seemed a easier to me to group the initial structures rather than the processes, because everything flows from them. For your information it is a calcfunction that indeed only takes the StructureData node as the input, and then looks for outgoing VaspCalculation processes to use their retrieved outputs (specifically the OUTCAR, processed with the pymatgen.io.vasp.outputs.Outcar class).

All the best.
Sylvian.

**Comment by sphuber** [comment]
> This is the reason why this makes me think that it could potentially be a bug.

I see the point now, I didn't fully understand that your structures were used for just a single workchain.

> One possibility that I can see is that generic inputs such as the code, which is the same for all calculations, could be the link connecting all structures ? Does this make any sense at all, and if so and can it be avoided ?

This is probably exactly what is happening. Assuming that you used a single `Code` node for all workchains (which is very common and perfectly reasonable to do) it would indeed become a central vertex from which all other nodes are globbed that are connected to it (since `--input-calc-forward` is now enabled). The critical thing to understand about the graph traversal rules is that they are all applied at the same time and then all connections are explored exhaustively.

I guess this is why typically for these kinds of use-cases, it are either the processes or (one of) their outputs that are put in a group and used for easy export.

> For your information store_nmr_parameters_from_structure is a calcfunction that indeed only takes the StructureData node as the input, and then looks for outgoing VaspCalculation processes to use their retrieved outputs (specifically the OUTCAR, processed with the pymatgen.io.vasp.outputs.Outcar class).

Although possible, I don't think this is the ideal approach. As you can see from the provenance graph, it is not immediately visible that the output of the calcfunction _actually_ depends on outputs from the `VaspCalculation`. As a general rule of thumb, it is better to pass all input that a calcfunction needs as a direct input node and not use the `QueryBuilder` or the ORM to retrieve additional input indirectly through a part of the input nodes. Then you will have a direct link from the VaspCalculation output to the calcfunction which better represents what is going on. If you know add the output of the calcfunction to a group, that is the _only_ group that you would have to export and all relevant ondes will automatically be attached.

**Comment by sylviancadars** [comment]
Thank you very much Sebastiaan for the carifications and explanations.

Your solution to avoid the problem worked just as just expected and required very little adaptation to 

Regarding the matter of the code input (and maybe other inputs such as pseudopotentials) being generic and consequently causing unwanted links between nodes that would otherwise be independent: would it be possible in the future to assign a speficic character to these node to prevent the input-calc/work-forward options from taking them into account ?  It would see to make much sense to me, but I don't know if this is technically feasible.

To be (maybe) continued.
Best wishes.

**Comment by sphuber** [comment]
> would it be possible in the future to assign a speficic character to these node to prevent the input-calc/work-forward options from taking them into account ? It would see to make much sense to me, but I don't know if this is technically feasible.

Not sure, we would have to think about how that would really work. Let's assume you could "tag" your input structure as to be excluded from the `--input-calc-forward` rule. I think technically this would be possible, but then the graph traversal would halt right at that node and not include anything else. Clearly this is not what you want. You would want the workchain that you are targeting in your head to be included, but how do you communicate that? I think you would anyway end up again with an approach that I suggested where rather you target an _output_ node, that will end up including the original input structure that you intended to be included.

I will close this for now. If you have a concrete suggestion for functionality/behavior, feel free to reopen it or open a feature request.
