### ISSUE TITLE
RTD build failing on `main` due to issue with `PluggableSchemaValidator` of `pydantic`

### ISSUE THREAD

**Issue by GeigerJ2** [aiidateam/aiida-core#6514]
Hi all,
seems like the RTD build is failing on `main` due to some `pydantic` issue with the `PluggableSchemaValidator`. They released a 2.8.2 patch release yesterday, with a change referencing this class, though building locally with this version, I still get the respective warnings (which I suppose are making the build fail). Also getting the warnings with 2.8.0 (which was released on 2024-07-01), which is the current default version installed from the `pydantic~=2.4` specification in our `pyproject.toml`. With `pydantic` version 2.7.4 (last one before 2.8.0), I'm not getting the warnings locally, so I suppose the build would work via GitHub actions. Still trying to better traceback the issue locally. Maybe one of the more senior people can also weigh in, regarding dependency management in AiiDA?

Thanks!

EDIT: We also fix the version of `pydantic-core` in the `requirements/requirements-py-3.[9-12].txt` files, but not in `pyproject.toml`. Possibly also something to consider?

![image](https://github.com/aiidateam/aiida-core/assets/41700727/33374352-89fe-40a9-8278-47dc3049dd13)
![image](https://github.com/aiidateam/aiida-core/assets/41700727/5e685b21-d7b5-4b41-911e-a18f6062e05a)

**Comment by sphuber** [comment]
> which I suppose are making the build fail

Yes, we run with the nitpick option which causes any warning to fail the build.

> hey released a 2.8.2 patch release yesterday, with a change referencing this class, though building locally with this version, I still get the respective warnings

I think this is actually the change that is causing the breaking behavior. I can reproduce the warnings with 2.8.2 but 2.8.0 and 2.8.1 run just fine. This matches with the builds on Github actions starting to fail only since yesterday.

Honestly, with these kinds of problems, we just add the class to the nitpick ignore list in `docs/source/nitpick-exceptions`. The warning doesn't affect the docs and trying to fix it takes way too much time.

>  We also fix the version of pydantic-core in the requirements/requirements-py-3.[9-12].txt files, but not in pyproject.toml. Possibly also something to consider?

The requirements files and the `pyproject.toml` serve different purposes. The `pyproject.toml` provides abstract requirements and should aim to be as "loose" as possible, i.e., putting version limits and pinning only when necessary. The requirements files use all pinned versions though and serve as a historical complete record of an environment that should work.

**Comment by GeigerJ2** [comment]
> Yes, we run with the nitpick option which causes any warning to fail the build.

Yes, I'm aware of this.
 
> I think this is actually the change that is causing the breaking behavior. I can reproduce the warnings with 2.8.2 but 2.8.0 and 2.8.1 run just fine. This matches with the builds on Github actions starting to fail only since yesterday.

I was thinking the same, wouldn't make sense, as before it was working fine. Hm, weird, I tried 2.8.0 again now and it worked indeed. Probably doing too many things at the same time again :D 
 
> Honestly, with these kinds of problems, we just add the class to the nitpick ignore list in `docs/source/nitpick-exceptions`. The warning doesn't affect the docs and trying to fix it takes way too much time.

That's good, fully agree. 

> The requirements files and the `pyproject.toml` serve different purposes. The `pyproject.toml` provides abstract requirements and should aim to be as "loose" as possible, i.e., putting version limits and pinning only when necessary. The requirements files use all pinned versions though and serve as a historical complete record of an environment that should work.

Thanks for the clarification!
