### ISSUE TITLE
New graph update functionality

### ISSUE THREAD

**Issue by lekah** [aiidateam/aiida-core#924]
Functionality of AiiDA often depends on ways to update the graph based on a specific rule;
examples of implemented graph-update functions in AiiDA:
- export: if group is passed, all members of the group; for every node, find me all ancestors. For every calculation of this set, give me also data output. 
- graph generate: for every node, give me ancestors and descendants, optionally with a certain depth. Optionally, give me all inputs or outputs of all calculations in the resulting set.

There will  be more to come. AiiDA should provide developers and users an easy/robust way to do such graph-updates from a starting subgraph. It will depend on the QueryBuilder for the particular queries, and should include all the entities exposed to the user (Group, Node, Computer, User).

**Comment by lekah** [comment]
@broeder-j pointed out another usecase: Deletion of nodes always happens accounting also for the connectivity of the node. I.e. called work for workflows, descendendants for data, etcpp. 
It should be possible to remove subgraphs, but the tool for it should be transparent and safe.

**Comment by giovannipizzi** [comment]
Also, as a rule: each calculation should "bring" with itself its direct inputs and outputs. For data instead there is not this rule.
Note this is true (and probably I would say compulsory) when exporting data. Instead, it should *not* be applied when deleting (at least not by default) because otherwise e.g. if one uses a pseudo potential just imported for the first time and then deletes the calculation, they will then delete also the group.
Maybe there's some clever logic to do the right thing (e.g. if the input data node is not used by any other calculation, has no parents *and* is not part of any group (except maybe the autogroups created when you do 'verdi run'), then you can delete it, or something like this.

**Comment by ltalirz** [comment]
@lekah @ramirezfranciscof 
Can this issue now be closed?

**Comment by ramirezfranciscof** [comment]
Indeed, this is exactly the AGE.
