### ISSUE TITLE
Simple way to export an entire database

### ISSUE THREAD

**Issue by oschuett** [aiidateam/aiida-core#974]
It would be nice if there were a simple way to export an **entire** AiiDA database.
This would be very useful for collaboration and backup alike.

**Comment by ltalirz** [comment]
Not sure what others have to say on this, but in my opinion this should even be the default behavior of `verdi export`, when the user does not specify any of the options for selecting nodes.
Perhaps a `click.confirm` would be appropriate.

**Comment by giovannipizzi** [comment]
We're working on this - at this stage, I would rather add a `--all-nodes` flag, both because the current export is a bit slow (and can run out of memory) if too many attributes are exported, and because there are some things (notably, the new call links) that are not exported.
With @szoupanos we're improving the export, in the future it could be the default (or at least it might be the default of the push/pull commands @szoupanos is developing)

**Comment by ltalirz** [comment]
@szoupanos I think this is very important, in particular since people working with aiida now start to have to back up their stuff.
I believe we should add this in 0.12.x for this reason

**Comment by ltalirz** [comment]
Discussion April 17th, 2019:
   * to add `--all` option, which exports: all nodes (with extras), groups, users, computers, comments, logs
     * add both in 1.0 and 0.12
     * if anything is not taken by default, mention this in the documentation!
     * mention that this is not the same as a database backup, since PKs will change
   * to decide in the future whether you might want to make this option the default (depending on what users usually want when doing `verdi export`)
